### ISSUE TITLE
Define what baggage attributes should be set, and how they should be consumed by other services.

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry-demo#100]
The demo should utilize baggage for telemetry attributes, demonstrating the following:

- Creating baggage
- Propagating baggage
- Extracting baggage and appending it to telemetry signals (metrics, logs, traces)

The two baggage signals that should be set are the following:

- `synthetic_request`: `true` or `false` set by load generator service
- `session_id`: string set by frontend service

These baggage attributes should be extracted from context and set on telemetry signals in each service --

- Exception/Error logs should receive the session ID
- Frontend (optionally, other downstream services) should receive the session ID and synthetic request flag.

**Comment by austinlparker** [comment]
`synthetic_request` should be extracted in paymentservice and added to span attributes.

**Comment by cartersocha** [comment]
Defined and implemented. Closing this
