### ISSUE TITLE
Getting a Bootstrap validation error with the Frontendproxy

### ISSUE THREAD

**Issue by munibshah** [open-telemetry/opentelemetry-demo#1019]
# Bug Report

Which version of the demo you are using? 
https://github.com/open-telemetry/opentelemetry-demo/commits/main

## Symptom

I am deploying using the kubernetes/opentelemetry-demo.yaml file and my frontendproxy throws the following error:

```
opentelemetry-demo-frontendproxy-567ff6f5fd-fnx55           0/1     CrashLoopBackOff   9 (51s ago)        21m

Proto constraint validation failed (BootstrapValidationError.StaticResources: embedded message failed validation | caused by StaticResourcesValidationError.Clusters[0]: embedded message failed validation | caused by ClusterValidationError.LoadAssignment: embedded message failed validation | caused by ClusterLoadAssignmentValidationError.Endpoints[0]: embedded message failed validation | caused by LocalityLbEndpointsValidationError.LbEndpoints[0]: embedded message failed validation | caused by LbEndpointValidationError.Endpoint: embedded message failed validation | caused by EndpointValidationError.Address: embedded message failed validation | caused by AddressValidationError.SocketAddress: embedded message failed validation | caused by field: "port_specifier", reason: is required): static_resources 
```

**What is the expected behavior?**
Frontendproxy pod should be running 
What do you expect to see?
Frontendproxy pod throws the above mentioned error 

## Additional Context

Here is my kubectl version:

```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:27:13Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
```

I am running K8s on Ubuntu 22.04

**Comment by julianocosta89** [comment]
Hello @munibshah, could you check if you have the latest updates in your main branch?
We had an issue that was supposed to be fixed with https://github.com/open-telemetry/opentelemetry-demo/pull/981.

Let us know if pulling the latest commits of main solves your issue.

**Comment by noMoreCLI** [comment]
I could solve this issue with building the fontendproxy
`docker-compose build frontendproxy`

In addition I needed to change the image for the otel-collector - I did set it to `otel/opentelemetry-collector-contrib:0.76.1` from the original value `${IMAGE_NAME}:${IMAGE_VERSION}-otelcol`

**Comment by munibshah** [comment]
I was able to solve it by adding this to the environment variables as mentioned in a previous fix

       - OTEL_COLLECTOR_PORT=${OTEL_COLLECTOR_PORT_GRPC}

**Comment by julianocosta89** [comment]
Thanks for the feedback everyone.

We have made some breaking changes that are not published to the registry yet.

This should be solved with the release of version 1.5.
It should happen by the beginning of next week.

**Comment by chenmancm** [comment]
Hi,

I'm trying to deploy the demo by docker and having the same error:
```
2023-08-07 18:23:04 [2023-08-07 10:23:04.897][7][critical][main] [source/server/server.cc:117] error initializing configuration 'envoy.yaml': Proto constraint validation failed (BootstrapValidationError.StaticResources: embedded message failed validation | caused by StaticResourcesValidationError.Clusters[0]: embedded message failed validation | caused by ClusterValidationError.LoadAssignment: embedded message failed validation | caused by ClusterLoadAssignmentValidationError.Endpoints[0]: embedded message failed validation | caused by LocalityLbEndpointsValidationError.LbEndpoints[0]: embedded message failed validation | caused by LbEndpointValidationError.Endpoint: embedded message failed validation | caused by EndpointValidationError.Address: embedded message failed validation | caused by AddressValidationError.SocketAddress: embedded message failed validation | caused by field: "port_specifier", reason: is required): static_resources {
```

Looking forward to opentelemetry-demo:1.5 which will fix the bug.

**Comment by julianocosta89** [comment]
Same as #971

**Comment by n-able-consulting** [comment]
same issue for default helm chart:

bare-metal k8s: 1.28.1
following https://opentelemetry.io/docs/kubernetes/helm/demo/
using helm chart: open-telemetry/opentelemetry-demo

**Comment by julianocosta89** [comment]
Hello all, could you try the latest release?
`1.5.0` was released 2 days ago, and should have solved those issues.

**Comment by IppX** [comment]
@julianocosta89 I confirm, bumping the frontend image tag from `1.4.0-frontendproxy` to `1.5.0-frontendproxy` worked. Thanks!

**Comment by julianocosta89** [comment]
Thank you for confirming @IppX!
