### ISSUE TITLE
Give a simple example to use this client demo for AdService

### ISSUE THREAD

**Issue by laziobird** [open-telemetry/opentelemetry-demo#102]
**Is your feature request related to a problem?**

@mic-max  @reyang   

I found a client sample for this Java Project called "AdService" , and it is able to some steps for running  , like this 

1. build a image for AdService , for example:
```shell
cd  /${project}/opentelemetry-demo-webstore/src/adservice
docker build -t  adservice:v1  . 
```
2. run a instance for AdService by Docker, for example:
```shell
docker run -d -p 9555:9555 adservice:v1 
```
3.  enter into the docker instance and start a client demo, for example:
```shell
docker exec -it 3d6a8db7322a /bin/sh
sh /app/build/install/hipstershop/bin/AdServiceClient
```
4.  check  if  AdServer is  successful to start  by the log of this client  , for example :   
```shell
2022-06-03 17:57:11 - hipstershop.AdServiceClient - Get Ads with context camera ... trace_id= span_id= trace_flags= 
2022-06-03 17:57:12 - hipstershop.AdServiceClient - Ads: Hairdryer for sale. 50% off. trace_id= span_id= trace_flags= 
2022-06-03 17:57:12 - hipstershop.AdServiceClient - Ads: Bamboo glass jar for sale. 10% off. trace_id= span_id= trace_flags= 
```

**Describe the solution you'd like:**

So, i want to add more details for how to run a client and check the  AdService . Maybe there ? https://github.com/open-telemetry/opentelemetry-demo-webstore/blob/main/src/adservice/README.md 

**Describe alternatives you've considered.**

A suggestion is just for more people to use this Java demo easily .   What do you think? 😊

**Comment by mic-max** [comment]
That's great!!!

I think these instructions also belong in `/src/adservice/README.md` and also think we should still use the `docker compose up` command for running the service though to keep it simple and not give lots of ways to run these containers, especially if (not in this case) the service depends on another service or resource.

**Comment by julianocosta89** [comment]
AdService client was removed as wasn't being used in the demo.
