### ISSUE TITLE
using 'internal' grafana dashboard JSONs limits usage and compatibility

### ISSUE THREAD

**Issue by horovits** [open-telemetry/opentelemetry-demo#1032]
# Bug Report

Which version of the demo you are using?
1.4.0

## Symptom
The current demo offers existing grafana dashboard JSONs, found under
opentelemetry-demo/src/grafana/provisioning/dashboards/general
These dashboard JSON are set as internal. This means that one cannot import and use the dashboard JSON with another datasource, and will only run on the local instance of the demo. This means that users that use the demo with their own Prometheus or Prometheus-compatible instance, for example, will have trouble trying out the demo in this setup.

**What is the expected behavior?**
I suggest using external grafana dashboard JSON, namely ones that were exported to JSON with the 'external' flag on, an thus have the necessary   "__inputs" headers.
with the 'external' flag used, users could import and use the dashboard JSON with their own instance if so desired.

**What is the actual behavior?**
currently these JSONs fail to import when using other datasource. 

What did you see instead?
One needs to load the dashboard locally and then export to another JSON with the 'external' flag turned on, to have a JSON that can be used with other instances.

## Reproduce
spin up an instance of granfa of your own.
open the dashboard browser window in grafana UI
click 'import', and choose the demo dashboard JSON from opentelemetry-demo/src/grafana/provisioning/dashboards/general
click to import. 

We will close this issue if:

* The steps you provided are complex.
* If we can not reproduce the behavior you're reporting.

## Additional Context
The 'external' flag is a built-in feature in grafana, that is designed exactly for this purpose, of enabling dashboards to be used externally. In the negligible cost of exporting as 'external', the demo dashboards will be usable in a far wider range of use cases and environments.

**Comment by mviitane** [comment]
Seems a good improvement to me.

**Comment by austinlparker** [comment]
This must have gotten fixed somewhere along the way, because I can import all of these dashboards just fine.
