### ISSUE TITLE
`otelsarama` got deprecated

### ISSUE THREAD

**Issue by julianocosta89** [open-telemetry/opentelemetry-demo#1080]
As of the new release notes of `opentelemetry-go-contrib`, `otelsarama` got deprecated https://github.com/open-telemetry/opentelemetry-go-contrib/pull/4099.

We are currently using it in AccountingService https://github.com/open-telemetry/opentelemetry-demo/blob/main/src/accountingservice/go.mod#L9.

We need to update it to the new supported instrumentation package.

**Comment by julianocosta89** [comment]
@pellared do we already have a solution for this?
Or the options mentioned in https://github.com/open-telemetry/opentelemetry-go-contrib/pull/4099 are still in discussion?

**Comment by pellared** [comment]
> Or the options mentioned in [open-telemetry/opentelemetry-go-contrib#4099](https://github.com/open-telemetry/opentelemetry-go-contrib/pull/4099) are still in discussion?

That is the current state. I am leaning towards Option A and awaiting feedback: https://github.com/IBM/sarama/issues/2510

I think that for demo purposes you can still use the deprecated package. It is unmaintained but "working".
