### ISSUE TITLE
True correlation between trace,logs and metrics

### ISSUE THREAD

**Issue by gajavallisantosh** [open-telemetry/opentelemetry-demo#1116]
Describe the bug
True correlation between trace,logs and metrics

True correlation between trace,logs and metrics

Describe the bug
Unable to correlate with the same tarceid/span id between a trace,log and metrics

Expected behavior
Please give a working example or show me a link where i can get true correlation between 3 pillars of observability

in .NET this feature is unavailable, just want to know whether Java supports it

**Comment by austinlparker** [comment]
Logs, metrics, and traces should all emit shared trace and span IDs if they exist. 

Closing this as part of issue cleanup. If there's anything that needs to be done, please create a new issue.
