### ISSUE TITLE
Validate make start performance

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry-demo#1135]
This issue is meant to collect benchmarks from running 'make start' with a clean cache.

Process:
- Prune all images from docker cache
- Set .env version to 'local'
- Run make start

**Comment by julianocosta89** [comment]
Ubuntu
Processor: `11th Gen Intel® Core™ i9-11950H @ 2.60GHz × 16`
Memory: `64,0 GiB`

I've done 2 tests:
- Test 1
  ```
  docker system prune -a
  docker compose build
  ```
  Total of 34m

- Test 2 (changed `version` to `local`)
  ```
  docker system prune -a
  make start
  ```
  Total of  32m

**Comment by julianocosta89** [comment]
> Huh, this seems like a weird outlier. My Windows build was on a 9th Gen Intel chip... I assume this is a laptop?

Yep, laptop

**Comment by danielbdias** [comment]
Hi folks! Here are some tests with my machine:

OS: MacOs Ventura 13.5.2
Computer: iMac 2017

Processor: 3,4 GHz Quad-Core Intel Core i5
Memory: 24,0 GiB

Internet speed: 218 Mbps

Ran `docker system prune -a`

Test 1 - `time docker compose build`
Total: 24m 36s

Test 2 - `time make start`
Total: 7m 44s

Remark: I'm not sure if I set the `env` as `local`, I'm using the following vars:
```
```

**Comment by julianocosta89** [comment]
> Ubuntu
> Processor: `11th Gen Intel® Core™ i9-11950H @ 2.60GHz × 16`
> Memory: `64,0 GiB`
>   ```
>   
>   docker system prune -a
>   
>   docker compose build
>   ```
> Total of 34m

When using the internet at the office, I'm down to 8m30s, so it seems that my home internet just sucks 😅

**Comment by austinlparker** [comment]
Closing this as part of issue cleanup. If there's anything that needs to be done, please create a new issue.
