### ISSUE TITLE
Issue in deployed 1.5version OpenTelemetry Demo application - Grafana & Featureflag service

### ISSUE THREAD

**Issue by manjejda** [open-telemetry/opentelemetry-demo#1136]
# Question

Use [Github Discussions](https://github.com/open-telemetry/opentelemetry-demo/discussions/).

Hi Experts,
I have deployed the latest 1.5 version of Opentelemetry demo application in my machine. By running docker compose command installed all the services and application. Facing below 2 issues post deployment:

1. FeatureFlag service URL is working with respective port, but none of the links of Feature flag URL is not working, giving 404 not found, so unable to update the Featureflag from false to true. Please find below screenshot.
![image](https://github.com/open-telemetry/opentelemetry-demo/assets/144259189/39ac3309-9fc8-4fb1-bfa4-84f6cccc8688)

2. Grafana URL is not working, not even loading or hit. Facing issue of "Page cannot be displayed". Please find below screenshot for more reference.

![image](https://github.com/open-telemetry/opentelemetry-demo/assets/144259189/7844fe99-4302-4ab1-89e2-f0b0e8ed51d9)
Also observed vulnerabilities in grafana image:
![image](https://github.com/open-telemetry/opentelemetry-demo/assets/144259189/91964bdb-ad5c-4b43-a59e-c7968164468f)

Logs Details: 
logger=provisioning.datasources t=2023-09-20T15:38:35.841000677Z level=info msg="inserting datasource from configuration " name=Prometheus uid=webstore-metrics
logger=provisioning.datasources t=2023-09-20T15:38:35.866052117Z level=info msg="inserting datasource from configuration " name=Jaeger uid=webstore-traces
logger=provisioning.plugins t=2023-09-20T15:38:35.881791883Z level=error msg="Failed to read plugin provisioning files from directory" path=/etc/grafana/provisioning/plugins error="open /etc/grafana/provisioning/plugins: no such file or directory"
logger=provisioning.notifiers t=2023-09-20T15:38:35.882108584Z level=error msg="Can't read alert notification provisioning files from directory" path=/etc/grafana/provisioning/notifiers error="open /etc/grafana/provisioning/notifiers: no such file or directory"
logger=provisioning.alerting t=2023-09-20T15:38:35.882454996Z level=error msg="can't read alerting provisioning files from directory" path=/etc/grafana/provisioning/alerting error="open /etc/grafana/provisioning/alerting: no such file or directory"

**Comment by mviitane** [comment]
Hi @manjejda, do you still have this issue? I've also sometimes seen similar problems with the feature flag service, possibly related to some cache issues in docker. For me, it has helped to prune my docker environment and redeploy the app.
`docker system prune -a`

**Comment by julianocosta89** [comment]
Shouldn't be `localhost:8080/feature`?

**Comment by manjejda** [comment]
> Shouldn't be the following?
> 
> * `localhost:8080/feature`
> * `localhost:8080/grafana`
> * `localhost:8080/jaeger/ui`
> * `localhost:8080`

Hi, 
Thanks for your quick turnaround, when we deploy in our local machine, it doesnt take the same port always. Only application uses 8080 and others uses different port. Is there any settings need to be done for it as a pre-requisite?

Finally i was able to access Grafana, but facing issue with Featureflagservice still [am seeing 404s for all links as shown above]

**Comment by manjejda** [comment]
> Hi @manjejda, do you still have this issue? I've also sometimes seen similar problems with the feature flag service, possibly related to some cache issues in docker. For me, it has helped to prune my docker environment and redeploy the app. `docker system prune -a`

Hi Mviitane,
Thanks for your response.
i tried redeploying multiple times, still the same, can you please give me clear steps to do the cache clear.

`docker system prune -a` : This command should run before docker compose.
Please help here

**Comment by mviitane** [comment]
> can you please give me clear steps to do the cache clear.

I do it in this order:
```
docker compose down
docker system prune -a
docker compose build
docker compose up
```
I like to build the demo app myself to get the latest bug fixes and improvements. That's why the build part.

The prune command cleans up all your downloaded and built resources — images, containers, volumes, and networks.

**Comment by puckpuck** [comment]
All services in the demo are exposed through the frontendProxy only which runs on port 8080.

I recommend you use `make start` and `make stop` to start and stop the demo. Doing this will also output the URLs on how to access each demo component.

**Comment by manjejda** [comment]
> docker system prune -a

Tried the same, but still no luck, causing the same issue after clearing cache and run also.

**Comment by mviitane** [comment]
> when we deploy in our local machine, it doesnt take the same port always. Only application uses 8080 and others uses different port. Is there any settings need to be done for it as a pre-requisite?

The ports are defined in `.env` file. Have you done any changes there? In general, there shouldn't be a need to do port changes. Also, the services should always use the same ports.

It would also help to know more about your environment:
- operating system
- CPU
- RAM amount
- docker and docker compose versions

When you have the app running, do all services start normally?
`docker compose ps`

**Comment by puckpuck** [comment]
@manjejda we don't expose the feature flag, Grafana, Jaeger, etc., UIs directly. They are all exposed through the frontend proxy service on port 8080. 

This was done to minimize port conflicts on local systems.

For example to access Jaeger you will use http://localhost:8080/jaeger/ui. Not using the URLs exposed by the frontend proxy will lead to odd results like you are showing screenshots of.

**Comment by manjejda** [comment]
Thanks all for quick turnaround, 2 issues which i had mentioned [Grafana issue and Feature flag issue], Grafana issue resolved. :)
Need help on Feature flag issue, am able to access feature flag service URL with the port.
But the page doesnt look completely downloaded with css, js etc. When i click on the links of editing, showing, deleting the flag services [any hyperlink] is not working.  For every link am getting page not found [404 error].

![image](https://github.com/open-telemetry/opentelemetry-demo/assets/144259189/134d4020-64c9-4efa-ab72-fee00f7b7d61)

**Comment by julianocosta89** [comment]
> @manjejda we don't expose the feature flag, Grafana, Jaeger, etc., UIs directly. They are all exposed through the frontend proxy service on port 8080.
> 
> This was done to minimize port conflicts on local systems.
> 
> For example to access Jaeger you will use http://localhost:8080/jaeger/ui. Not using the URLs exposed by the frontend proxy will lead to odd results like you are showing screenshots of.

Web Store:
* `localhost:8080`

FeatureFlagService:
* `localhost:8080/feature`

Grafana:
* `localhost:8080/grafana`

Jaeger:
* `localhost:8080/jaeger/ui`

**Comment by manjejda** [comment]
Thanks all for the input, i am not trying to change the port, its automatically changing. Sometime am seeing proxy server is not running giving below error. if i restart also it will go down with below errors:

[2023-10-05 16:26:36.138][8][info][main] [source/server/server.cc:394]   envoy.upstreams: envoy.filters.connection_pools.tcp.generic
[2023-10-05 16:26:36.138][8][info][main] [source/server/server.cc:394]   envoy.resolvers: envoy.ip
[2023-10-05 16:26:36.148][8][critical][main] [source/server/server.cc:117] **error initializing configuration 'envoy.yaml': Proto constraint validation failed (BootstrapValidationError.StaticResources: embedded message failed validation | caused by StaticResourcesValidationError.Clusters[0]: embedded message failed validation | caused by ClusterValidationError.LoadAssignment: embedded message failed validation | caused by ClusterLoadAssignmentValidationError.Endpoints[0]: embedded message failed validation | caused by LocalityLbEndpointsValidationError.LbEndpoints[0]: embedded message failed validation | caused by LbEndpointValidationError.Endpoint: embedded message failed validation | caused by EndpointValidationError.Address: embedded message failed validation | caused by AddressValidationError.SocketAddress: embedded message failed validation | caused by field: "port_specifier", reason: is required):** static_resources {
  listeners {
    address {
      socket_address {
        address: "0.0.0.0"
        port_value: 8080
      }
    }

**Comment by julianocosta89** [comment]
could you do the following steps and paste the results afterwards?

```
docker compose down
docker system prune -a

make start
```

**Comment by puckpuck** [comment]
Something on your system is already binding to port 8080, preventing the frontend proxy from starting up.

You can search the `.env` file for references to port `8080` and change it to another port (ie: 8888).  Once done, you can use `docker compose up` to start the demo, and connect to the feature flag service with a URL like http://localhost:8888/feature/

**Comment by puckpuck** [comment]
Closing this issue. How to change the demo's frontend-proxy port is documented here: https://opentelemetry.io/docs/demo/docker-deployment/#changing-the-demos-primary-port-number
