### ISSUE TITLE
Define and add OpenSLO definitions for user journeys through demo application

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry-demo#114]
In order to provide some guidelines for monitoring, we should define SLOs for key user journeys through the application, and use [OpenSLO](https://github.com/OpenSLO/OpenSLO) to define them.

**Comment by cartersocha** [comment]
I think someone from the open slo community volunteered to help you with this. I’m going to check our slack

**Comment by weyert** [comment]
You can assign this one to me

**Comment by austinlparker** [comment]
Closing as this is not currently on the roadmap
