### ISSUE TITLE
Update metric exporter to use OTLP instead of prom

### ISSUE THREAD

**Issue by cartersocha** [open-telemetry/opentelemetry-demo#1143]
Prometheus now supports native OTel ingestion. We should update the metric export to use our native protocol 

https://horovits.medium.com/prometheus-now-supports-opentelemetry-metrics-83f85878e46a

**Comment by reyang** [comment]
FYI - we made a recent change in the OpenTelemetry .NET repo to use OTLP -> Prometheus https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/metrics/getting-started-prometheus-grafana#collect-metrics-using-prometheus.
