### ISSUE TITLE
opentelmetry demo - prometheus targets are down

### ISSUE THREAD

**Issue by prashantnitt07** [open-telemetry/opentelemetry-demo#1144]
# Question

Use [Github Discussions](https://github.com/open-telemetry/opentelemetry-demo/discussions/).

![image](https://github.com/open-telemetry/opentelemetry-demo/assets/31304206/4879324d-e7c6-45fc-9632-eb69cb2a180b)

opentelmetry demo - prometheus targets are down
please find attached

**Comment by puckpuck** [comment]
We have moved Prometheus to use OTLP write instead of scraping. Prometheus is now started without any scrape targets with #1174
