### ISSUE TITLE
OTEL - kubernetes demo -  Images pulling issue for singlenode kind cluster

### ISSUE THREAD

**Issue by gajavallisantosh** [open-telemetry/opentelemetry-demo#1161]
Team,

we are trying to deploy the OTEL kubernetes demo inside single node kind cluster following the documentation 
https://opentelemetry.io/docs/demo/kubernetes-deployment and while performing step  "kubectl apply --namespace otel-demo -f https://raw.githubusercontent.com/open-telemetry/opentelemetry-demo/main/kubernetes/opentelemetry-demo.yaml" , we are unable to pull images and attached the error .
"Service": rpc error: code = Unknown desc = failed to pull and unpack image "ghcr.io/open-telemetry/demo:1.5.0-shippingservice": failed to resolve reference "ghcr.io/open-telemetry/demo:1.5.0-shippingservice": failed to do request: Head "https://ghcr.io/v2/open-telemetry/demo/manifests/1.5.0-shippingservice": tls: failed to verify certificate: x509: certificate signed by unknown authority"

This is happening for all images and images name referenced below
![image](https://github.com/open-telemetry/opentelemetry-demo/assets/144720501/bc67667d-8f61-499b-ba6d-16bd39a10ace)

Please let us know any fix for this.

**Comment by styblope** [comment]
Looks more like a cluster CA availability issue rather than the demo problem. Check the your kind node certs. Also what kind provider do you use - docker/podman? What is the OS environment?

**Comment by puckpuck** [comment]
@gajavallisantosh are you still have issues with this and the latest release?
