### ISSUE TITLE
I want to deploy otel collector with elastic apm as back end in kind cluster where to put service name

### ISSUE THREAD

**Issue by khossain-clgx** [open-telemetry/opentelemetry-demo#1199]
# Question
I am planning to deploy the OpenTelemetry Collector with Elastic APM as the backend in a Kind cluster. Could you please guide me on where to specify the service name in the configuration file that I am currently using?. I am using the attached configuration file

Use [Github Discussions](https://github.com/open-telemetry/opentelemetry-demo/discussions/).
[valuesv1.zip](https://github.com/open-telemetry/opentelemetry-demo/files/13187010/valuesv1.zip)

**Comment by puckpuck** [comment]
Bringing your own backend like Elastic APM is documented on the [OpenTelemetry docs site](https://opentelemetry.io/docs/demo/kubernetes-deployment/#bring-your-own-backend)
