### ISSUE TITLE
Frontend service fails with 503 errors after running for about a week

### ISSUE THREAD

**Issue by AlexPSplunk** [open-telemetry/opentelemetry-demo#1210]
# Bug Report

Which version of the demo you are using? 
Commit [fc01d8f](https://github.com/open-telemetry/opentelemetry-demo/commit/fc01d8f46f9d2a1cac6a4e674662fbfe8b66f3c4)

## Symptom

After being up for about a week, frontend container returns errors to after running for about a week.
Specifically, http get requests to frontend return a 503 error.  The logs of the container show exceptions with a stack trace.
I can delete the frontend pod, causing it to be respawned.  The new container runs for about 8 hours before showing the same problem.  I have been running for about 2 weeks now, and it stays up for just about a workday.  Every morning I have to restart the frontend pod.
I have tried restarting other pods instead, including adservice and featureflag, but neither of those will fix it -- I have to restart frontend.

Stack traces are not always the same - it fails in different places on different days.  However, on any single day the stack traces are always the same.  Attached are 3 files for different stacktraces.  

**What is the expected behavior?**

Frontend continues to work after a week.

**What is the actual behavior?**

Frontend works for about a week, then fails to respond to requests and logs show .js exceptions with stack trace.  Restarting the pod fixes it for about 8 hours, then it fails again.

## Reproduce

Run the demo for a week straight on EKS (environment details below).  After about a week, frontend starts returning 503 errors to requests.

## Additional Context
Environment:
Amazon EKS Running Kubernetes 1.28.  Node AMI is 1.28.1-20230919.
4 Nodes in Cluster:
  2 of m5.large (2vCPU, 8GB memory, x86)
  2 of t2.xlarge (4 vCPU, 16GB memory, x86)

I built the images myself, with no code changes.  Images are hosted on ghcr.io.

Stack trace Files
[resource_exhausted_error_trace.txt](https://github.com/open-telemetry/opentelemetry-demo/files/13245227/resource_exhausted_error_trace.txt)
[error_trace_recommendations_failure.txt](https://github.com/open-telemetry/opentelemetry-demo/files/13245228/error_trace_recommendations_failure.txt)
[error_trace_ff_failure.txt](https://github.com/open-telemetry/opentelemetry-demo/files/13245229/error_trace_ff_failure.txt)

Helm deployment values file:
[otel-demo-astronomyshop.yaml.txt](https://github.com/open-telemetry/opentelemetry-demo/files/13245246/otel-demo-astronomyshop.yaml.txt)

**Comment by baerchen110** [comment]
I've got the same issue, 503 error on frontend service, after that the demo has been running for 8 hours

**Comment by JanOberserve** [comment]
I got the same issue. But I think I might have found the root-cause. It looks like the Productcatalogservice has a memory leak. After the second crash (in this example 20:40) the frontend starts to hang and send 503 responses.
See this screenshots:
![Productcatalog_service_crash_pod_details](https://github.com/open-telemetry/opentelemetry-demo/assets/153714291/0eab6e8a-d0b5-412f-a3dc-a7fc46973f8b)
![Productcatalog_service_pod_memory_and_traffic_leak](https://github.com/open-telemetry/opentelemetry-demo/assets/153714291/83d61f24-8e17-4692-8159-02aba3ee683b)

**Comment by puckpuck** [comment]
This is a known issue with 1.6. It is resolved in the main branch and should be fixed with the next release.

**Comment by puckpuck** [comment]
This issue should be resolved with the 1.7.x release. If you are still having problems please open a new issue
