### ISSUE TITLE
Shippingservice crashes after d1cd7a7

### ISSUE THREAD

**Issue by styblope** [open-telemetry/opentelemetry-demo#1240]
# Bug Report

Shippingservice container crashes after d1cd7a7 with a log message:

```/app/shippingservice: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /app/shippingservice)```

The cause is rust:1.73 image ([link](https://github.com/open-telemetry/opentelemetry-demo/blob/d1cd7a7a2345b470fca984f1b5b0df254390c4f9/src/shippingservice/Dockerfile#L5)), because rolling back to previous version 1.69  does not crash.

Tested on Docker, Linux, x86.

**Comment by julianocosta89** [comment]
Reproducible, I'm also getting the error.

Thx for reporting @styblope
