### ISSUE TITLE
Adding Tracetest to the PR tests would be great for approvers and maintainers

### ISSUE THREAD

**Issue by adnanrahic** [open-telemetry/opentelemetry-demo#1242]
# Feature Request

We noticed an issue with the current test harness. It's only testing container build.
So whenever there's a PR, we ensure the container is building, **BUT** that doesn't mean containers are running.
Adding Tracetest to the PR tests would be great for approvers and maintainers.
I think we can implement this in GitHub actions.

**Is your feature request related to a problem?**

Yes. We're only testing if containers are built in PRs.

**Describe the solution you'd like:**

I'd like to test if the containers are running as expected and perform functional tests in PRs.

**Describe alternatives you've considered.**

I can't think of alternatives.

## Additional Context

Discussions in CNCF Slack:

- https://cloud-native.slack.com/archives/C03B4CWV4DA/p1699539292783259?thread_ts=1699277880.228259&cid=C03B4CWV4DA

**Comment by austinlparker** [comment]
We can't run these as part of PR checks, but we're running them post-merge now.
