### ISSUE TITLE
loadgenerator build failed 

### ISSUE THREAD

**Issue by Frapschen** [open-telemetry/opentelemetry-demo#126]
# Question
I want build the loadgenerator service ,run :
```
docker build -t otel-demo-loadgenerator:1.0.0 -f ./src/loadgenerator/Dockerfile .
```
I got an error:
```
#9 55.03 Failed to build psutil
#9 55.03 ERROR: Could not build wheels for psutil, which is required to install pyproject.toml-based projects
#9 55.03 WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
#9 55.03 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
------
executor failed running [/bin/sh -c pip install --prefix="/usr/local/" -r ./requirements.txt]: exit code: 1

```
dev env:
```
os: macos 12.3.1
cpu: M1
IED:golang
```

is there someone encounter the same err or help me out ?

**Comment by wph95** [comment]
```
MacOS: 12.3.1
CPU: Intel Core i7
```
not reproduce

Because I don't have an m1 mac, I can't help you troubleshoot. I personally think
This is not the problem of this repo. Because the base image used is the official `python:3.10-slim`.
and I recommended 
 - Update your docker for mac
 - Manually pull docker image "docker pull python:3.10-slim" to make sure the local image is up to date.
 - Retry again

**Comment by parker-edwards** [comment]
@Frapschen if it's helpful I ran into this error as well and was able to resolve it by replacing `python:3.10-slim` with `python:3.10` in `/opentelemetry-demo-webstore/src/loadgenerator/Dockerfile`

**Comment by Frapschen** [comment]
> ```
> MacOS: 12.3.1
> CPU: Intel Core i7
> ```
> 
> not reproduce
> 
> Because I don't have an m1 mac, I can't help you troubleshoot. I personally think This is not the problem of this repo. Because the base image used is the official `python:3.10-slim`. and I recommended
> 
> * Update your docker for mac
> * Manually pull docker image "docker pull python:3.10-slim" to make sure the local image is up to date.
> * Retry again

think for your advice :)

**Comment by Frapschen** [comment]
> @Frapschen if it's helpful I ran into this error as well and was able to resolve it by replacing `python:3.10-slim` with `python:3.10` in `/opentelemetry-demo-webstore/src/loadgenerator/Dockerfile`

think for your advice :) this method work for me.
