### ISSUE TITLE
loadgenerator with playwright, not generating traces for frontend-web

### ISSUE THREAD

**Issue by puckpuck** [open-telemetry/opentelemetry-demo#1297]
# Bug Report

This PR #1266 added the playwright engine and websitebrowser to the loadgenerator so we can see traces going through the frontend-web service. Though it is working with generating traffic, we do not see any spans for `frontend-web`. Since the playwright engine imposes a 10x memory requirement on the loadgenerator, we should ensure this is working as intended before release.

It seems that the playwright engine has issues with the OpenTelemetry SDK and is not correctly exporting span data. See this [comment](https://github.com/open-telemetry/opentelemetry-demo/pull/1266#issuecomment-1853940273) for more details.

**Comment by danielgblanco** [comment]
Although I can see this was fixed by reverting the previous PR. Just linking this comment back here for reference:

https://github.com/open-telemetry/opentelemetry-demo/pull/1266#issuecomment-1859939407
