### ISSUE TITLE
[loadgenerator] - have traffic go through frontend-web

### ISSUE THREAD

**Issue by puckpuck** [open-telemetry/opentelemetry-demo#1303]
It would be desirable to have the load generator create traffic that shows the frontend-web service trace through to the backend.

There was an attempt to do this using Playwright, but that was pulled because the spans for frontend-web were not getting sent to the collector. [This comment](https://github.com/open-telemetry/opentelemetry-demo/pull/1266#issuecomment-1859939407) and the 3 subsequent ones point to potential issues with why it failed in the past and workarounds that can be implemented to alleviate this.

cc: @jordibisbal8 and @danielgblanco

**Comment by jordibisbal8** [comment]
Hi @puckpuck, we have added a [PR](https://github.com/open-telemetry/opentelemetry-demo/pull/1345) that now correctly exports the traces for the frontend-web service. The approach used was to use the baggage header with synthetic_request=true from the load generator. Then, the frontend uses a different OTC endpoint for the synthetic requests `OTEL_COLLECTOR_NAME`
