### ISSUE TITLE
Restart script does more than restart

### ISSUE THREAD

**Issue by flands** [open-telemetry/opentelemetry-demo#1315]
# Bug Report

1.7

## Symptom

Run `./restart-service.sh frontend` or `make restart service=frontend`

**What is the expected behavior?**

The service is restarted and nothing more - the operation is quick

**What is the actual behavior?**

The service is rebuilt and redeployed - the operation takes a long time

## Reproduce

See above

## Additional Context

It seems like the restart operation should only perform a restart action. A better name for the current behavior would be redeploy. Having both restart and redeploy operations is likely helpful. Changing this would be a breaking change, but perhaps that is OK.

As an aside, why does restart use a script while everything else is either defined in the Makefile or left to the user to figure out? Seems like everything in the script could/should be in the Makefile. I can file a separate issue for this if people agree.

**Comment by puckpuck** [comment]
The comment in the Makefile for this target is clear that the service will be rebuilt and restarted.

I believe the reason why this was done as a separate script is that that's how it existed before, similar to other "dev tooling" with the demo like the `generate-protofuf` target. I brought it up at a SIG meeting that I depended on this script to quickly test changes, and the idea came that we should include it as a Make target or part of the demo repo itself as just a script.

**Comment by austinlparker** [comment]
Could we clarify what the enhancement is here? Making the restart script a make target called 'redeploy'?

**Comment by puckpuck** [comment]
It's on my long list of todos...

rename the current target to `redeploy` and create a new target called `restart` which only does a restart.
