### ISSUE TITLE
some images missing for version 1.7.1

### ISSUE THREAD

**Issue by dmitchsplunk** [open-telemetry/opentelemetry-demo#1327]
# Bug Report

Which version of the demo you are using?  

1.7.1 

## Symptom

The demo application fails to run via the following command: 

`docker compose up --no-build `

**What is the expected behavior?**

The application runs successfully. 

**What is the actual behavior?**

It fails with the error: 

`Error response from daemon: manifest unknown`

I believe this is happening because some images are missing for version 1.7.1.  For example: 

`$ docker pull ghcr.io/open-telemetry/demo:1.7.1-loadgenerator`
`Error response from daemon: manifest unknown`

recommendationservice is also missing

## Reproduce

`git clone https://github.com/open-telemetry/opentelemetry-demo.git`
`docker compose up --no-build`

## Additional Context

As a workaround, I was able to get it working again by updating the .env file to revert the image version back to 1.7.0.

**Comment by puckpuck** [comment]
This has been fixed with the 1.7.2 release
#1331
