### ISSUE TITLE
No class source at src/adservice (demo)

### ISSUE THREAD

**Issue by yzeballos** [open-telemetry/opentelemetry-demo#1351]
## Symptom

These class cannot be imported because they doesn´t exist in project::
import oteldemo.Demo.Ad;
import oteldemo.Demo.AdRequest;
import oteldemo.Demo.AdResponse;
import oteldemo.Demo.GetFlagResponse;
import oteldemo.FeatureFlagServiceGrpc.FeatureFlagServiceBlockingStub;

maybe they get lost in some commit.

**Comment by julianocosta89** [comment]
Hello @yzeballos those classes are generated from the [demo.proto file](https://github.com/open-telemetry/opentelemetry-demo/blob/main/pb/demo.proto).

If you would like to develop locally, you can use this guide: https://opentelemetry.io/docs/demo/development/

Please let us know if something goes wrong.

I'm closing this issue, but feel free to re-open it if something comes up.

**Comment by yzeballos** [comment]
thanks @julianocosta89,
sorry for report that.

**Comment by julianocosta89** [comment]
No worries at all.

We are happy that you did it!

Please let us know if you have any trouble with the project.
