### ISSUE TITLE
featureflagservice does not initialize database

### ISSUE THREAD

**Issue by fvlankvelt** [open-telemetry/opentelemetry-demo#1364]
# Bug Report

Which version of the demo you are using? (please provide either a specific
[commit
hash](https://github.com/open-telemetry/opentelemetry-demo/commits/main)
or a specific
[release](https://github.com/open-telemetry/opentelemetry-demo/releases)).

hash: 022ba9090add200d768af7d7696a92ed6e71474f

## Symptom

When using the featureflag service docker container, it no longer creates the featureflags table in postgres upon startup.
As a result, the container is e.g. not usable in the Kubernetes helm chart.

**What is the expected behavior?**

I expect the service to take care of its data when given access to a database.

**What is the actual behavior?**

The service logs loads of errors when querying the database.

## Reproduce

Build the docker container and use it with the helm chart.

**Comment by klucsik** [comment]
The [initDB sql files](https://github.com/open-telemetry/opentelemetry-demo/blob/main/src/ffspostgres/init-scripts/20-ffs_data.sql) should be included as volumes coming from configmap in this deployment: 
https://github.com/open-telemetry/opentelemetry-demo/blob/23094bf6901bc896889dab09ba8a781f9aff41b2/kubernetes/opentelemetry-demo.yaml#L9634

**Comment by klucsik** [comment]
#1338 Seems to be the solution

**Comment by fvlankvelt** [comment]
okay, so the helm chart should also use that postgres image.  That'll work indeed.
