### ISSUE TITLE
featureflagservice OOM Killed

### ISSUE THREAD

**Issue by alexeadem** [open-telemetry/opentelemetry-demo#1371]
# Bug Report

Which version of the demo you are using? (please provide either a specific

k8s version 1.27.3

```
helm list
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
my-otel-demo    default         1               2024-02-07 18:41:46.025374898 +0000 UTC deployed        opentelemetry-demo-0.28.1       1.7.0 
```
## Symptom

featureflagservice OOM Killed by k8s with helm chart limit of 175mi. It only works when you assign over 2Gi !!!

What do you expect to see?

It runs without hitting the OOM limit with default config.

What did you see instead?

OOM Killed message

## Reproduce

Provide the minimum required steps to result in the issue you're observing.

Following helm chart instructions here: 
https://opentelemetry.io/docs/demo/kubernetes-deployment/
```
helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
helm install my-otel-demo open-telemetry/opentelemetry-demo
```

and lb config

```
components:
  frontendProxy:
    service:
      type: LoadBalancer
```

if you increase the pod mem to 2Gi pod runs but fails when you try to access the UI with this error:

```
kubectl logs my-otel-demo-featureflagservice-594fc5d94-7xl48 
Defaulted container "featureflagservice" out of: featureflagservice, wait-for-ffspostgres (init)
21:22:14.500 [info] Migrations already up
21:22:17.229 [info] Running FeatureflagserviceWeb.Endpoint with cowboy 2.10.0 at 0.0.0.0:8081 (http)
21:22:17.238 [info] Access FeatureflagserviceWeb.Endpoint at https://localhost
21:22:21.313 [info] crash: class=:error exception=%Postgrex.Error{
  message: nil,
  postgres: %{
    code: :undefined_table,
    file: "parse_relation.c",
    line: "1449",
    message: "relation \"featureflags\" does not exist",
    pg_code: "42P01",
    position: "55",
    routine: "parserOpenTable",
    severity: "ERROR",
    unknown: "ERROR"
  },
  connection_id: 508,
  query: "SELECT f0.\"name\", f0.\"description\", f0.\"enabled\" FROM \"featureflags\" AS f0 WHERE (f0.\"name\" = $1)"
} stacktrace=[
  {Ecto.Adapters.SQL, :raise_sql_call_error, 1,
   [file: 'lib/ecto/adapters/sql.ex', line: 913]},
  {Ecto.Adapters.SQL, :execute, 6,
   [file: 'lib/ecto/adapters/sql.ex', line: 828]},
  {Ecto.Repo.Queryable, :execute, 4,
   [file: 'lib/ecto/repo/queryable.ex', line: 229]},
  {Ecto.Repo.Queryable, :all, 3, [file: 'lib/ecto/repo/queryable.ex', line: 19]},
  {Ecto.Repo.Queryable, :one, 3,
   [file: 'lib/ecto/repo/queryable.ex', line: 151]},
  {:ffs_service, :get_flag, 2, [file: 'src/ffs_service.erl', line: 32]},
  {:otel_tracer_default, :with_span, 5,
   [file: '/app/deps/opentelemetry/src/otel_tracer_default.erl', line: 47]},
  {:grpcbox_stream, :handle_unary, 3,
   [file: '/app/deps/grpcbox/src/grpcbox_stream.erl', line: 283]}
]
```
All other components are working fine.

**Comment by AlexPSplunk** [comment]
My version runs without increasing memory to 2G, but I still get the same crash with "undefined table".

**Comment by puckpuck** [comment]
Now that 1.8.0 is released on all platforms, can you retest this? It should be fixed now.

**Comment by alexeadem** [comment]
Working now @puckpuck in [QBO Kubernetes engine (QKE) CE and Cloud)([https://www.qbo.io/) 

Tested in K8s kindest/node:v1.27.3  with version 1.8.0 from helm chart. 

Thanks for the fix.  

Default memory  assigned to component is pretty low and more suitable for a local deployment. 

featureflagService service uses a lot of memory with high memory and CPU k8s nodes. See below my config.

```
opentelemetry-collector:
  resources:
    limits:
      memory: 512Mi
components:
  frontendProxy:
    service:
      type: LoadBalancer
    resources:
      limits:
        memory: 265Mi
  featureflagService:
    resources:
      limits:
        memory: 2048Mi
```

**Comment by AlexPSplunk** [comment]
After digging further, I don't think this was a bug at all.  I think it was a problem of deploying with outdated chart versions. It looks like starting in v1.7.2 the init scripts for the ffpostgres were moved into the postgres image. If you ran with an older Helm chart, everything builds and starts, but the ffpostgress does not have the init scripts in the image so ffservice fails.  After running "helm repo update" everything works.
