### ISSUE TITLE
The item quantity remains the same when switching between products instead of reset to 1

### ISSUE THREAD

**Issue by MonaMaNotAvailable** [open-telemetry/opentelemetry-demo#1403]
# Bug Report

Which version of the demo you are using?
[v1.7.2](https://github.com/open-telemetry/opentelemetry-demo/releases/tag/1.7.2).

## Symptom

What do you expect to see?
The quantity should be reset to 1 when switching to a new product page.

What did you see instead?
The quantity remains the same when switching between products.

## Reproduce

1. make start
2. open any specific product page
3. select quantity to be any number except 1
4. switch to another product
5. the quantity does not reset to 1

## Additional Context
I believe this is related to some saved state on the frontend that there should be a reset somewhere in the typescript (maybe index.tsx line 27 const [quantity, setQuantity] = useState(1);).

Thank you!

**Comment by aming27** [comment]
I've tried to reproduce the bug but in my case it works fine.
