### ISSUE TITLE
CartService - Should console logging be enabled?

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-demo#1413]
# Bug Report

Which version of the demo you are using? main

## Symptom

[CartService](https://github.com/open-telemetry/opentelemetry-demo/blob/main/src/cartservice/src/Program.cs#L31) has enabled OTel Logging, but it is also routing logs to stdout/console - is that intended? The component that routes logs to console is not the OpenTelemetry console exporter either.

**What is the expected behavior?**

No usage of Console (LoggerProvider).

**What is the actual behavior?**

## Additional Context

.NET's built-in templates enable the ConsoleLoggerProvider (not the OTel Console Exporter).

**Comment by puckpuck** [comment]
We need to holistically clean up all logs for all services.

We started to send all things to console with little consistency. Now that the logs telemetry type is getting support in all SDKs we have been adding log outputs there or converting some of the console outputs, but went even further away from consistency.

We need to clean this up for not just the CartService, but review and implement proper Otel logging for all services. Perhaps this deserves an issue of its own with a set of tasks for each service.

**Comment by puckpuck** [comment]
I'm closing this issue. This is behaving similarly to how other languages are working with Otel logging. We are seeing the logs emitted to both the console and the OTLP pipeline.

**Comment by cijothomas** [comment]
> other languages are working with Otel logging

CartService's console logging is *not* OTel logging!

**Comment by puckpuck** [comment]
The OpenTelemetry exporter is added to the cartservice logger here https://github.com/open-telemetry/opentelemetry-demo/blob/f4eee80b9893d9334afd97b98a6dbee89acca657/src/cartservice/src/Program.cs#L33

This is a similar implementation to how Java hooks into the popular log4j framework in that world.

**Comment by cijothomas** [comment]
> The OpenTelemetry exporter is added to the cartservice logger here
> 
> https://github.com/open-telemetry/opentelemetry-demo/blob/f4eee80b9893d9334afd97b98a6dbee89acca657/src/cartservice/src/Program.cs#L33
> 
> This is a similar implementation to how Java hooks into the popular log4j framework in that world.

Maybe some confusion is there.. Let me clarify:
There is no OpenTelemetry console exporter added in cartservice. Only OTLP Exporter is added.
*But*, there is a consoleexporter, *outside* of OpenTelemetry is added. https://github.com/open-telemetry/opentelemetry-demo/blob/f4eee80b9893d9334afd97b98a6dbee89acca657/src/cartservice/src/Program.cs#L34 This line is adding the non-OpenTelemetry console exporter. (its actual name is  ConsoleProvider in .NET ILogger world)
