### ISSUE TITLE
Add Session ID to Baggage

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry-demo#1435]
The frontend service currently sets a Session ID on frontend spans as an attribute. It would be good for this to be propagated down thru baggage in order to use it for feature flag targeting.

**Comment by Navya-Verma11** [comment]
I would like to work on this. Please assign this issue to me if possible. I am an Outreachy 24 Applicant.

**Comment by puckpuck** [comment]
We may want to rename this attribute while doing this effort as well. If I'm not mistaken, the spec for this will be that the attribute be called `session.id` (no app. prefix).

In the not-too-distant future, the Otel Web SDK will automatically generate this attribute for us, so good to align with what that name will be right now.

**Comment by Navya-Verma11** [comment]
> We may want to rename this attribute while doing this effort as well

SO do you want to rename them to `session.id` instead of current `app.session.id` ?

**Comment by puckpuck** [comment]
> > We may want to rename this attribute while doing this effort as well
> 
> 
> 
> So do you want to rename them to `session.id` instead of current `app.session.id` ? 

Yes
