### ISSUE TITLE
Cannot view the document of `github.com/opentelemetry/opentelemetry-demo/src/productcatalogservice/genproto/oteldemo`

### ISSUE THREAD

**Issue by Wattyyy** [open-telemetry/opentelemetry-demo#1438]
# Bug Report

Which version of the demo you are using? 
- [0c80094e7ce9accb4bb782dae0e935db5350af7f](https://github.com/open-telemetry/opentelemetry-demo/tree/0c80094e7ce9accb4bb782dae0e935db5350af7f)

## Symptom
We cannot view the document of [github.com/opentelemetry/opentelemetry-demo/src/productcatalogservice/genproto/oteldemo](https://pkg.go.dev/github.com/opentelemetry/opentelemetry-demo/src/productcatalogservice/genproto/oteldemo) used at [L39 of src/productcatalogservice/main.go](https://github.com/open-telemetry/opentelemetry-demo/blob/main/src/productcatalogservice/main.go#L39).
If this is intended behavior, feel free to close this issue.

**What is the expected behavior?**
- Can open the document

**What do you expect to see?**
- Documentation for the package

**What is the actual behavior?**
- 404 error page shown

**What did you see instead?**
- 404 error page

## Reproduce
Open the following URL link of `github.com/opentelemetry/opentelemetry-demo/src/productcatalogservice/genproto/oteldemo`
https://pkg.go.dev/github.com/opentelemetry/opentelemetry-demo/src/productcatalogservice/genproto/oteldemo

We will close this issue if:

* The steps you provided are complex.
* If we can not reproduce the behavior you're reporting.

## Additional Context
The organization name in package's URL is `opentelemetry`, not `open-telemetry`

**Comment by puckpuck** [comment]
That file is generated. You can create it using `make generate-protobuf`

**Comment by Wattyyy** [comment]
@puckpuck 
After installing the needed libraries specified in the [gRPC document](https://grpc.io/docs/languages/go/quickstart/#prerequisites) and executing `make generate-protobuf`, I could finally view the file's document in IDE.
Thanks for your kind response!
