### ISSUE TITLE
 http://localhost:8080/feature/ Page NOT FOUND

### ISSUE THREAD

**Issue by av-nextleap** [open-telemetry/opentelemetry-demo#1459]
# Bug Report

Which version of the demo you are using? (please provide either a specific
git clone https://github.com/open-telemetry/opentelemetry-demo.git

## Symptom

When this URL is executed --http://localhost:8080/feature/ .. Getting PAGE NOT FOUND.. Rest all the URLs are working

OpenTelemetry Demo is running.
Go to http://localhost:8080 for the demo UI.
Go to http://localhost:8080/jaeger/ui for the Jaeger UI.
Go to http://localhost:8080/grafana/ for the Grafana UI.
Go to http://localhost:8080/loadgen/ for the Load Generator UI.
Go to http://localhost:8080/feature/ for the Feature Flag UI.

**What is the expected behavior?**

The feature flag PAGE

**What is the actual behavior?**

PAGE NOT FOUND

## Reproduce

1. git clone https://github.com/open-telemetry/opentelemetry-demo.git
2. make start
3.  try to hit the URL after the installation is done

We will close this issue if:

* The steps you provided are complex.
* If we can not reproduce the behavior you're reporting.

**Comment by julianocosta89** [comment]
Hello @av-nextleap,

The `feature` endpoint was removed from the demo on this PR: #1388

Seems that we've missed 2 lines where the endpoint was mentioned.
I've opened the PR #1461 to remove the reference to the endpoint.

**Comment by av-nextleap** [comment]
if that is removed then from where we can access the functionality

**Comment by julianocosta89** [comment]
@av-nextleap that's now explained here: https://opentelemetry.io/docs/demo/feature-flags/
