### ISSUE TITLE
Integrate Pixie for eBPF Telemetry

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry-demo#148]
Pixie (an eBPF telemetry tool for Kubernetes) has recently updated to support OTLP output (see [here](https://docs.px.dev/tutorials/integrations/otel/) for a tutorial). We should evaluate this as a potential integration for the Kubernetes-deployed version of the demo.

**Comment by philkuz** [comment]
Hi I'm Phillip, one of the Pixie maintainers. We would love to prototype this out if the community is interested!

**Comment by austinlparker** [comment]
Closing as this isn't on the roadmap (doesn't mean we won't do it, but we'll create an issue when it's time)
