### ISSUE TITLE
Add Mikko as a maintainer

### ISSUE THREAD

**Issue by julianocosta89** [open-telemetry/opentelemetry-demo#1487]
I'd like to move @mviitane from approver to maintainer.

Mikko has been involved in the OTel Demo since the beginning of it, has been [actively contributing](https://github.com/open-telemetry/opentelemetry-demo/pulls?q=author%3Amviitane) to the project and an [active approver](https://github.com/open-telemetry/opentelemetry-demo/pulls?q=reviewed-by%3Amviitane).

He would replace @cartersocha and we'd move Carter to emeritus maintainer status.

**Comment by austinlparker** [comment]
👍 sgtm

**Comment by puckpuck** [comment]
I agree to doing this
