### ISSUE TITLE
Determine release verification process

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry-demo#149]
In order to ensure that we're not breaking telemetry or causing regressions, it would be good to figure out some sort of telemetry verification test suite. Potentially, this could be automated with the use of something like [TraceTest](https://tracetest.kubeshop.io). 

We should first determine what the appropriate level of verification is, and go from there -- I don't necessarily think it'd help to build up some complex automation that would take a lot of time to keep up-to-date, for example.

**Comment by ahayworth** [comment]
An initial integration spec could look something like this, perhaps -

For each request that the load generator can perform:
- We should be able to locate one complete, unbroken trace.
- That trace should contain at least one span from every service we expect to be participating in that request.

Making additional assertions about ordering or what attributes are present might end up being brittle, but those two assertions would probably not change often (if ever).

**Comment by austinlparker** [comment]
Closing as this is not currently needed.
