### ISSUE TITLE
Running into issue in Lima VM, MacOS(M1) , frontend Pod is restarting all the time. 

### ISSUE THREAD

**Issue by developer1622** [open-telemetry/opentelemetry-demo#1491]
# Bug Report

Which version of the demo you are using? (please provide either a specific
[commit
hash](https://github.com/open-telemetry/opentelemetry-demo/commits/main)
or a specific
[release](https://github.com/open-telemetry/opentelemetry-demo/releases)).

I have followed this to install demo App:

```
kubectl apply --namespace otel-demo -f https://raw.githubusercontent.com/open-telemetry/opentelemetry-demo/main/kubernetes/opentelemetry-demo.yaml

```

## Symptom

**What is the expected behavior?**
I expected that URL Web **store: http://localhost:8080/** would work fine and I can do some operations on the page, 
but it did not

What do you expect to see?
Web store page and content

**What is the actual behavior?**
Web store page and content 

What did you see instead?

``upstream connect error or disconnect/reset before headers. reset reason: connection termination``

**After sometime refresh**

`` upstream connect error or disconnect/reset before headers. reset reason: remote connection failure, transport failure reason: delayed connect error: 111 ``

```
Logs of Pod: frontend  [opentelemetry-demo-frontend-76f486559f-mlbtp]

│ > frontend@0.1.0 start                                                                                                                                                                     │
│ > node --require ./Instrumentation.js server.js                                                                                                                                            │
│                                                                                                                                                                                            │
│ npm notice                                                                                                                                                                                 │
│ npm notice New minor version of npm available! 10.2.4 -> 10.5.0                                                                                                                            │
│ npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.5.0>                                                                                                                    │
│ npm notice Run `npm install -g npm@10.5.0` to update!                                                                                                                                      │
│ npm notice                                                                                                                                                                                 │
│ npm ERR! path /app                                                                                                                                                                         │
│ npm ERR! command failed                                                                                                                                                                    │
│ npm ERR! signal SIGILL                                                                                                                                                                     │
│ npm ERR! command sh -c node --require ./Instrumentation.js server.js                                                                                                                       │
│                                                                                                                                                                                            │
│ npm ERR! A complete log of this run can be found in: /home/nextjs/.npm/_logs/2024-04-01T18_43_39_297Z-debug-0.log                                                                          │


```

## Reproduce

Provide the minimum required steps to result in the issue you're observing.

Install LimaVM in MacOS:
https://github.com/lima-vm/lima/blob/master/examples/k3s.yaml

And install the Otel demo using the Kubectl command(above-mentioned)

Do the said port-forward as per the document: https://opentelemetry.io/docs/demo/kubernetes-deployment/

All the pods are up and running except the Pod named ``frontend, ``which restarts continuously and another Pod named ``opensearch``.  

We will close this issue if:

* The steps you provided are complex.
* If we can not reproduce the behavior you're reporting.

## Additional Context

MacOS, M1 Chip.
Installed K3s in Lima VM and trying to access in Host MacOS system.  Thanks

**Comment by julianocosta89** [comment]
@developer1622 it seems that nobody discussed that with you here.
Did you manage to get it working?

Is the issue still happening in the latest release of the demo?

**Comment by developer1622** [comment]
Hi @julianocosta89 
I stopped the above work and did not check in the latest. We can close this, Thank you.
