### ISSUE TITLE
network opentelemetry-demo was found but has incorrect label com.docker.compose.network set to "opentelemetry-demo"

### ISSUE THREAD

**Issue by tekbuds** [open-telemetry/opentelemetry-demo#1496]
# Bug Report

Which version of the demo you are using? (please provide either a specific

commit 59cdb0ab0bde1eaa6396c3511df0f2539f5b7fa3 (HEAD -> main, origin/main, origin/HEAD)

## Symptom

On running 
docker compose up --force-recreate --remove-orphans --detach

I see the below error:

WARN[0000] /root/sachin/opentelemetry-demo/docker-compose.yml: `version` is obsolete
network opentelemetry-demo was found but has incorrect label com.docker.compose.network set to "opentelemetry-demo"

I am running on SLES SP4
-------------------------------------------------
docker compose version
Docker Compose version v2.26.1
------------------------------------------------
docker version
Client:
 Version:           24.0.7-ce
 API version:       1.43
 Go version:        go1.20.12
 Git commit:        311b9ff0aa93
 Built:             Fri Oct 27 12:00:00 2023
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          24.0.7-ce
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.12
  Git commit:       311b9ff0aa93
  Built:            Fri Oct 27 12:00:00 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.10
  GitCommit:        4e1fe7492b9df85914c389d1f15a3ceedbb280ac
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0f32bc
 docker-init:
  Version:          0.1.7_catatonit
  GitCommit:

**Comment by puckpuck** [comment]
This seems related to the `version` property now being optional in docker. I also see plenty of issues like this [one](https://github.com/mailcow/mailcow-dockerized/issues/5797), which are inter linked with several other repos and resolved around the same idea. It probably makes sense we remove the `version` property.

**Comment by puckpuck** [comment]
For the network issue. If you had the demo running before and upgraded docker, you may need to run a `docker system prune`. This issue and [comment](https://github.com/docker/compose/issues/10797#issuecomment-1708751803) explains what to do.
