### ISSUE TITLE
[bug] product images not found at order completion page

### ISSUE THREAD

**Issue by julianocosta89** [open-telemetry/opentelemetry-demo#1525]
# Bug Report

Which version of the demo you are using?
742594fc2339653d4b38aa67ddf9a017561c919a

## Symptom

After #1462 got merged, when running the demo, the images are not loaded on the order completion page:

![image](https://github.com/open-telemetry/opentelemetry-demo/assets/15364991/958c13a0-d024-4ad0-9e45-87da7c4e4514)

**What is the expected behavior?**

All product images should be properly loaded.

## Reproduce

Clone `main`, run the demo, navigate to the web ui and buy a product.

**Comment by klucsik** [comment]
[This commit](https://github.com/klucsik/opentelemetry-demo/tree/fix-missing-image-in-cart) Fixes the issue by passing down the optimization request to the imageprovider service. The imageprovider doesnt have anything similar implemented, so the resulting images are distorted.
![image](https://github.com/open-telemetry/opentelemetry-demo/assets/10886524/a441a688-7827-4c79-be8c-a281714c42c0)

This can be done with https://nginx.org/en/docs/http/ngx_http_image_filter_module.html nginx module, which would need a more complex imageprovider setup (as we need to install both this and otel module to nginx is beyond the easy apt-get install capabilities).
Maybe we should put this loader globally, as it is a bit odd in this specific component, but as I see, no other image is resized by react, even in responsive view
