### ISSUE TITLE
Flagd CrashLoopBackOff

### ISSUE THREAD

**Issue by samuellvicente** [open-telemetry/opentelemetry-demo#1536]
# Bug Report

Which version of the demo you are using?
Version 1.9.0, deployed on a kind cluster

## Symptom
Flagd deployment in CrashLoopBackOff

**What is the expected behavior?**
Flagd does not crash

**What is the actual behavior?**

Flagd in CrashLoopBackOff

## Reproduce

Deploy the demo helm chart with Elastic values as per https://github.com/elastic/opentelemetry-demo

## Additional Context

I suspect it is a issue of the memory limit being set to 20Mi, I bumped it to 100Mi and the issue was mitigated.

**Comment by puckpuck** [comment]
Can you do a `kubectl describe pod <flagd-pod>` and paste the output here?

**Comment by MadVikingGod** [comment]
I was running into the same problem.  It looks like it's getting OOM killed because of the 20M limit.  I upped it to 400M just to be safe and it starts fine.
