### ISSUE TITLE
Running the demo fails with an authorisation error when pulling the "flagd" image

### ISSUE THREAD

**Issue by exhuma** [open-telemetry/opentelemetry-demo#1582]
# Bug Report

Which version of the demo you are using?

I am using a82287db6d

## Symptom

**What is the expected behavior?**

Running `docker compose up` should run the demo

**What is the actual behavior?**

The command fails with:

```
Error response from daemon: Head "https://ghcr.io/v2/open-feature/flagd/manifests/v0.10.1": denied: denied
```

## Reproduce

```
git clone https://github.com/open-telemetry/opentelemetry-demo.git
cd opentelemetry-demo
git checkout a82287db6d
docker compose up -d
```

## Additional Context

Accessing the URL from the error message returns an "Unauthorized" error:

```
› curl -i https://ghcr.io/v2/open-feature/flagd/manifests/v0.10.1
HTTP/2 401
content-type: application/json
www-authenticate: Bearer realm="https://ghcr.io/token",service="ghcr.io",scope="repository:open-feature/flagd:pull"
date: Sat, 25 May 2024 07:01:53 GMT
content-length: 73
x-github-request-id: F8E6:3986F4:73840B:767DC3:66518CE1

{"errors":[{"code":"UNAUTHORIZED","message":"authentication required"}]}
```

**Comment by MohadKamil** [comment]
I faced the same issue, and it turns out you need to authenticate to GitHub to be able to pull public images

```shell
docker login ghcr.io -u {YOUR_GH_USER} -p {YOUR_ACCESS_TOKEN}
```

you can generate an access token from the Personal access tokens setting, under developer settings
