### ISSUE TITLE
"Minimal" version of the docker-compose file fails with a missing dependency on "flagd"

### ISSUE THREAD

**Issue by exhuma** [open-telemetry/opentelemetry-demo#1583]
# Bug Report

Which version of the demo you are using?

I am using a82287db6d

## Symptom

**What is the expected behavior?**

Running `docker compose -f docker-compose.minimal.yml up -d` should run the demo

**What is the actual behavior?**

The command fails with:

```
service "loadgenerator" depends on undefined service flagd: invalid compose project
```

## Reproduce

```
git clone https://github.com/open-telemetry/opentelemetry-demo.git
cd opentelemetry-demo
git checkout a82287db6d
docker compose -f docker-compose.minimal.yml up -d
```

## Additional Context

I tried to run this after I ran into #1582

**Comment by rogercoll** [comment]
Thanks for reporting this @exhuma ! The `flagd` service is missing to the minimal docker compose. In addition, the frondend proxy environment variables need to be updated. 


This PR should fix it https://github.com/open-telemetry/opentelemetry-demo/pull/1585
