### ISSUE TITLE
Spanmetrics panel always returns no results

### ISSUE THREAD

**Issue by flands** [open-telemetry/opentelemetry-demo#1623]
# Bug Report

Which version of the demo you are using? 1.10.0

## Symptom

Spanmetrics panel always returns no results

**What is the expected behavior?**

Spanmetrics panel returns results - this was the case, at least, in version 1.7.0

**What is the actual behavior?**

Spanmetrics panel always returns no results

## Reproduce

Download version 1.10.0 and run `make start`. Once started, open Grafana (`http://localhost:8080/grafana`) and navigate to Dashboards > Demo > Demo Dashboard. Look at the panels under Spanmetrics. Switch to any other service and the same behavior is experienced. If you scroll down, you will see most of the other panel work (some do not have logs today so those also return no results but for a different reason).

## Additional Context

This appears to be a regression. A workaround is to manually edit each widget and for the query letter (A, B, C, etc) option settings, manually setting the Min step to something like `30s`.

**Comment by puckpuck** [comment]
Spanmetrics data takes several minutes to show up. The data is aggregated on minute intervals, and because the charts are all rate charts you also need multiple data points before anything can render for them. 

How long did you wait after starting the demo before visiting the dashboard?

**Comment by flands** [comment]
More than an hour and I tried every service - see attachments.

<img width="1434" alt="Screenshot 2024-06-30 at 10 04 50 AM" src="https://github.com/open-telemetry/opentelemetry-demo/assets/645366/ebbd1035-8fd0-4a6b-9933-9dfbbacdc833">
<img width="1439" alt="Screenshot 2024-06-30 at 10 04 58 AM" src="https://github.com/open-telemetry/opentelemetry-demo/assets/645366/04bdd3d5-986b-4d11-9a2c-3475488b8a43">
