### ISSUE TITLE
Loadgen doesn't work through the frontendproxy

### ISSUE THREAD

**Issue by martinjt** [open-telemetry/opentelemetry-demo#1706]
# Bug Report

Which version of the demo you are using? 
1.11.1

## Symptom

**What is the expected behavior?**

The Loadgen UI for locust works when accessing from the /loadgen path from the frontendproxy.

**What is the actual behavior?**

Because the static resources don't contain the base path, it doesn't work and all the static resources 404.

## Reproduce

Could you provide the minimum required steps to resolve the issue you're seeing?

* Run the helm chart to deploy it to a k8s cluster
* Port forward 8080 from the frontendproxy service
* access http://localhost:8080/loadgen

## Additional Context

Please feel free to add any other context about the problem here.

**Comment by dides82** [comment]
Same issue here. Ended up port-forwarding service loadgenerator to access UI and it is working fine.
Issue seems to be related to Locust but did not find a way to configure it correctly (see https://github.com/locustio/locust/issues/149 for example)

**Comment by gjshao44** [comment]
have the same issue with version 1.11.1, thanks for the workaround.

**Comment by julianocosta89** [comment]
Hello all, thanks for reporting it.
I'm not sure how to properly solve this, but there is a working solution, just add `/` at the end of the `url`.
Seems funny, but believe me:

`localhost:8080/loadgen`
![Screenshot 2024-10-14 at 16 13 29](https://github.com/user-attachments/assets/5fe469b4-763b-4b1c-831c-ed22382b5050)

`localhost:8080/loadgen/`
![Screenshot 2024-10-14 at 16 13 53](https://github.com/user-attachments/assets/80a9bfa5-7842-4c02-9f18-a039dfc9045c)

We tried making it explicit in the docs and in the `make start` command, but we are open to suggestions.

@martinjt any suggestions?
Or should we close this one?
