### ISSUE TITLE
Feature Flag `productCatalogFailure` raising errors on Recommendation Service

### ISSUE THREAD

**Issue by julianocosta89** [open-telemetry/opentelemetry-demo#1710]
# Bug Report

Which version of the demo you are using?
52d315aeba7f6da80268eaf84613f6bf94e1f341

## Symptom

**What is the expected behavior?**
When enabling the feature flag `productCatalogFailure` it is expected to have an error generated for `GetProduct` requests with product ID: `OLJCESPC7Z`.

![image](https://github.com/user-attachments/assets/4dd04ec4-3483-4fc1-9a72-17ff058fcba9)

**What is the actual behavior?**
Currently the error is also being trigged in requests for recommendation service whenever the product `OLJCESPC7Z` is returned in the recommendation list.

![image](https://github.com/user-attachments/assets/2580f0f9-01d2-4648-afdf-4ddd6c82c07f)

## Reproduce

1. Run the demo
2. Enable the feature flag `productCatalogFailure`
3. Navigate to `http://localhost:8080/loadgen/`and check the tab `Failures`.

**Comment by julianocosta89** [comment]
The more I think about this the more I believe this is working as expected.
The recommendation and the checkout service get the product as well, so when they call `GetProduct` for product `OLJCESPC7Z`, the request fails.

This is a great example on how one error can impact multiple services and multiple endpoints.

Not sure if we should work this around for demo purposes.

@reese-lee I'd love to hear your opinion on this.

**Comment by julianocosta89** [comment]
@reese-lee we have discussed that in the SIG meeting and it seems that this is expected.
The frontend does call the productCatalog once it get the list of products from recommendation service.

https://github.com/open-telemetry/opentelemetry-demo/blob/main/src/frontend/pages/api/recommendations.ts#L21

**Comment by reese-lee** [comment]
@julianocosta89 I see, I'm trying to understand why recommendationservice isn't impacted by the issue. So, recommendationservice doesn't generate an error, because it's generating the list of products (including the problem product ID) that is then supplied to productcatalogservice when requested by frontend, and since the error doesn't occur until productcatalogservice attempts to give it to frontend, there's no issue for recommendationservice?

**Comment by julianocosta89** [comment]
@reese-lee I must have lost this comment, sorry about that.
I was taking a look at it again and what happens is that the `get_product_list` returns a list of all `product_ids`.
Only when `get_product` with an specific `<id>` is called the error is raised.
That's the way the error was implemented initially.
Kinda showcasing an error when getting the details of a specific product.

Does that make sense?

**Comment by puckpuck** [comment]
Closing this, as this error is being raised as expected.
