### ISSUE TITLE
Testing Observability Pipeline

### ISSUE THREAD

**Issue by francisan** [open-telemetry/opentelemetry-demo#1712]
Hi,

How I can test below pipeline using some sample payload. Want to test/ensure connector routes the request to corresponding pipeline based on the field 'name'.

receivers:
  webhookevent:

      endpoint: 0.0.0.0:1111
      path: /get/info

processors:
  transform/tr:

       error_mode: ignore
       log_statements:
        - context: log
          statements:
           - set(body, ParseJSON(body)) where body != nil
           - set(resource.attributes["name"], body["name"])
         
connectors:
  routing :
      table:
        - statement: route() where attributes["name"] == "abc"
           pipelines:
            - logs/abc
        - statement: route() where attributes["name"] == "xyz"
           pipelines:
            - logs/xyz            
     
exporters:
 logging:
   loglevel: debug

service:
  pipelines:

  logs/receivers:
    receivers: [webhookevent]
    processors: [transform/tr]
    exporters: [routing,logging]
    
  logs/abc:
    receivers: [routing]
    processors: []
    exporters: [logging]
    
  logs/xyz:
    receivers: [routing]
    processors: []
    exporters: [logging]

Want to build something as shown below. Any existing test frameworks available?
type: Test
spec:
  id: 19L__G7IR
  name: Call API
  trigger:
    type: http
    httpRequest:
      url: http://host.docker.internal:1111/get/info
      method: POST
      headers:
      - key: Content-Type
        value: application/json
  specs:
 
    assertions:
    - attr:http.status_code  =  200

**Comment by danielbdias** [comment]
hi @francisan , I noticed this issue is related to your report on https://github.com/kubeshop/tracetest/issues/3997.

I believe that is not related to the OTel Demo itself (feel free to correct me if I'm wrong @puckpuck and @julianocosta89)

Are you trying to validate a behavior on your OTel Collector right?

**Comment by francisan** [comment]
@danielbdias Yes, you are right. Will discuss this in other thread (https://github.com/kubeshop/tracetest/issues/3997).
