### ISSUE TITLE
[featureflag] `productCatalogFailure` flag raising 128 events

### ISSUE THREAD

**Issue by julianocosta89** [open-telemetry/opentelemetry-demo#1735]
# Bug Report

Which version of the demo you are using?
Main (a1cfe470c6c1e412865b351e473060b66674b2fb)

## Symptom

When enabling the feature flag `productCatalogFailure`, the spans from productCatalog service are emitting 128 events.
![image](https://github.com/user-attachments/assets/74696d4a-563b-4a05-82a9-59a8b9069f11)

**What is the expected behavior?**

The feature flag should be checked only once.

**What is the actual behavior?**

The feature flag is checked 127 times.

## Reproduce

Could you provide the minimum required steps to resolve the issue you're seeing?

- pull `main`
- run `make start`
- enable `productCatalogFailure`feature flag
- navigate to jaeger and check any span with error from the `productCatalogService`.

**Comment by julianocosta89** [comment]
@beeme1mr would you be able to take a look at this?

I've quickly checked the productCatalogService and the implementation seems about right:
https://github.com/open-telemetry/opentelemetry-demo/blob/main/src/productcatalogservice/main.go#L253-L257

I couldn't find a place where we would set 127 span events in the productCatalogService, maybe I've missed something.

LMK if you want me to move this issue to the flagd repo.

**Comment by beeme1mr** [comment]
It looks like a new OTel hook is registered globally for every request, which is very likely the root cause. Either it should be done once during initialization, or the hook should be set at the client level.

https://github.com/open-telemetry/opentelemetry-demo/blob/main/src/productcatalogservice/main.go#L303

**Comment by julianocosta89** [comment]
Thank you @beeme1mr! 🤩
