### ISSUE TITLE
Unable to view `paymentservice` activity 

### ISSUE THREAD

**Issue by justincastilla** [open-telemetry/opentelemetry-demo#1749]
# Bug Report

Which version of the demo you are using? (please provide either a specific
most recent: https://github.com/open-telemetry/opentelemetry-demo/commit/d953c8196ed17473540380d477bc5aadba7a60ab
## Symptom

I am unable to see the payment-service span information on jaeger or grafana
**What is the expected behavior?**

I expect to see the payment service spans show up within the associated traces

**What is the actual behavior?**

I can verify via the logs that the payment services are running as expected, however the traces aren't being collected.
## Reproduce

Could you provide the minimum required steps to resolve the issue you're seeing?

from the root directory of the repository:
```make start```

## Additional Context

I may not be running this correctly or missing a step, but everything works fine except the paymentservice spans

**Comment by julianocosta89** [comment]
Hello @justincastilla 👋🏽 

Where are you running the demo?
Knowing OS, architecture, memory and CPUs would help.

Also, do you have any logs from the `paymentservice`?

**Comment by david1542** [comment]
I'm also unable to see traces for the paymentservice

**Comment by julianocosta89** [comment]
@david1542 could you check the latest release?
Everything should be working fine.

If it still doesn't work, could send some logs and details about your deployment?

**Comment by justincastilla** [comment]
I was able to get everything working with the newest release :)
