### ISSUE TITLE
Add metrics monitoring for runtime environments

### ISSUE THREAD

**Issue by morningspace** [open-telemetry/opentelemetry-demo#1775]
# Feature Request

**Is your feature request related to a problem?**

The current opentelemetry-demo app does not include some metrics monitoring or not sufficient metrics monitoring for runtime environments such as node.js and golang.

**Describe the solution you'd like:**

Can we add instrumentation for the runtime metrics so that we can demonstrate the monitoring of these runtime environments?

**Describe alternatives you've considered.**

n/a

## Additional Context

We are looking at demonstrating these runtime environments monitoring recently and would be happy to contribute code to the upstream opentelemetry-demo project if that makes sense.

**Comment by julianocosta89** [comment]
Hello @morningspace 👋🏽

We would be more than happy to accept your contributions!

**Comment by morningspace** [comment]
Thanks @julianocosta89, I'm working with my colleague @liyanwei93 on preparing some PR this week. Hope to submit soon!
