### ISSUE TITLE
tracetest cli and server versions mismatch problem/warning

### ISSUE THREAD

**Issue by sophiaxu0424** [open-telemetry/opentelemetry-demo#1784]
When enabling API observability-driven testing using
docker compose -f docker-compose-tests.yml run traceBasedTests
I am having mismatch problem/warning like below:

I've using darwin/arm64 as my platform is in `tracetest/docker-compose.yaml` file and the server container is up and running for now.
not sure if this warning would affect the process to see the test result?

```
Starting tests...
Running trace-based tests for: adservice cartservice currencyservice checkoutservice frontend emailservice paymentservice productcatalogservice recommendationservice shippingservice ...

CLI: v1.7.1
Server: v1.5.2

✖️ Version Mismatch
The CLI version and the server version are not compatible. To fix this, you'll need to make sure that both your CLI and server are using compatible versions.
We recommend upgrading both of them to the latest available version. Check out our documentation https://docs.tracetest.io/configuration/upgrade for simple instructions on how to upgrade.
Thank you for using Tracetest! We apologize for any inconvenience causedCLI: v1.7.1
Server: v1.5.2
```

**Comment by puckpuck** [comment]
we recommend you run trace testing using the Make target

```
make run-tracetesting
```

I just ran this command from the main branch, and it ran successfully. Can you try running that command and confirm you are still having an issue?

**Comment by julianocosta89** [comment]
Please feel free to re-open the issue if the solution above doesn't solve your case.
