### ISSUE TITLE
accounting-service failing to start

### ISSUE THREAD

**Issue by MMartyn** [open-telemetry/opentelemetry-demo#1798]
# Bug Report

Which version of the demo you are using? ghcr.io/open-telemetry/demo:latest-accountingservice@sha256:a4c22f54468bf16fc32fc788e8f71d663b6886158847a5e555eb90381b6aae0e

## Symptom

The container is in a restart loop. The logs report:

```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'AccountingService, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
```

**What is the expected behavior?**

I would expect the container to reach a running state.

**What is the actual behavior?**

Container is in a restart loop.

## Reproduce

Run `make start`

We will close this issue if:

* The steps you provided are complex.
* If we can not reproduce the behavior you're reporting.

## Additional Context

I am attempting to run this on a Macbook Pro M2, so it would be pulling the arm64 versions.

**Comment by julianocosta89** [comment]
@puckpuck it seems that we may have an issue with the current nightly release.
Maybe changing the action to use the new buildx introduced by you should solve. WDYT?!

**Comment by julianocosta89** [comment]
@puckpuck I've done some digging and as now we have `ARG TARGETARCH` in the Dockerfiles, we need to also add this arg in here:
https://github.com/open-telemetry/opentelemetry-demo/blob/main/.github/workflows/component-build-images.yml#L198

I'll do some further investigation tomorrow to see if we can dinamically get this value, as we are passing it via `platforms`:https://github.com/open-telemetry/opentelemetry-demo/blob/main/.github/workflows/component-build-images.yml#L196

**Comment by MMartyn** [comment]
@julianocosta89 That env should automatically be getting set. https://docs.docker.com/build/building/variables/#pre-defined-build-arguments

**Comment by MMartyn** [comment]
My guess would be the second stage needs to be something like this:
```
FROM builder AS publish
ARG TARGETARCH
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./AccountingService.csproj" --use-current-runtime -r linux-musl-$TARGETARCH -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false
```

**Comment by MMartyn** [comment]
It's getting set. I had checked the build log and see it being set. But I think it needs to have those changes I mentioned in the second stage. If you look at the cart image you can see that the argument is being used in both stages and I think that is what is missing.

**Comment by julianocosta89** [comment]
Thanks @MMartyn, I've sent a PR with the change.
Locally it is building fine!

**Comment by julianocosta89** [comment]
Tagging some @open-telemetry/dotnet-instrumentation-approvers here to see if we can get some help.

While this PR https://github.com/open-telemetry/opentelemetry-demo/pull/1805/files builds fine, the service doesn't emit traces, and there are no errors raised at all.

I'm reverting it, but this will bring @MMartyn error back.
Any ideas of what is going on?

**Comment by MMartyn** [comment]
I see this in the logs on the service: 
```
/app/libOpenTelemetry.AutoInstrumentation.Native: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/libOpenTelemetry.AutoInstrumentation.Native: cannot open shared object file: No such file or directory
```

**Comment by julianocosta89** [comment]
Which OS are you running this @MMartyn ?
I troubleshot this the whole day and got no error messages at all 🙃

**Comment by MMartyn** [comment]
I logged into the container and checked the open telemetry logs in /var/logs/opentelemetry/dotnet. Don't know why it doesn't work though. The working one doesn't have those errors but also doesn't have the files that the broken one is looking for either.
