### ISSUE TITLE
How can I crosscompile with a MAC M1 for a linux target platform? 

### ISSUE THREAD

**Issue by sergiohinojosa** [open-telemetry/opentelemetry-demo#1801]
# Question

When I deploy the images/pods built without changing any configuration to a linux system I get an error like the following:

`
exec ./build/install/opentelemetry-demo-ad-service/bin/AdService: exec format error
`

If I set as a global environment the default platform to be linux/amd64

`
DOCKER_DEFAULT_PLATFORM=linux/amd64
`

then I get an error in the shipping service since this is C++ and has more plattform dependencies.

`
 > [shippingservice builder 3/8] RUN if [ "linux/amd64" = "linux/arm64" ] ; then         apt-get update && apt-get install --no-install-recommends -y g++ libc6-dev libprotobuf-dev protobuf-compiler ca-certificates;     elif [ "linux/amd64" = "linux/arm64" ] ; then         apt-get update && apt-get install --no-install-recommends -y g++-aarch64-linux-gnu libc6-dev-arm64-cross libprotobuf-dev protobuf-compiler ca-certificates &&         rustup target add aarch64-unknown-linux-gnu &&         rustup toolchain install stable-aarch64-unknown-linux-gnu;     else         echo "linux/amd64 is not supported";         exit 1;     fi:
0.520 linux/amd64 is not supported
 failed to solve: process "/bin/sh -c if [ \"${TARGETPLATFORM}\" = \"${BUILDPLATFORM}\" ] ; then         apt-get update && apt-get install --no-install-recommends -y g++ libc6-dev libprotobuf-dev protobuf-compiler ca-certificates;     elif [ \"${TARGETPLATFORM}\" = \"linux/arm64\" ] ; then         apt-get update && apt-get install --no-install-recommends -y g++-aarch64-linux-gnu libc6-dev-arm64-cross libprotobuf-dev protobuf-compiler ca-certificates &&         rustup target add aarch64-unknown-linux-gnu &&         rustup toolchain install stable-aarch64-unknown-linux-gnu;     else         echo \"${TARGETPLATFORM} is not supported\";         exit 1;     fi" did not complete successfully: exit code: 1
make: *** [build-and-push-dockerhub] Error 17
`

then I tried to live without the shipping service by taking the build out from docker compose but the next svc fails

`

 > [frauddetectionservice] importing cache manifest from docker.io/shinojosa/astroshop:1.12.0-frauddetectionservice:
failed to solve: process "/bin/sh -c chmod +x /usr/local/bin/install-php-extensions   && install-php-extensions     opcache     pcntl     protobuf     opentelemetry" did not complete successfully: exit code: 100
make: *** [build-and-push-dockerhub] Error 17
`

Any hints would be greately appretiated

Sergio

**Comment by julianocosta89** [comment]
Hey @sergiohinojosa 👋🏽 
Nice to see you here!

You can use the following to cross-compile:

```
make create-multiplatform-builder
make build-multiplatform
```

That will use `docker buildx` to compile for `platform=linux/amd64,linux/arm64`.

**Comment by sergiohinojosa** [comment]
Hi @julianocosta89 nice to see you! long time no see! 
I hope you are doing great! 

hey, thanks for your reply. I was working with a version that did not have the multiplatform builder in the Makefile. I just pulled everything and gave it a try, but unfortunately I'm getting a docker error that does not support exporting manifest lists. See below. Any hints?

```
make create-multiplatform-builder
docker buildx create --name otel-demo-builder --bootstrap --use --driver docker-container --config ./buildkitd.toml
[+] Building 2.3s (1/1) FINISHED
 => [internal] booting buildkit                                                                                                                                                                                                                           2.3s
 => => pulling image moby/buildkit:buildx-stable-1                                                                                                                                                                                                        1.8s
 => => creating container buildx_buildkit_otel-demo-builder0                                                                                                                                                                                              0.4s
otel-demo-builder
❯ make build-multiplatform
# Because buildx bake does not support --env-file yet, we need to load it into the environment first.
set -a; . ./.env.override; set +a && docker buildx bake -f docker-compose.yml --load --set "*.platform=linux/amd64,linux/arm64"
[+] Building 0.2s (1/1) FINISHED                                                                                                                                                                                            docker-container:otel-demo-builder
 => [internal] load local bake definitions                                                                                                                                                                                                                0.0s
 => => reading docker-compose.yml 22.31kB / 22.31kB                                                                                                                                                                                                       0.0s
ERROR: docker exporter does not currently support exporting manifest lists
make: *** [build-multiplatform] Error 1
```


Thanks and best

**Comment by julianocosta89** [comment]
I'll ask for help here 😅 
@puckpuck any ideas?

**Comment by julianocosta89** [comment]
@sergiohinojosa which OS are you running it?
Also, which Docker version?

**Comment by sergiohinojosa** [comment]
Hi @julianocosta89 ,
I have an MacBook Pro, M1 with 64 Gb.
ProductVersion:	      14.7 (Sonoma)
BuildVersion:		       23H124

Docker version 24.0.7, build afdd53b

**Comment by julianocosta89** [comment]
That's exactly what I have, even Docker version

**Comment by sergiohinojosa** [comment]
Hi @julianocosta89 ,

thanks for the hint. So I  enabled the beta-feature, pulled the latest changes, deleted and created a new multi-platform-builder. 

it can successfully start to build, but I get this errors:
1.- Loadgenerator image:
```
 > [loadgenerator linux/arm64 builder 1/3] RUN apt-get -qq update     && apt-get install -y --no-install-recommends g++     && rm -rf /var/lib/apt/lists/*:
0.587 W: GPG error: http://deb.debian.org/debian bookworm InRelease: At least one invalid signature was encountered.
0.587 E: The repository 'http://deb.debian.org/debian bookworm InRelease' is not signed.
0.587 W: GPG error: http://deb.debian.org/debian bookworm-updates InRelease: At least one invalid signature was encountered.
0.587 E: The repository 'http://deb.debian.org/debian bookworm-updates InRelease' is not signed.
0.587 W: GPG error: http://deb.debian.org/debian-security bookworm-security InRelease: At least one invalid signature was encountered.
0.587 E: The repository 'http://deb.debian.org/debian-security bookworm-security InRelease' is not signed.
------
Dockerfile:8
--------------------
   7 |     FROM base AS builder
   8 | >>> RUN apt-get -qq update \
   9 | >>>     && apt-get install -y --no-install-recommends g++ \
  10 | >>>     && rm -rf /var/lib/apt/lists/*
  11 |
--------------------
ERROR: failed to solve: process "/bin/sh -c apt-get -qq update     && apt-get install -y --no-install-recommends g++     && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100
```
I solved it by adding this to the Dockerfile of the Loadgenerator.

`--allow-unauthenticated --allow-insecure-repositories`

2.- but then I get this error in the Adservice Image

```
Dockerfile:7
--------------------
   5 |     ARG TARGETARCH
   6 |     ARG BUILD_CONFIGURATION=Release
   7 | >>> WORKDIR /src
   8 |     COPY ["/src/accountingservice/", "AccountingService/"]
   9 |     COPY ["/pb/demo.proto", "AccountingService/proto/"]
--------------------
ERROR: failed to solve: ResourceExhausted: failed to compute cache key: write /var/lib/buildkit/runc-overlayfs/snapshots/snapshots/120/fs/usr/share/dotnet/sdk/8.0.404/Sdks/Microsoft.NET.Sdk/tools/net472/NuGet.Protocol.dll: no space left on device

View build details: docker-desktop://dashboard/build/otel-demo-builder/otel-demo-builder0/v11mdp27ogx30mfnq0uli4aaq
make: *** [build-multiplatform] Error 1
```
 I believe the builder image has no more space left, how do I increase the space in the buildkitd.toml file? Or how should I best solve this?

Gracias!

**Comment by julianocosta89** [comment]
I think this may be related to Docker desktop resource limits.

I don't have any extra configuration in the builder.

**Comment by sergiohinojosa** [comment]
Hi @julianocosta89 , so I fixed the ressources in Dockerhub, but now I get another error in the shippingservice. 😅
Can you build with your setup using the crossplatform build?

```
Dockerfile:13
--------------------
  12 |     # Check if we are doing cross-compilation, if so we need to add in some more dependencies and run rustup
  13 | >>> RUN if [ "${TARGETPLATFORM}" = "${BUILDPLATFORM}" ] ; then \
  14 | >>>         apt-get update && apt-get install --no-install-recommends -y g++ libc6-dev libprotobuf-dev protobuf-compiler ca-certificates; \
  15 | >>>     elif [ "${TARGETPLATFORM}" = "linux/arm64" ] ; then \
  16 | >>>         apt-get update && apt-get install --no-install-recommends -y g++-aarch64-linux-gnu libc6-dev-arm64-cross libprotobuf-dev protobuf-compiler ca-certificates && \
  17 | >>>         rustup target add aarch64-unknown-linux-gnu && \
  18 | >>>         rustup toolchain install stable-aarch64-unknown-linux-gnu; \
  19 | >>>     elif [ "${TARGETPLATFORM}" = "linux/amd64" ] ; then \
  20 | >>>         apt-get update && apt-get install --no-install-recommends -y g++-x86-64-linux-gnu libc6-amd64-cross libprotobuf-dev protobuf-compiler ca-certificates && \
  21 | >>>         rustup target add x86_64-unknown-linux-gnu && \
  22 | >>>         rustup toolchain install stable-x86_64-unknown-linux-gnu; \
  23 | >>>     else \
  24 | >>>         echo "${TARGETPLATFORM} is not supported"; \
  25 | >>>         exit 1; \
  26 | >>>     fi
  27 |
--------------------
ERROR: failed to solve: process "/bin/sh -c if [ \"${TARGETPLATFORM}\" = \"${BUILDPLATFORM}\" ] ; then         apt-get update && apt-get install --no-install-recommends -y g++ libc6-dev libprotobuf-dev protobuf-compiler ca-certificates;     elif [ \"${TARGETPLATFORM}\" = \"linux/arm64\" ] ; then         apt-get update && apt-get install --no-install-recommends -y g++-aarch64-linux-gnu libc6-dev-arm64-cross libprotobuf-dev protobuf-compiler ca-certificates &&         rustup target add aarch64-unknown-linux-gnu &&         rustup toolchain install stable-aarch64-unknown-linux-gnu;     elif [ \"${TARGETPLATFORM}\" = \"linux/amd64\" ] ; then         apt-get update && apt-get install --no-install-recommends -y g++-x86-64-linux-gnu libc6-amd64-cross libprotobuf-dev protobuf-compiler ca-certificates &&         rustup target add x86_64-unknown-linux-gnu &&         rustup toolchain install stable-x86_64-unknown-linux-gnu;     else         echo \"${TARGETPLATFORM} is not supported\";         exit 1;     fi" did not complete successfully: exit code: 1

View build details: docker-desktop://dashboard/build/otel-demo-builder/otel-demo-builder0/jlggn4u7gxfi856s6rzolfrl8
make: *** [build-multiplatform] Error 1


```

**Comment by julianocosta89** [comment]
@sergiohinojosa that's what doesn't make sense to me 😅 
I can run the exact same command as I've suggested and it works fine

**Comment by julianocosta89** [comment]
Would this maybe be something to your company network policy or something?
I don't need to use `--allow-unauthenticated --allow-insecure-repositories`

**Comment by sergiohinojosa** [comment]
maybe, I can cross-compile now. The variables of the shipping service needed to be set since in my mac they are not. 
by setting BUILDPLATFORM=arm64 and TARGETPLATFORM=x86_64 it worked. 

Muchas gracias amigo!

**Comment by julianocosta89** [comment]
Great that it worked out Sergio!
Not sure why you had to set the extra stuff, but happy that you can continue!

Hasta luego y feliz Navidad!
