### ISSUE TITLE
kafka pod crashes on amd64 kind cluster 

### ISSUE THREAD

**Issue by stytchiz** [open-telemetry/opentelemetry-demo#1824]
# Bug Report

Which version of the demo you are using? 

c281f7c0e26d9a8543709aad4fb3224ecd63224a

## Symptom
The kafka pod is crashing on a cluster built using `kind`. 

```
$ kubectl get pods
...
opentelemetry-demo-imageprovider-7466d894fb-djb9p           1/1     Running            0               7m11s
opentelemetry-demo-jaeger-7785549bb-8krc8                   1/1     Running            2 (5h43m ago)   2d20h
opentelemetry-demo-kafka-76d4d9f48b-9bwms                   0/1     CrashLoopBackOff   6 (68s ago)     7m11s
opentelemetry-demo-loadgenerator-6994f5db8-v9hnx            1/1     Running            0               7m10s
opentelemetry-demo-paymentservice-857974bcdb-lvbnk          1/1     Running            0               7m10s
...

$ kubectl logs opentelemetry-demo-kafka-76d4d9f48b-9bwms
exec /__cacert_entrypoint.sh: exec format error
```

Investigating this error further, apparently it could have something to do with the image being built for arm64 but running the container on amd64. I'm not using a M1 Macbook (x86 Linux) so can not use the arm64-`kind` binary.

```
$ docker images
REPOSITORY     TAG       IMAGE ID       CREATED       SIZE
kindest/node   <none>    18fbefc20a71   4 weeks ago   1.49GB
$ docker image inspect 18fbefc20a71
[
    {
        "Id": "sha256:18fbefc20a7113353c7b75b5c869d7145a6abd6269154825872dc59c1329912e",
        "RepoTags": [],
        "RepoDigests": [
            "kindest/node@sha256:18fbefc20a7113353c7b75b5c869d7145a6abd6269154825872dc59c1329912e"
        ],
        ...
        "Architecture": "amd64",
        "Os": "linux",
    }
]
```

**What is the expected behavior?**

See above.

**What is the actual behavior?**

See above.

## Reproduce

1. Install `kind-linux-amd64` per https://kind.sigs.k8s.io/docs/user/quick-start/#installing-from-release-binaries
2. https://opentelemetry.io/docs/demo/kubernetes-deployment/#install-using-helm-recommended
3. kubectl get pods

## Additional Context

Please feel free to add any other context about the problem here.

**Comment by stytchiz** [comment]
I tried specifying the amd64 manifest digest, but still get the same error.
```
$ k describe deployments opentelemetry-demo-kafka
  Containers:
   kafka:
    Image:       ghcr.io/open-telemetry/demo:1.12.0-kafka@sha256:9878e8959b942b9b30ce97f479e08bc1bd1faa37623b1b7d8cc5ff73f8b40979
    Ports:       9092/TCP, 9093/TCP
    Host Ports:  0/TCP, 0/TCP
```

**Comment by julianocosta89** [comment]
@stytchiz I believe we should move this issue to the Kind repo: https://github.com/kubernetes-sigs/kind/issues

The 2 different arch are available, but for some reason kind is not pulling the correct one for you, even when you explicitly define it.

I've spun up a kind cluster here and tried it out. everything worked fine 🤔 

Not sure what is going on there.
i've used the latest version of kind btw

**Comment by stytchiz** [comment]
Well that's odd!

I ended up adding a worker node to my kind config and that resolved it. Kafka pod is running now.

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
```

I'll create an issue in the Kind repo to figure out what happened there.
