### ISSUE TITLE
change docker-compse image pull way

### ISSUE THREAD

**Issue by Frapschen** [open-telemetry/opentelemetry-demo#192]
# Feature Request

the docker-compse current use `build` command to create the image, it often occur unexpected problem when someone want to  take a look the demo, like #178 #170 #126, and I notice #184 had merged, can we use the prebuild image instead of build localy? by the way, there is also don't have a clearly way to kown how to find the demo image  in docker hub.

**Comment by wph95** [comment]
> by the way, there is also don't have a clearly way to kown how to find the demo image in docker hub.
'm very sorry about this.
We are not ready to document about this thing yet. This thing is still a work in progress. The plan is to have detailed documentation explaining the corresponding issues when the helm chart is released.
If you are interested in this matter, you can see the context in this issue.

**Comment by Frapschen** [comment]
> 

yes, there is no contradiction, the `image` command have added, I don't notice it. the README.md need a little imporve, only run `docker compose up` the pull stage will fail, if there is a note 'if you want to test the pre-build image, you need export the IMAGE_NAME and IMAGE_VERSION 
 enviroment' the guidance will be better.

**Comment by cartersocha** [comment]
Hey we've implemented this now. Check our most recent docs
