### ISSUE TITLE
New services don't have consistent licensing

### ISSUE THREAD

**Issue by cartersocha** [open-telemetry/opentelemetry-demo#220]
Some services have OpenTelemetry author licensing while others like the shipping service have no licensing.

We need consistent licensing across our new services including: the currency service, feature flag service, shipping service, & email service

**Comment by cartersocha** [comment]
@mtwo Can you please provide some guidance on what we should do to give proper ownership to the otel community / use the appropriate license?

**Comment by ahayworth** [comment]
FWIW When I contributed it, I assumed that the `emailservice` would be licensed under the project-wide Apache license.

But, licensing makes my head hurt, so I'm happy to support fixing that in whatever way needs to be done.

**Comment by cartersocha** [comment]
It should stay under Apache 2. We just want a consistent credit blurb for “OpenTelemetry Authors” or whatever form it takes if that makes sense
