### ISSUE TITLE
Repository Name Change

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry-demo#222]
Per discussion in #153 (and Slack), there's a general consensus that the current repository name should be modified to `opentelemetry-demo` rather than `opentelemetry-demo-webstore`. If we're going to do it, we should do it now before too many links get made. This issue tracks work that needs to be done --

- [x] Request rename in community issue for repository and approver/maintainer teams.
- [x] Modify links to repo in community, opentelemetry.io, etc.
- [x] Modify links to repo in this repository

**Comment by cartersocha** [comment]
I support the name change

**Comment by austinlparker** [comment]
Opened a request for renames here: https://github.com/open-telemetry/community/issues/1115

**Comment by reyang** [comment]
> Opened a request for renames here: [open-telemetry/community#1115](https://github.com/open-telemetry/community/issues/1115)

I've made the change, please help to double check and follow up on https://github.com/open-telemetry/community/issues/1115#issuecomment-1192015057.

**Comment by reyang** [comment]
These are the commands that can help you to migrate:

```sh
git remote remove origin
git remote add origin https://github.com/open-telemetry/opentelemetry-demo.git
git branch --set-upstream-to=origin/main main
```

**Comment by cartersocha** [comment]
Do we need to update any repo stuff to the new name / group names @reyang ? I'm noticing my PRs don't have the approvers auto assigned for instance

**Comment by reyang** [comment]
> Do we need to update any repo stuff to the new name / group names @reyang ? I'm noticing my PRs don't have the approvers auto assigned for instance

I think it's caused by https://github.com/open-telemetry/opentelemetry-demo/blob/b4125aac374822b0e68f79dd91fa060d80eac3a9/.github/CODEOWNERS#L5 which needs to be updated.

**Comment by cartersocha** [comment]
@austinlparker all demo repo links are updated. Just the community & other repos remain

**Comment by cartersocha** [comment]
This should be good now.
