### ISSUE TITLE
yamllint don't give enough message for locating error

### ISSUE THREAD

**Issue by Frapschen** [open-telemetry/opentelemetry-demo#226]
# Bug Report

current yamllint don't give enough message for locating error:

![image](https://user-images.githubusercontent.com/35491170/180354676-a37b7bf6-b08f-4bbd-a0da-902726f17663.png)

if an error occur, we can't find the error location, as the [adrienverge/yamllint](https://github.com/adrienverge/yamllint#overview) show, it can tell us the error locatons clearly.

the command `yamllint . -f github`  is correct? I only find `yamllint --format github` by [search](https://yamllint.readthedocs.io/en/stable/search.html?q=github&check_keywords=yes&area=default)

**Comment by wph95** [comment]
you can saw the detail error in here https://github.com/open-telemetry/opentelemetry-demo/pull/212/files#diff-5c2c0c519ac17acb48d9da9321b869aa61caef2209426fdf00726b1d12321f5eR30
