### ISSUE TITLE
Enable codecov for repo

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry-demo#228]
Per slack -- https://cloud-native.slack.com/archives/C03B4CWV4DA/p1658518984210019

**Comment by austinlparker** [comment]
See https://github.com/open-telemetry/community/issues/1119

**Comment by austinlparker** [comment]
per https://github.com/open-telemetry/community/issues/1119#issuecomment-1195284332, we don't need to actually enable it, we can just upload reports with the action? @cartersocha

**Comment by cartersocha** [comment]
Thanks Austin! @mic-max could you take a look at integrating our new service tests into [this action](https://github.com/marketplace/actions/codecov)?

**Comment by austinlparker** [comment]
Closing; We can re-evalute this later if there's still a want. I'll add it as a topic to the next SIG meeting for inclusion in 1.4
