### ISSUE TITLE
[ci] add license lint check 

### ISSUE THREAD

**Issue by fatsheep9146** [open-telemetry/opentelemetry-demo#233]
# Feature Request

I think the repo missing license lint check. 

I submit a pr with a new but without license info, all checks are passed

https://github.com/open-telemetry/opentelemetry-demo/pull/232/commits/a14ac2509d0ea029c0a3178a0cbbf6f7dd65906f

**Describe the solution you'd like:**

What do you want to happen instead? What is the expected behavior?

Throw out check failed for pull request, just like the collector repo does

https://github.com/open-telemetry/opentelemetry-collector/blob/74cca75ee1b84b8da72b73122984b52b7857489f/.github/workflows/build-and-test.yml#L79-L80

**Comment by cartersocha** [comment]
Is there an equivalent of this in the dotnet repo @reyang ?

**Comment by reyang** [comment]
> Is there an equivalent of this in the dotnet repo @reyang ?

Nope, I guess the model is different. OpenTelemetry .NET does not redistribute any source or binary.
I can see how this is important for demo and collector.

**Comment by cartersocha** [comment]
@bogdandrutu or @tigrannajaryan do y’all have suggestions or guidance on how the collector repo handles licensing checks & general licensing? We could use some help maturing our story here

**Comment by cartersocha** [comment]
@fatsheep9146 all the need or updated services should have basic license info in one place now. I did a v1 review. 

We could potentially add this now or decide we don’t need it?
