### ISSUE TITLE
Optimize README.md to make it more friendly for beginners.

### ISSUE THREAD

**Issue by wph95** [open-telemetry/opentelemetry-demo#256]
## Current issues.
I personally feel that the current documentation quickstart section is not simple enough and not clear enough.
git clone to local, and then build the image locally. The threshold for this operation is high. Not "quick" enough

## Solution.
We've done a lot of things to optimize deployment. But we don't reflect it in the documentation. A possible solution.

```
## Deployment
- [Docker Compose](./doc/compose.md)
- [Helm](./doc/deployment/helm.md)
- [Kubernetes YAML](. /doc/deployment/kubernetes.md)
```

Also, in the docker compose scenario, it is recommended to use pre-built images instead of local builds

**Comment by cartersocha** [comment]
I like the idea of reducing the readme content. It feels like a block of content today. 

The kubernetes section in my pr is fairly simple. If we match the docket instructions then that might be one potential improvement. 

I’m open to standalone docs too

**Comment by mviitane** [comment]
I agree the README is a bit long and complex, and the Kubernetes part makes it even longer&more complex. The Kubernetes description also has the limitation that it currently doesn’t cover even the basic option (port-forward) to expose the frontend. ⇒ The deployment part can get even longer in the future.

I think splitting the deployment options into separate sub-pages would be a great improvement. I can help with this if needed.

**Comment by cartersocha** [comment]
@wph95 do you still have the time to work on this?

**Comment by cartersocha** [comment]
Readme is cleaned up
