### ISSUE TITLE
Port bindings for webstore services

### ISSUE THREAD

**Issue by puckpuck** [open-telemetry/opentelemetry-demo#257]
I just got this after running `docker compose up` 
```
Error response from daemon: Ports are not available: listen tcp 0.0.0.0:7000: bind: address already in use
```

Turns out port 7000 is used by MacOS for AirPlay.  The same port we have the currency service binding to.

I think it makes sense we only use ports in the dynamic range (49151 - 65535) for each service in the demo. Things like the Otel collector, Grafana, Prometheus, etc should stay where they are, but the webstore services should be binding to ports that are less likely to be used for other reasons.

**Comment by cartersocha** [comment]
Interesting issue. Thanks for bringing this up. @mic-max fyi 🦞
