### ISSUE TITLE
Improve vendor fork experience

### ISSUE THREAD

**Issue by cartersocha** [open-telemetry/opentelemetry-demo#267]
Vendors need proper documentation and repo improvements to ensure their forks aren't difficult to maintain.

**Comment by cartersocha** [comment]
I think the main outstanding item here is configure the helm chart for new vendors. 

FYI @joshleecreates, @austinlparker

**Comment by julianocosta89** [comment]
Do you mean documenting this?
https://cloud-native.slack.com/archives/C03B4CWV4DA/p1664974983694979

**Comment by cartersocha** [comment]
That link isn't redirecting properly for me so not sure. But at least have something like [this](https://github.com/open-telemetry/opentelemetry-demo/blob/main/docs/docker_deployment.md#bring-your-own-backend) documented for kubernetes

**Comment by cartersocha** [comment]
I'd be curious if vendors would like more specific documentation around forking + maintaining too. Microsoft doesn't have a fork today so I don't have a lived perspective

**Comment by julianocosta89** [comment]
What I meant to share was the comment on slack by @puckpuck showing how to use helm to deploy the demo and configure the collector to a specific vendor

**Comment by joshleecreates** [comment]
I can take a first stab at documenting the fork process this week.

**Comment by joshleecreates** [comment]
> I'd be curious if vendors would like more specific documentation around forking + maintaining too. Microsoft doesn't have a fork today so I don't have a lived perspective

From my perspective the key part will be documenting the options available via custom a custom values file. That covers all of the use cases Instana will need for our fork.

**Comment by cartersocha** [comment]
Yeah that'd be great to get @joshleecreates

**Comment by cartersocha** [comment]
Thanks for taking care of this Josh!
