### ISSUE TITLE
[featureflag] - Dockerfile should build protobuf modules

### ISSUE THREAD

**Issue by puckpuck** [open-telemetry/opentelemetry-demo#279]
# Feature Request

Update Dockerfile to build artifacts similar to how other services are built. 

- [ ] Use the top-level build context, updating paths in Dockerfile accordingly
- [ ] Copy the top-level demo.proto file into the appropriate build location
- [ ] Run `rebar3 grpc gen` as part of the build

cc @tsloughter

**Comment by cartersocha** [comment]
Can we close this @puckpuck ?

**Comment by puckpuck** [comment]
#599 will close this
