### ISSUE TITLE
error docker-compose up

### ISSUE THREAD

**Issue by zgq25302111** [open-telemetry/opentelemetry-demo#299]
# Bug Report

Which version of the demo you are using? (please provide either a specific
[commit
hash](https://github.com/open-telemetry/opentelemetry-demo/commits/main)
or a specific
[release](https://github.com/open-telemetry/opentelemetry-demo/releases)).

## Symptom

run error when commond:docker-compose up
desc:
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

# After edit docker-compose.yml file, 
change version 3.9 to 3.3, type commond docker-compose up, then prompt:
ERROR: The Compose file './docker-compose.yml' is invalid because:
networks.default value Additional properties are not allowed ('name' was unexpected)
Invalid top-level property "x-default-logging". Valid top-level sections for this Compose file are: version, services, networks, volumes, secrets, configs, and extensions starting with "x-".

You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**What is the expected behavior?**

What do you expect to see?

**What is the actual behavior?**

What did you see instead?

## Reproduce

Provide the minimum required steps to result in the issue you're observing.

We will close this issue if:

* The steps you provided are complex.
* If we can not reproduce the behavior you're reporting.

**Comment by mviitane** [comment]
Hi @zgq25302111, you could check your docker compose version. It could be that you're running too old docker compose to support docker-compose.yml file version 3.9.

**Comment by mviitane** [comment]
Issue to be closed as can't be reproduced?

**Comment by zgq25302111** [comment]
ok
