### ISSUE TITLE
Improve the images

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-demo#31]
Currently the screenshots look bad under dark theme

![image](https://user-images.githubusercontent.com/17327289/169636611-f00a5fbd-775e-41a8-aa8d-d41e2e45f661.png)

**Comment by cartersocha** [comment]
What are you specific issues with the current pics? I think they look fairly similar in light mode although small & pixellated

**Comment by mviitane** [comment]
Jaeger screenshots have a dark top bar -> no contrast to the background. However, for me, this is still fine, because the text is clearly visible.

One possible improvement to make the screenshots look better would be to remove borders from the screenshot tables.
