### ISSUE TITLE
Providing greater control over the loadgenerator

### ISSUE THREAD

**Issue by Mwad22** [open-telemetry/opentelemetry-demo#320]
# Feature Request

Providing greater control over the loadgenerator.

**Is your feature request related to a problem?**

Currently, there is not much control given to the user over the loadgenerator beyond being able to change the number of `USERS` via an environment variable. No simple way to control the loadgenerator, and locust web UI is specifically disabled via `--headless` flag at docker entrypoint ([see here](https://github.com/open-telemetry/opentelemetry-demo/blob/1996384cfd4597fb8aaae87b34394def05b2db29/src/loadgenerator/Dockerfile#L23)) so users aren't able to override it.

**Describe the solution you'd like:**
Providing more control over the loadgenerator via the following:

- [x] removing the `--headless` and `-u` tags from loadgenerator's docker entry point and supporting this default behaviour via `LOCUST_HEADLESS` and   `LOCUST_USERS` environment variables. This allows users to override these environment variables in case they would like to expose the Locust UI and allow users more control over the loadgenerator.
- [x]   Supporting `LOCUS_HOST` option. Allows vendors that want to add an ingress route to the demo on k8s to direct loadgen to go through the ingress route.

**Describe alternatives you've considered.**

On k8s, setting env variable `USERS` to 0 and using command line within the loadgenerator pod.

**Comment by puckpuck** [comment]
This was fixed in #316
