### ISSUE TITLE
Release tag not being picked up by build

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry-demo#323]
While releasing 0.3.0 we discovered that the release tag was not properly being inserted as the image tag (0.3.0 built as 0.1.0) -- this was temporarily worked around by updating the .env file, but it worked correctly for 0.2.0, so something here needs investigation.

**Comment by wph95** [comment]
https://docs.docker.com/compose/environment-variables/
> Values in the shell take precedence over those specified in the .env file.

<img width="1194" alt="截屏2022-08-19 13 45 41" src="https://user-images.githubusercontent.com/2732352/185704501-ca8f2b97-5221-4880-8f6d-0454046993d5.png">

yeah it's very strange
