### ISSUE TITLE
cache export feature is currently not supported for docker driver

### ISSUE THREAD

**Issue by julianocosta89** [open-telemetry/opentelemetry-demo#349]
# Bug Report

Which version of the demo you are using?
3ccd221fafefdb3c8b3fdcc302ad03ed5dca1f6f.

## Symptom

Since merge of #304 I can't run the project anymore. 
Whenever trying to start the project I'm getting this error: 
`"cache export feature is currently not supported for docker driver. Please switch to a different driver"`

**What is the expected behavior?**

I expect to run `docker compose up` and have the project running.

**Comment by cartersocha** [comment]
https://github.com/open-telemetry/opentelemetry-demo/pull/350 temporarily fixed

**Comment by GaryPWhite** [comment]
@puckpuck are we worried at all about the `export` feature failing? I assumed from conversations / this chat that we wanted to have the `cache_to` (export) feature working to resolve this issue.
