### ISSUE TITLE
Frontend service is actually written in Typescript , but the docs say Javascript

### ISSUE THREAD

**Issue by saurabhdes** [open-telemetry/opentelemetry-demo#358]
# Bug Report

Which version of the demo you are using? 
[commit hash](https://github.com/open-telemetry/opentelemetry-demo/commit/9c64b4ab3b2d0b79e5254a8d03a61e478ecb05dc)

## Symptom

Files with code in [frontend directory](https://github.com/open-telemetry/opentelemetry-demo/tree/main/src/frontend) directory end in .ts - implying Frontend service is actually written in Typescript. But the docs say Javascript. By docs i am referring to [service_table](https://github.com/open-telemetry/opentelemetry-demo/blob/main/docs/service_table.md)  and [mermaid graph](https://github.com/open-telemetry/opentelemetry-demo/blob/main/README.md?plain=1#L45)

**What is the expected behavior?**

Change Frontend service description from Javascript to Typescript to make it more accurate. 

**What is the actual behavior?**

Frontend service description mentions it's written in Javascript.

## Reproduce

Go to the links displayed in Symptom section above.

**Comment by mic-max** [comment]
Hello, yes, I believe there was a decision made to say JavaScript here instead of, yes, the more accurate TypeScript. IIRC it was because the actual OTel library is for JavaScript and the example should still apply mostly to JavaScript developers despite some syntax differences.
