### ISSUE TITLE
docker compose up --no-build command fails with error on Mac 

### ISSUE THREAD

**Issue by saurabhdes** [open-telemetry/opentelemetry-demo#367]
# Bug Report

Which version of the demo you are using?
Latest commit from main branch

## Symptom

Unable to launch the App after running `docker compose up --no-build` on my Local Mac. 
I get error message **Error response from daemon: manifest unknown**

**What is the expected behavior?**
All the docker containers of respective demo services should get started

**What is the actual behavior?**

What did you see instead?
I get error message **Error response from daemon: manifest unknown**

## Reproduce

1. git clone https://github.com/open-telemetry/opentelemetry-demo.git
2. cd opentelemetry-demo/
3. docker compose up --no-build

## Additional Context
Here's the workaround that worked for me on my Mac. 
1. Changed cache_from to use the full path vs env variable for all the services in docker-compose.yml file 
        - ghcr.io/open-telemetry/demo:v0.3.4-alpha-emailservice
2. Then ran `docker compose up  frontend --no-build` this created frontend and all the dependant services in about 3 min.

The other thing i noticed is doing `docker compose convert` does seem to do the env variable substitution correctly.
So it's puzzling why the command docker compose up --no-build doesn't work for me.

**Comment by saurabhdes** [comment]
After more investigation i found the issue is because of newly added `quoteservice`. Which lacks a cache_from section like below

cache_from:
        - ${IMAGE_NAME}:${IMAGE_VERSION}-quoteservice

But adding the above to docker compose doesn't solve the problem because the image is not yet pushed to ghcr.io

@julianocosta89 - Since you added the quoteservice recently, is it possible for you to push the quoteservice image to ghcr.io with the same version number as other services ? 
Once the image is pushed I can then create a PR to add a cache_from section like mentioned above.
Please let me know your thoughts, open to any other ideas. I am new to the repo so not familiar with the process.

**Comment by cartersocha** [comment]
@austinlparker please help on this and share with the other maintainers / approvers on how to do version releases on slack

**Comment by cartersocha** [comment]
I’m assuming as part of the version upgrade we have a couple places in the code to update for the new version number too. Unless we addressed that problem

**Comment by austinlparker** [comment]
I believe any maintainer can do a release, you just click the new release button in GitHub. I'm traveling today but can do one later this evening if you don't get to it first.

**Comment by austinlparker** [comment]
I believe any maintainer can do a release, you just click the new release button in GitHub. I'm traveling today but can do one later this evening if you don't get to it first.

**Comment by cartersocha** [comment]
I think I just released v0.4.0! I just followed the previous release examples

@julianocosta89 When we integrate the service we can bump it a minor version.
