### ISSUE TITLE
Which languages have RC/beta metric instrumentation available?

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry-demo#376]
Per discussion at SIG meeting, which languages have support for metric instrumentation that we are not using at this point?

**Comment by cijothomas** [comment]
.NET has some. Adding one here : https://github.com/open-telemetry/opentelemetry-demo/pull/393
Will add more as future PRs. (I am just new to the repo learning the practices here...)

**Comment by cartersocha** [comment]
GA: 
Dotnet
Java
Python (?) - unclear. Website says stable

RC:
Cpp
JavaScript

Beta:

Alpha:
Swift
Rust
Erlang
Go
PHP

No:
Ruby
