### ISSUE TITLE
Pass temporality preference environment variable though to services

### ISSUE THREAD

**Issue by pichlermarc** [open-telemetry/opentelemetry-demo#383]
# Feature Request

**Is your feature request related to a problem?**

At this point in time, the demo cannot be easily adapted to export delta metrics instead of cumulative. Once more metrics are being added this might make the demo more difficult to use for people that want to try out different backends.

**Describe the solution you'd like:**

It would be great to have the `OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE` passed through to services on the `docker-compose.yml` file, so that temporality can be more easily changed, but keep cumulative as a default.

**Describe alternatives you've considered.**

My alternative now is to provide more setup instructions with the demo, which basically just pass through the environment variable to all the applicable services. 

# 
I can work on this issue if this is something we'd want in this repo. :slightly_smiling_face:

**Comment by cartersocha** [comment]
@puckpuck could this help with the JavaScript issue too?

**Comment by cartersocha** [comment]
Ah nevermind but this would be nice to have @pichlermarc

**Comment by pichlermarc** [comment]
Alright, then I'll start working on this :slightly_smiling_face:
