### ISSUE TITLE
Restyle and update product catalog, frontend, etc.

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry-demo#39]
**Objective**

Bring out a bit of the project's personality by rebranding from 'Online Boutique' to something else. Maybe 'Astronomy Shop'? :)

- Update frontend logo
- Update product key art/product names
- Rebrand colors/fonts to align with opentelemetry.io styles

**Comment by austinlparker** [comment]
See also #31 -- ensure that product images work well in dark mode/dark bg.

**Comment by cartersocha** [comment]
The physical page quality looks okay to me in dark mode. Is it just the picture quality itself or the product pictures in the web store?

**Comment by wph95** [comment]
Personal thoughts, can we refer to https://store.cncf.io/ for our demo store's ui/merchandise (not sure if there will be copyright issues) 
by the way, I'm interested in helping the demo store optimize the ui

**Comment by mic-max** [comment]
I came looking for an existing issue to suggest an astronomy shop too since that is already the theme of the site https://opentelemetry.io/

**Comment by cartersocha** [comment]
Not sure if we can piggyback off the cncf domain. We might be better off using opentelemetry itself. 

It would be cool to have it do something like store.opentelemetry.io. @austinlparker any issues with the copyright you can think of? Don't want to step on any toes.

**Comment by austinlparker** [comment]
I don't think there'd be copyright issues.

As a stretch goal, it might be nice to see if we could keep an instance of this running somewhere and have the dashboards and stuff going as well.

**Comment by xoscar** [comment]
Hello Team, I'm Oscar Reyes from the Tracetest team and I'm going to be working on a proposal to move the front-end section of the app to a SPA. I'm really excited to start contributing 😄

**Comment by tsloughter** [comment]
/cc'ing @maciej-szlosarczyk -- assuming you still want to update the featureflag service UI you might want to keep tabs on this issue and @xoscar's work :)

**Comment by kdhamric** [comment]
@olha23 has done a preliminary mock of the online store trying to match the style of the opentelemetry.io site with the 'Astronomy Shop' theme.  Take a look and give her feedback: https://www.figma.com/file/6YjjnLhE7QExI2RY0LyCpU/OTEL-demo?node-id=2%3A26

**Comment by cartersocha** [comment]
FYI @maciej-szlosarczyk on the figma design. 

@kdhamric @olha23, looks fantastic. Only nit feedback from the sig meeting is we’d like more product diversity but overall excellent work & easy fix

@xoscar I think we’re good to move forward with this design

**Comment by xoscar** [comment]
Hello everyone, I just opened the PR with the updated changes for the frontend https://github.com/open-telemetry/opentelemetry-demo/pull/236
