### ISSUE TITLE
List of currencies should be alphabetical

### ISSUE THREAD

**Issue by puckpuck** [open-telemetry/opentelemetry-demo#395]
# Feature Request

**Is your feature request related to a problem?**

The list of currencies in the UI of the app is not alphabetical, making it hard to find the currency you desire.

**Describe the solution you'd like:**

Sort the list of currencies rendered in the UI.

**Comment by cartersocha** [comment]
I think this was added.

**Comment by julianocosta89** [comment]
It wasn't actually @cartersocha

**Comment by puckpuck** [comment]
#448 did solve this. I should of referenced in in the PR.

**Comment by julianocosta89** [comment]
Oh sorry... I've missed that one!

**Comment by cartersocha** [comment]
Nbd! I should’ve referenced the pr when I closed this but I remembered merging it
