### ISSUE TITLE
Update the frontend service to use 2 different exporters ( Client & Backend)

### ISSUE THREAD

**Issue by henrikrexed** [open-telemetry/opentelemetry-demo#397]
# Feature Request
Once the Demo is deployed, the browser is trying to send spans to localhost ( or the collector address).
To make it more realistic all the client side spans need to be sent to a specific url.

**Describe the solution you'd like:**

i have tried to resolve this  by creating a new Environment variable for the Frontend code  :
-> FrontendTracer.ts : 
 const provider = new WebTracerProvider({
    resource: new Resource({
      [SemanticResourceAttributes.SERVICE_NAME]: process.env.NEXT_PUBLIC_OTEL_SERVICE_NAME,
    }),
  });

What is expected is that all the spans generated by the backend will be sent to a local collector.
The spans produced by the end-user browser should use another endpoint to export the spans. 

In the context of k8s a specific ingress rule needs to be created to expose the collector out of the cluster.

**Comment by cartersocha** [comment]
@xoscar could you potentially take a look at this?

**Comment by xoscar** [comment]
Yep, this is part of what we discussed two weeks ago about adding new env vars to the helm chart, I'll take a look!
