### ISSUE TITLE
Container information not sent by demo apps

### ISSUE THREAD

**Issue by gbbr** [open-telemetry/opentelemetry-demo#403]
# Feature Request

Would it make sense to add [container information](https://pkg.go.dev/go.opentelemetry.io/otel/sdk@v1.10.0/resource#WithContainerID) to the demo apps? I have noticed in [current apps](https://github.com/open-telemetry/opentelemetry-demo/blob/main/src/checkoutservice/main.go#L73) that no resource information of any kind is added. Is there a reason for this? Would it be ok to add this? I think it can help enrich the experience.

Is there any way to enable this in the demo that I wasn't able to figure out?

**Comment by svrnm** [comment]
A bunch of the PRs I introduced recently are adressing this:

* https://github.com/open-telemetry/opentelemetry-demo/pull/651
* https://github.com/open-telemetry/opentelemetry-demo/pull/648
* https://github.com/open-telemetry/opentelemetry-demo/pull/663
* https://github.com/open-telemetry/opentelemetry-demo/pull/662

**Comment by austinlparker** [comment]
Closing this as part of issue cleanup. If there's anything that needs to be done, please create a new issue.
