### ISSUE TITLE
Error: Cannot find module './Instrumentation.js' when running frontend service for local development

### ISSUE THREAD

**Issue by kodayashi** [open-telemetry/opentelemetry-demo#407]
# Bug Report

Which version of the demo you are using?

main (latest)

## Symptom

I'm trying to follow the README for running the frontend service locally. After running

docker compose run --service-ports -e NODE_ENV=development --volume $(pwd)/src/frontend:/app --volume $(pwd)/pb:/app/pb frontend sh

I get this error:

Error: Cannot find module './Instrumentation.js'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at Module._preloadModules (node:internal/modules/cjs/loader:1303:12)
    at loadPreloadModules (node:internal/bootstrap/pre_execution:583:5)
    at prepareMainThreadExecution (node:internal/bootstrap/pre_execution:95:3)
    at node:internal/main/run_main_module:7:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}

It looks like npm start is being run (per package.json) as opposed to npm dev. Am I doing something wrong here?

## Reproduce

Just follow the instructions for running the frontend service locally in the README file.

**Comment by julianocosta89** [comment]
Are you running the command from the root folder of the project?
I mean not in the `src/frontend` folder.

**Comment by kodayashi** [comment]
@julianocosta89 - Correct, I'm running it from the root folder.

**Comment by julianocosta89** [comment]
Cool, just to be sure.
I'll try to reproduce.
Thanks for reporting it!

**Comment by julianocosta89** [comment]
I'm on the road ATM, I will take a look later.
Maybe @xoscar has an idea of what may be the root cause of that.

**Comment by kodayashi** [comment]
Thanks @julianocosta89. @xoscar all I can tell at this point is that npm is being run in production mode as opposed to dev. In package.json, there's the requirement for ./Instrumentation.js in "start" (which is referenced in the error above)

"start": "node --require ./Instrumentation.js server.js"

Whereas "dev" in package.json is what we're looking to run from what I can tell as it has the correct relative path to Instrumentation.js:

"dev": "npm run grpc:generate && NODE_OPTIONS='-r ./utils/telemetry/Instrumentation.js' next dev"

So, I think the answer lies in understanding why start is firing off instead of dev when running "docker compose run..." command in the frontend README file.

**Comment by xoscar** [comment]
Oh I think it's because a change was made to move away from `CMD` in the frontend docker file to use `ENTRYPOINT` instead. And the problem with that is that it doesn't allow for command overwrite in this case when running the container it will always run `npm start` @julianocosta89 changes https://github.com/open-telemetry/opentelemetry-demo/pull/342/files

**Comment by julianocosta89** [comment]
Hey @xoscar I may need your help here.
We can still overwrite the `ENTRYPOINT` but I faced some issues with the next steps.

1st to overwrite the `ENTRYPOINT` we need the following command:
`
docker compose run --service-ports -e NODE_ENV=development --volume $(pwd)/src/frontend:/app --volume $(pwd)/pb:/app/pb --entrypoint sh frontend
`

Once we `sh` into the container we have the 1st issue:
The user `nextjs` has no permission to create folder, so the `mkdir -p ./protos` fails.

I've tried switching to root `USER`, but then I get the 2nd issue:
Nothing happens. Looks like the `npm run dev` is not doing anything.

Any ideas?

**Comment by julianocosta89** [comment]
Also, @puckpuck do you see any issue if we return the `frontend` to `CMD` instead of `ENTRYPOINT`.
I've tested locally and changing it back to `CMD`solves the issue.

**Comment by puckpuck** [comment]
The only issue I see is consistency with the other services, which all use `ENTRYPOINT`

**Comment by julianocosta89** [comment]
@puckpuck if consistency is the only issue, I'll go ahead and send a PR to use `CMD` as this solves the issue.

**Comment by julianocosta89** [comment]
Hello all, I've just sent a PR fixing this :)
