### ISSUE TITLE
Support deployment to Kubernetes

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry-demo#41]
**Objective**

Highlight the integration between OpenTelemetry and the greater cloud-native ecosystem by supporting Kubernetes.

The following are a non-exhaustive list of requirements for this --

- Minikube/local k8s as the minimum requirement for installation
- Self-deployment of services via ArgoCD
- OpenTelemetry deployment via OpenTelemetry Operator
- Kubernetes API Server Tracing enabled
- Kubernetes Metrics scraped by Collector
- Kubernetes resource detectors on Collector (and associated telemetry enhancement)

**Comment by cartersocha** [comment]
Done
