### ISSUE TITLE
Ensure sufficient breadth in trace features across services

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry-demo#42]
The following is a list of requirements that we need to evaluate before declaring v1 for trace telemetry. These requirements are across the entire application; Not all services will meet all requirements.

- [ ] Automatic Instrumentation is being used where appropriate.
- [ ] Automatic instrumentation is being injected through the OpenTelemetry Operator.
- [ ] Library instrumentation is being used if automatic instrumentation is unavailable.
- [ ] Services extend automatic instrumentation.
  - [ ] New attributes/events attached to existing spans.
  - [ ] New spans are being created from existing spans.
- [ ] Automatic and Manual Context Propagation are being demonstrated.
  - [ ] Interprocess context propagation is demonstrated.
  - [ ] Intraprocess context propagation is demonstrated.
- [ ] Trace links are being demonstrated in appropriate places (security boundary, fan-in/fan-out)
- [ ] Telemetry is not being sampled upfront.
- [ ] Telemetry is not being filtered upfront.
- [ ] Baggage is being set and read appropriately (i.e., baggage must be explicitly set as attributes on spans)

**Comment by cartersocha** [comment]
depending on timeline for new services this might be a rolling issue as new components are added. Should we plan on splitting these into stages?

**Comment by cartersocha** [comment]
We are done on tracing!
