### ISSUE TITLE
feat: Add queue example to demo 

### ISSUE THREAD

**Issue by secustor** [open-telemetry/opentelemetry-demo#429]
# Feature Request
Add a queue/message bus to this demo to demonstrate capabilites regarding async workflows. 

**Is your feature request related to a problem?**

**Describe the solution you'd like:**

Add a RabbitMQ or Kafka instance to make use of an event driven architecture. 
To show the usage, new microservices are needed.     

One adapted application as producer and two as consumer should be enough. 

**Describe alternatives you've considered.**

**Comment by saurabhdes** [comment]
Great idea ! Kafka will be great as nowadays I see it used much more than RabbitMQ and others for messaging.

**Comment by secustor** [comment]
I have started working on this.
