### ISSUE TITLE
Produce multi-arch/platform images and improve build times.

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry-demo#458]
To address #396

**Comment by cartersocha** [comment]
If possible it'd be nice to have this by the 1.0 release on friday but nbd if you don't have the bandwidth

**Comment by cartersocha** [comment]
@JaredTan95

**Comment by JaredTan95** [comment]
> If possible it'd be nice to have this by the 1.0 release on friday but nbd if you don't have the bandwidth

Sorry, I'm afraid I won't be able to catch up on Friday... :-(

**Comment by austinlparker** [comment]
Reopening this -- after merging this in, release builds fail.

**Comment by austinlparker** [comment]
@JaredTan95 could you take another look today?

**Comment by austinlparker** [comment]
https://github.com/open-telemetry/opentelemetry-demo/actions/runs/3286470674/jobs/5414695123 is a link to a failed run

**Comment by JaredTan95** [comment]
I noticed a revert PR https://github.com/open-telemetry/opentelemetry-demo/pull/502, I found the failure issue and I will reopen PR after fixed it.

**Comment by austinlparker** [comment]
Updates to this issue for posterity:

- I was able to fix the issues causing failed builds. These were mostly due to build contexts not being standard across every service.
- Another persistent issue was OOM kills of the build containers. After some investigation, these seemed to be related to the amount of available memory on a GHA Runner as well as the overhead of trying to parallelize certain build steps.

You can see a successful build here: https://github.com/open-telemetry/opentelemetry-demo/actions/runs/3313405848

However, instead of reducing build time, we've dramatically increased it. There's a few reasons for this:

- Forcing 1x parallelism on Docker itself; turning this off results in OOM kills.
- Adding swap space to work around memory limitations of runners.
- Emulating arm64 on x86

In an attempt to work around this, I've discarded several solutions:

- Local caching doesn't help at all since runners are ephemeral.
- Remote caching (i.e., publish intermediate layers) would help but not durably since anytime there's a gRPC/OpenTelemetry update we'd have to do a full rebuild.
- It doesn't seem like it's possible to build different platforms on different machines then merge the manifests later, although it kinda seems like it should be possible. Either way, we only have access to x86 runners and at best this would halve the build time, still leaving us north of 2 hours.

My current train of thought is to see if it's possible to simply throw more resources at the problem. I've opened https://github.com/open-telemetry/community/issues/1281 to request larger runner support added to the organization. I suspect that if we could 2x or 3x our runner size, these problems would be mitigated.

**Comment by cartersocha** [comment]
What's the current state here @austinlparker ? I think the current build is just x86 right? Our performance is much better now

**Comment by cartersocha** [comment]
I think this has been solved in #536. Closing for now

**Comment by nlamirault** [comment]
Are you sure @cartersocha  Demo Docker images seems only amd64 : https://hub.docker.com/r/otel/demo/tags

**Comment by JaredTan95** [comment]
> Are you sure @cartersocha Demo Docker images seems only amd64 : https://hub.docker.com/r/otel/demo/tags

next tag will release multi-arch images.

**Comment by austinlparker** [comment]
Actually we had to remove multi-arch because it takes 4 hours to build. We're working on alternatives still to reduce build time and make this feasible.

**Comment by puckpuck** [comment]
The 1.3.1 release is multi-arch
