### ISSUE TITLE
Docker container metrics

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry-demo#459]
Explore setting up docker container metrics via otel receiver for 1.0

**Comment by austinlparker** [comment]
I've spent a bit of time investigating this and have run into a roadblock, so I'm going to write up my notes and hope someone else has an idea on a workaround.

Enabling `docker_stats` receiver is fairly straightforward, the defaults mostly work (adding `docker_stats:` to the receivers configuration in `./src/otelcollector/otelcol-config.yml` and then assigning it to the `metrics` pipeline), but the problems start when we try to actually map the docker daemon into the container.

Adding a new volume map for `/var/run/docker.sock:/var/run/docker.sock` to the compose file is easy, but you immediately get hit with permission denied errors from the collector when it tries to actually talk to the daemon. This is because the volume map preserves permissions and group affiliations from the host when it maps a volume, and the socket is owned by `root`:

```
lrwxr-xr-x  1 root  daemon  33 Oct 31 23:25 /var/run/docker.sock -> /Users/ap/.docker/run/docker.sock
```

I'm not quite sure what the best way to tackle this would be. Potentially, if we can get the collector process to run as `root` inside its container, then the uids would match and things would work? I've tried passing the `privileged` flag to the container as well with no luck.

**Comment by austinlparker** [comment]
Ok, figured out a workaround -- if you run the collector container as root, then it _does_ work. Do we _want_ to do that, though? Obviously it's not a "best practice" but I'm not sure there's another way to really get around it.

**Comment by austinlparker** [comment]
<img width="1817" alt="Screenshot 2022-11-02 at 3 11 50 PM" src="https://user-images.githubusercontent.com/4140740/199580455-895507c4-7352-4c3d-9936-29933fb1bf63.png">

Memory utilization with the cache leak turned on

**Comment by cartersocha** [comment]
@austinlparker Do we want to discuss this in a sig meeting or just factor it out of the requirements? It doesn't seem essential to me

**Comment by austinlparker** [comment]
We can discuss it I guess. If we're going to create infra dashboards then I think we'll need it.

**Comment by austinlparker** [comment]
Closing this as we won't target docker container metrics for infra telemetry
