### ISSUE TITLE
Review and enhance tracing support for frontend (Go) 

### ISSUE THREAD

**Issue by cartersocha** [open-telemetry/opentelemetry-demo#49]
The following is a list of requirements that we need to evaluate before declaring v1 for trace telemetry. These requirements are across the entire application; Not all services will meet all requirements. Determine the relevant features for this service. 

- [x] Automatic Instrumentation is being used where appropriate. - not appropriate
- [x] Library instrumentation is being used if automatic instrumentation is unavailable.
- [ ] Services extend automatic instrumentation.
  - [x] New attributes/events attached to existing spans.
  - [ ] New spans are being created from existing spans.
- [ ] Automatic and Manual Context Propagation are being demonstrated.
  - [x] Interprocess context propagation is demonstrated.
- [x] Telemetry is not being sampled upfront.
- [x] Telemetry is not being filtered upfront.
- [ ] Baggage is being set and read appropriately (i.e., baggage must be explicitly set as attributes on spans)

Referencing: https://github.com/open-telemetry/opentelemetry-demo-webstore/issues/42

Service: https://github.com/open-telemetry/opentelemetry-demo-webstore/tree/main/src/frontend

**Comment by fatsheep9146** [comment]
1. Automatic Instrumentation is being used where appropriate.

I think the project `frontend` meets this requirements. Since the two main libraries that project used are both instrumented appropriately. 

- `google.golang.org/grpc` 
- `github.com/gorilla/mux`

the instrumentation is initialized in following lines:

- https://github.com/open-telemetry/opentelemetry-demo-webstore/blob/a49f3b8f30e344c88978d09ea851230540981b3f/src/frontend/main.go#L129
- https://github.com/open-telemetry/opentelemetry-demo-webstore/blob/a49f3b8f30e344c88978d09ea851230540981b3f/src/frontend/main.go#L166-L170

**Comment by cartersocha** [comment]
I think that covers the instrumentation library requirement. Auto instrumentation is one of those words that means something different to everyone. 

In this case auto instrumentation is the agent / collector running in a sidecar right @austinlparker ?

**Comment by cartersocha** [comment]
@puckpuck could you check off the requirements you completed in your pr?

From a quick glance it seems like telemetry is not being sampled / filtered, custom attributes are being added to all spans, & library instrumentation is pre-existing. Did I miss anything & would we consider this interprocess context prop with the middleware attribute example too?

**Comment by puckpuck** [comment]
We can check off the following from the list.

* [ ]  Services extend automatic instrumentation.
  * [x]  New attributes/events attached to existing spans.
  * [ ]  New spans are being created from existing spans.
* [ ]  Automatic and Manual Context Propagation are being demonstrated.
  * [x]  Interprocess context propagation is demonstrated.
  * [ ]  Intraprocess context propagation is demonstrated.
