### ISSUE TITLE
Add tempo as second tracing backend

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-demo#503]
To demonstrate how to fan out data points to multiple destinations, it would be interesting to have a second distributed tracing backend in addition to Jaeger, such as Tempo.

**Comment by jpkrohling** [comment]
If this is interesting, please assign this to me, as I'm working on this for a private demo.

**Comment by cartersocha** [comment]
@jpkrohling we're doing some build optimization at the moment but definitely interested in adding an additional tracing backend. 

We've made some major improvements but after our next minor release we'll have a clear understanding of the improvement.

Feel free to work on this and open a pr but we'll wait to merge until the release

**Comment by cartersocha** [comment]
Please post about this in the slack channel. The sig may have opinions on which additional tracing back end we'd want to use. 

I'm not personally familiar with tempo but it seems interesting !

**Comment by austinlparker** [comment]
I want to spark a quick discussion here as we think about this going into v1.4 work -

Generally, we've restricted ourselves to only 'bundling' CNCF projects with this one (minus things like pg or kafka, which are functional vs. observability components). Including Tempo (or any other open source, but non-CNCF) projects would be a move away from this and open the door to requests from other open source projects with competing storage/search backends that we would then need to entertain and/or maintain.

_However_

I can see the benefit of keeping this repository as a 'hub' for common distributions or deployment patterns, especially when you get into the grey area of 'native' implementations on top of a given cloud or telemetry stack (i.e., AWS or Grafana stack).

I'll bring this up at the next SIG meeting, but it'd be good to have a bit of a discussion here along two lines:

1. Do we want to add support for additional telemetry back-ends as long as they're open source? Keep in mind, this wouldn't necessarily just be Tempo -- ClickHouse, traces-to-blob-storage, there's other things that'd fall into this.
2. If we do, how do we want to present those to end-users?

**Comment by jpkrohling** [comment]
To share my opinion: I'm fine either way. Having a clear scope certainly makes sense and Grafana Labs can showcase Tempo on its fork of the demo, just like the next vendor is doing. If the audience of this demo finds it easier to have a big repo with potentially hundreds of combinations for components, that's also fine by me and I'd commit (on behalf of Grafana Labs) to maintaining our components.

cc @cedricziel

**Comment by cartersocha** [comment]
Fan out may be considered at another date but the vendor forks are enough for now.
