### ISSUE TITLE
Frontend is not updating currency in product page and cart

### ISSUE THREAD

**Issue by julianocosta89** [open-telemetry/opentelemetry-demo#506]
# Bug Report

Which version of the demo you are using? d44100d0390a227475928e38239db8cc628215cc.

## Symptom

Frontend is not updating currency symbol and value in product page and cart.

**What is the expected behavior?**

What do you expect to see?
When selecting a currency, I expect the frontend to show me the symbols and values of the products in the selected currency.

**What is the actual behavior?**
Just landing page is updated, if we navigate to product page or cart, the products are shown with its dollar symbol and price.

## Reproduce

* Run the demo:
`docker compose up --no-build`
* Select a currency other than dollar
* Navigate to a product page (you will see the price in dollar)
* Add the product to the cart (the product will be added to the cart as a product in dollar, no matter what currency you have selected).

We will close this issue if:

* The steps you provided are complex.
* If we can not reproduce the behavior you're reporting.

## Additional Context

Homepage:
![Screenshot from 2022-10-20 22-56-15](https://user-images.githubusercontent.com/15364991/197056486-1573b8a3-0278-4add-8b03-eaa3616adf5d.png)

After selecting the product:
![Screenshot from 2022-10-20 22-56-58](https://user-images.githubusercontent.com/15364991/197056661-a2a295ff-8791-413b-9824-2ca0bf932124.png)

**Comment by austinlparker** [comment]
Closed by #522
