### ISSUE TITLE
Suggestion: change docker-compose to use published images

### ISSUE THREAD

**Issue by yurishkuro** [open-telemetry/opentelemetry-demo#542]
# Feature Request

I didn't find any issues with "publish" keyword, apologies if this is a dup.

As a way of making this demo more user-friendly, I recommend changing the top-level docker-compose file to load published Docker images instead of rebuilding the whole project. I suspect this whole thing can come up in a couple minutes, since the images are already published to registries (as far as I can tell from .github/workflows/release.yml).

**Comment by saurabhdes** [comment]
Yes, my understanding is that this is what is recommended to new users as per https://github.com/open-telemetry/opentelemetry-demo/blob/main/docs/docker_deployment.md#run-docker-compose 
And the whole app does startup in about 5 min if `docker compose up --no-build` is used.

**Comment by julianocosta89** [comment]
Hello @yurishkuro glad to have you here 🤩

As @saurabhdes mentioned when you use the `--no-build` flag you will be using the pushed images instead of rebuilding everything locally.

All suggestions are welcome, please let us know if anything else comes up!

**Comment by yurishkuro** [comment]
> https://github.com/open-telemetry/opentelemetry-demo/blob/main/docs/docker_deployment.md#run-docker-compose

How about having this in the top-level README? It's the first thing people will look for.

**Comment by julianocosta89** [comment]
I'll re-open this issue to get more insights from the rest of the team.

**Comment by austinlparker** [comment]
I think it's fine, although there's currently an issue with Apple Silicon and the published images; you need to build on that platform, otherwise one of the services fails to load.

**Comment by cartersocha** [comment]
This is covered in docker file and we link to the docker file in the quick start. 

We segmented out the docker info into a separate file to reduce main readme length. 

We’ll keep as is for now. Ideally once the apple silicon issue is solved we’ll have minimal onboarding issues
