### ISSUE TITLE
Add Kubernetes yaml for demo

### ISSUE THREAD

**Issue by yuxiaoba** [open-telemetry/opentelemetry-demo#545]
# Feature Request

This repository only offers a helm deployment option, I think a Kubernetes yaml deployment like [online Boutique](https://github.com/GoogleCloudPlatform/microservices-demo/tree/main/kubernetes-manifests) is also necessary )

**Comment by yuxiaoba** [comment]
If this is interesting, please assign this to me.

**Comment by cartersocha** [comment]
Hey @yuxiaoba this would be interesting. Open to exploring this. Just assigned to you

**Comment by puckpuck** [comment]
I wonder if we can automate this based on the Helm chart?

something like 
```
helm template opentelemetry-demo open-telemetry/opentelemetry-demo | sed '/helm.sh\/chart:/d' | sed '/helm.sh\/hook/d' | sed '/managed-by: Helm/d'
```

The sed commands would be used to remove the helm-specific annotations added to each resource.

**Comment by julianocosta89** [comment]
> I wonder if we can automate this based on the Helm chart?
> 
> something like
> 
> ```
> helm template opentelemetry-demo open-telemetry/opentelemetry-demo | sed '/helm.sh\/chart:/d' | sed '/helm.sh\/hook/d' | sed '/managed-by: Helm/d'
> ```
> 
> The sed commands would be used to remove the helm-specific annotations added to each resource.

+1 to that
