### ISSUE TITLE
[Frontend] Cart view not summing cents

### ISSUE THREAD

**Issue by julianocosta89** [open-telemetry/opentelemetry-demo#558]
# Bug Report

Which version of the demo you are using? 
[v1.0.0](https://github.com/open-telemetry/opentelemetry-demo/releases/tag/v1.0.0)

## Symptom

When navigating to the cart view, the total is not taking into account the cents part of the value.

**What is the expected behavior?**

I expected to see the total value.

## Reproduce

Start the sample following the docker approach, add a product to the cart, navigate to the cart view.

![Screenshot from 2022-11-05 15-31-05](https://user-images.githubusercontent.com/15364991/200125195-f533b8ec-caad-4b64-92fc-0c2f5bddeabc.png)

**Comment by julianocosta89** [comment]
@xoscar would you be able to take a look at this?

**Comment by julianocosta89** [comment]
Shipping costs are also not being updated whenever a new product is added to the cart, it is required to refresh the page manually to get the shipping costs recalculated.

**Comment by cartersocha** [comment]
Addressed in https://github.com/open-telemetry/opentelemetry-demo/pull/633
