### ISSUE TITLE
[frontend] some trace with unreasonable duration  

### ISSUE THREAD

**Issue by fatsheep9146** [open-telemetry/opentelemetry-demo#562]
# Bug Report

when I check of trace duration for product/[productID] page, some trace has unreasonable duration , such as 213503972d 16h

![image](https://user-images.githubusercontent.com/11855957/200503684-74d85c2d-31fc-4c92-a954-f2c505b1d32c.png)

Which version of the demo you are using? 
v1.0.0

## Symptom

**What is the expected behavior?**

the trace has reasonable duration

**What is the actual behavior?**

the trace has unreasonable duration, such as 213503972d 16h

## Reproduce

- docker compose up all service
- check the page http://127.0.0.1:8080/product/66VCHSJNUP
- search for the trace

**Comment by xoscar** [comment]
I was investigating this issue and found that this is a problem specifically with the @instrumentation-fetch package and Chrome. I found an issue opened against the [opentelemetry-js](https://github.com/open-telemetry/opentelemetry-js/issues/3355) main repo describing this same situation.

CC: @cartersocha

**Comment by austinlparker** [comment]
Closing as this should be addressed by updates to the JS SDK that came in in 1.3
