### ISSUE TITLE
Review and enhance tracing support for admin service (PHP)

### ISSUE THREAD

**Issue by cartersocha** [open-telemetry/opentelemetry-demo#57]
The following is a list of requirements that we need to evaluate before declaring v1 for trace telemetry. These requirements are across the entire application; Not all services will meet all requirements. Determine the relevant features for this service. 

- [ ] Automatic Instrumentation is being used where appropriate.
- [x] Library instrumentation is being used if automatic instrumentation is unavailable.
- [x] Services extend automatic instrumentation.
  - [x] New attributes/events attached to existing spans.
  - [x] New spans are being created from existing spans.
- [x] Automatic and Manual Context Propagation are being demonstrated.
  - [x] Interprocess context propagation is demonstrated.
- [x] Telemetry is not being sampled upfront.
- [x] Telemetry is not being filtered upfront.
- [ ] Baggage is being set and read appropriately (i.e., baggage must be explicitly set as attributes on spans)

Referencing: https://github.com/open-telemetry/opentelemetry-demo-webstore/issues/42

Dependent on this item: https://github.com/open-telemetry/opentelemetry-demo-webstore/issues/34

**Comment by cartersocha** [comment]
Tracing is code complete

**Comment by julianocosta89** [comment]
@cartersocha can we close this one?
The Admin service wasn't implemented but we have PHP as a Quote Service.
I've checked all that we have done in the Quote Service already.

Automatic Instrumentation is not available for PHP: https://github.com/open-telemetry/opentelemetry-php#auto-instrumentation

The only thing missing the Baggage, is that something we want to implement here?

**Comment by cartersocha** [comment]
@julianocosta89 i think we’re good for v1. I just closed out a bunch of the issues and gave you a quick heads up on slack. 
Baggage would be a nice to have but not essential imo

thanks for looking through these!
