### ISSUE TITLE
refactor out most grpc calls and switch to http

### ISSUE THREAD

**Issue by cartersocha** [open-telemetry/opentelemetry-demo#577]
Http is generally quicker to build and this would reflect real world practices more consistently

**Comment by Frapschen** [comment]
Can we use [grpc-gateway](https://github.com/grpc-ecosystem/grpc-gateway) to proxy the grpc API to http? It have two benefit:
1. support both grpc and http 
2. easy to set up http server.

**Comment by cartersocha** [comment]
Moot point with new build times
