### ISSUE TITLE
Add Juliano as a maintainer 

### ISSUE THREAD

**Issue by cartersocha** [open-telemetry/opentelemetry-demo#579]
I'd like to nominate @julianocosta89 to move from approver to maintainer.  

Juliano has been involved in the project from the beginning and has been a big development asset. He selected and helped donate the original demo app, wrote the PHP service example, added docker compose support, and a [myriad of other feature enhancements](https://github.com/open-telemetry/opentelemetry-demo/commits?author=julianocosta89). As an approver he also has completed a [huge amount of pr reviews](https://github.com/pulls?q=is%3Apr+commenter%3Ajulianocosta89+user%3Aopen-telemetry+) over the course of the project to ensure code quality and prompt contributor response. 

He would replace Morgan and we'd move Morgan to emeritus maintainer status.

**Comment by GaryPWhite** [comment]
+1 if as not-a-maintainer we're interested, Juliano has always been kind and willing to help me out. He's also not been afraid to admit what he doesn't know and _take_ help as needed to build a good demo!

**Comment by puckpuck** [comment]
+1 to this from me

**Comment by austinlparker** [comment]
+1 sgtm

**Comment by mviitane** [comment]
Nice!
