### ISSUE TITLE
Improve ENV_PLATFORM flag in UI

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry-demo#616]
<img width="224" alt="Screenshot 2022-12-07 at 10 02 26 AM" src="https://user-images.githubusercontent.com/4140740/206214008-74c20e3e-cff0-4a58-8de2-8d03c420b6bb.png">

This guy here.

It occludes parts of the UI, and I don't think it actually properly updates right now anyway? We should move this to some other part of the UI (maybe in the footer, idk) or just get rid of it entirely.

**Comment by julianocosta89** [comment]
This is populated by the environment variable `ENV_PLATFORM`.
I personally like it, for blue/green deployments it is actually nice to set different values and easily identify which env you are.

Welllll.... Now that I wrote it, not sure if it makes much sense in our scenario 😅

**Comment by puckpuck** [comment]
If we do keep this, it needs to be able to be set to any string, and not be bound to an enum.

**Comment by austinlparker** [comment]
To summarize, the work here is as follows:

- Move the flag so that it doesn't occlude other UI elements
- Allow an arbitrary short string to be passed in rather than selecting from an enum

**Comment by martinkuba** [comment]
Would bottom right corner of the footer work? Like this
<img width="500" alt="image" src="https://user-images.githubusercontent.com/4933147/228684619-aa871246-f766-4043-973e-0dd1b82c7d7f.png">

**Comment by julianocosta89** [comment]
Bottom right is fine to me
