### ISSUE TITLE
Review and enhance logging support for cart service (C#) 

### ISSUE THREAD

**Issue by cartersocha** [open-telemetry/opentelemetry-demo#62]
As OpenTelemetry Logging has not fully stabilized, this list of requirements may change in future releases.

- [ ] Log events in existing services should be converted to span events where appropriate (i.e., the event occurs within a transaction)
- [ ] Logs should be emitted with OpenTelemetry resources and context for correlation where possible.
- [ ] Logs should be scraped by OpenTelemetry Collectors for further filtering and processing.

Referencing issue: https://github.com/open-telemetry/opentelemetry-demo-webstore/issues/44

Service: Service: https://github.com/open-telemetry/opentelemetry-demo-webstore/tree/main/src/cartservice

**Comment by cijothomas** [comment]
I can help with this item.
To begin with, I can replace the Console.Write with `ILogger` calls., 
Then wire up OpenTelemetry with OTLP Exporter.
Then add resources.

Not sure about using SpanEvent vs using dedicated Logging API. Do we have a preference on one vs other?

**Comment by austinlparker** [comment]
Closing this as logs are being pushed out
