### ISSUE TITLE
Review and enhance logging support for recommendation service (Python)

### ISSUE THREAD

**Issue by cartersocha** [open-telemetry/opentelemetry-demo#63]
As OpenTelemetry Logging has not fully stabilized, this list of requirements may change in future releases.

- [ ] Log events in existing services should be converted to span events where appropriate (i.e., the event occurs within a transaction)
- [ ] Logs should be emitted with OpenTelemetry resources and context for correlation where possible.
- [ ] Logs should be scraped by OpenTelemetry Collectors for further filtering and processing.

Referencing issue: https://github.com/open-telemetry/opentelemetry-demo-webstore/issues/44

Service: https://github.com/open-telemetry/opentelemetry-demo-webstore/blob/main/src/recommendationservice/README.md

**Comment by austinlparker** [comment]
Closing as logs are being pushed out
