### ISSUE TITLE
helm chart supports more repo related to observability 

### ISSUE THREAD

**Issue by wph95** [open-telemetry/opentelemetry-demo#634]
now helm chart support 
- grafana [metric/dashboard]
- prometheus [metric]
- jaeger  [trace]

Based on the discussion in slack, we plan to add more support
- loki [log]
- Tempo [trace]

Pending options
- clickhouse [log/trace]

**Comment by puckpuck** [comment]
Can you add this to the [Helm Charts](https://github.com/open-telemetry/opentelemetry-helm-charts/issues) repo?

**Comment by austinlparker** [comment]
Closing this to move discussion to #503
