### ISSUE TITLE
Update copyright notices

### ISSUE THREAD

**Issue by puckpuck** [open-telemetry/opentelemetry-demo#637]
Update copyright notices on all code files to use the OpenTelemetry copyright header template.

- [ ] Update all services code files that do not have any copyright notices (several ancillary files do not have notices)
- [ ] Update original GCP notices to OpenTelemetry notices where the code file has been modified.
- [ ] Add attribution to GCP for the original efforts which led to the creation of this demo

**Comment by austinlparker** [comment]
See also #233
