### ISSUE TITLE
[quote] - auto-instrumentation produces more span than expected since #644

### ISSUE THREAD

**Issue by puckpuck** [open-telemetry/opentelemetry-demo#659]
# Bug Report

The quoteservice now produces 14 spans on each request. This used to be 2 spans before #644 was merged. Fixing this may require updates to the PHP SDK itself. 

Screenshot of a trace snippet with the quoteserivce involved showing 14 spans for a `GetQuote` request
![Screen Shot 2022-12-24 at 12 40 24 AM](https://user-images.githubusercontent.com/1296118/209423268-8cc43b2d-8300-441c-a27e-31dd337a67e9.png)

/cc @brettmc

**Comment by brettmc** [comment]
In progress, I've got it down to 3 spans which feels like a sane amount (remembering that it's being instrumented by a generalized auto-instrumentation for the framework that quoteservice uses, not specialized for the demo):

![Screenshot from 2023-01-10 16-15-38](https://user-images.githubusercontent.com/4978962/212768026-33d0f8f7-0d6b-4f38-9ed2-8813b7d8f833.png)
