### ISSUE TITLE
Review and enhance metric support for product catalog service (Go)

### ISSUE THREAD

**Issue by cartersocha** [open-telemetry/opentelemetry-demo#66]
The following are requirements for metrics in the project. Not all services will meet all requirements.

- [ ] Service metrics should not be duplicative of trace-derived metrics.
- [ ] Services should emit multiple business metrics where appropriate.
- [ ] Services should emit trace exemplars for their metrics.
- [ ] Services should use push metrics where possible.
- [ ] Services should explicitly read baggage where needed.
- [ ] Collectors should perform metric transforms to normalize resource and service metrics.

Referencing issue: https://github.com/open-telemetry/opentelemetry-demo-webstore/issues/43

**Comment by Frapschen** [comment]
@cartersocha I'm a little confuse, what metrics should we add to service? in my view, we can add some span metric by the otel-collector:
* calls_total
* latency_bucket

**Comment by cartersocha** [comment]
We haven’t had time to define our metric story yet. We are planning on discussing overall metric requirements in our next sig meeting. 

We’ll need to set up a consumption experience too. I’m guessing we’ll add grafana in a container or something similar. 

Feel free to open a pr with what metrics you think would be useful. Then we can use that to solicit feedback / input from everyone

**Comment by Frapschen** [comment]
The newest implementation instrumentation for the `runtime` package is in process, waiting for its finish.

**Comment by austinlparker** [comment]
Basic metrics have been added; closing issue.
