### ISSUE TITLE
Rust and C++ - Can we remove gRPC dependency on exporter?

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry-demo#679]
In Rust and C++, we have hard requirements on gRPC due to OTLP exporters even if we aren't using gRPC export. Can this be changed upstream?

**Comment by austinlparker** [comment]
https://github.com/open-telemetry/opentelemetry-cpp/issues/1826

This might fix the C++ issue

**Comment by svrnm** [comment]
For c++ the exporter is not the problem alone, as far as I see it: the service itself serves via gRPC, so also that needs to be refactored.

**Comment by styblope** [comment]
Same as above for Rust + [http exporter](https://github.com/open-telemetry/opentelemetry-rust/blob/c3b1056e0e947f1d0e44109dd401cdf3132bacd4/opentelemetry-otlp/src/lib.rs#L251) currently only supports traces, no metrics (in case we'd like to implement some)

**Comment by cartersocha** [comment]
Probably a moot point with build times reduced. Closing for now.
