### ISSUE TITLE
Optimize c++ currency service build time

### ISSUE THREAD

**Issue by cartersocha** [open-telemetry/opentelemetry-demo#681]
# Feature Request

The currency service build time is drastically slowing our release process and a general pain. 

Please help.

**Comment by svrnm** [comment]
I did a small experiment on improving the build time by using pre-existing libraries where possible, I have not yet tested it through all details, so I have not raised the PR, but I think this should help a little bit:

https://github.com/svrnm/opentelemetry-demo/tree/experimental-cpp-with-libs, see the Dockerfile:

https://github.com/svrnm/opentelemetry-demo/blame/experimental-cpp-with-libs/src/currencyservice/Dockerfile
