### ISSUE TITLE
Review and enhance metric support for cart service (C#)

### ISSUE THREAD

**Issue by cartersocha** [open-telemetry/opentelemetry-demo#71]
The following are requirements for metrics in the project. Not all services will meet all requirements.

- [ ] Service metrics should not be duplicative of trace-derived metrics.
- [ ] Services should emit multiple business metrics where appropriate.
- [ ] Services should emit trace exemplars for their metrics.
- [ ] Services should use push metrics where possible.
- [ ] Services should explicitly read baggage where needed.
- [ ] Collectors should perform metric transforms to normalize resource and service metrics.

Referencing issue: https://github.com/open-telemetry/opentelemetry-demo-webstore/issues/43

**Comment by austinlparker** [comment]
Closing as tracking issue no longer required
