### ISSUE TITLE
Update frontend metrics for auto-instrumentation when fixed

### ISSUE THREAD

**Issue by cartersocha** [open-telemetry/opentelemetry-demo#710]
When javaScript FS is fixed add auto instrumentation / re-enable it in the frontend

**Comment by cartersocha** [comment]
@pichlermarc / @martinkuba is there a timeline on this? I didn't see anything when glancing through the docs

**Comment by pichlermarc** [comment]
I think the PR was merged some time ago, https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1332. Another fix was merged today.

There's no release PR open yet AFAIK, I'll comment here once the PR is open. :slightly_smiling_face:

**Comment by pichlermarc** [comment]
The PR release PR is open (https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1396), once it is merged, the new auto instrumentation package should include the fix.
