### ISSUE TITLE
Enable the Feature Flags on k8s pod

### ISSUE THREAD

**Issue by PoojaGidaveer** [open-telemetry/opentelemetry-demo#728]
# Enable the Feature Flags on k8s pod

I want to try out this [FeatureFlags](https://github.com/open-telemetry/opentelemetry-demo/blob/main/docs/feature_flags.md) on the opentelementry k8s deployments. 

I am not able to edit this flags via UI- http://localhost:8081/

Below are the errors-
`07:01:21.767 request_id=Fz_v1FxmCaOu8bMAOPyh [info] GET /feature/assets/app-12403e086a772b88f325d7f94661e032.css
07:01:21.767 request_id=Fz_v1FxfyFcg4eMAOPxh [info] Sent 404 in 542µs
07:01:21.767 request_id=Fz_v1FxmCaOu8bMAOPyh [info] Sent 404 in 182µs
07:01:30.172 request_id=Fz_v1lFn1s5psCMAOPzh [info] GET /feature/featureflags/1/edit
07:01:30.173 request_id=Fz_v1lFn1s5psCMAOPzh [info] Sent 404 in 383µs
07:01:38.202 request_id=Fz_v2DABIQJWiHUAOP0h [info] GET /feature/featureflags/2/edit
07:01:38.202 request_id=Fz_v2DABIQJWiHUAOP0h [info] Sent 404 in 265µs`

Can you please let me know if there is a way on how to enable these flags ?

**Comment by julianocosta89** [comment]
Hello @PoojaGidaveer , which version of the demo are you running?

The `FeatureFlag` service has moved out from `8081` for some time already, maybe you are using an old version?
Could you try the latest release?

Feature Flag Service should be available at: `http://localhost:8080/feature/`

**Comment by PoojaGidaveer** [comment]
@julianocosta89  i am using - ghcr.io/open-telemetry/demo:v1.2.1-featureflagservice deployed via helm charts..
Can you please let me know the latest version?

**Comment by julianocosta89** [comment]
`1.3.0` was released a couple of days ago.
`helm repo update` should do the tricky.

**Comment by PoojaGidaveer** [comment]
i tried with 1.3.0 but still same error...

**Comment by puckpuck** [comment]
The featureflag service is now exposed via the `frontendProxy`.  Forward that port (8080), and access the UI at this URL [http://localhost:8080/feature/](http://localhost:8080/feature/)

More info with the [kubernetes docs](https://github.com/open-telemetry/opentelemetry-demo/blob/main/docs/kubernetes_deployment.md) for the demo.

**Comment by PoojaGidaveer** [comment]
Thanks @puckpuck ...
