### ISSUE TITLE
Does this demo application support for Mac M1? 

### ISSUE THREAD

**Issue by rkdutta** [open-telemetry/opentelemetry-demo#739]
# Question

I am using a kind kubernetes cluster running on my mac laptop. And I am facing issue :: "No Matching Manifest for Linux/Arm64/V8" when downloading the application images within the cluster (for example: accountingservice). 

Does the current release support mac m1? Can you suggest a solution? 

## Kind configuration

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.26.0
  - role: worker
    image: kindest/node:v1.26.0

```

## Mac Configuration
<img width="513" alt="image" src="https://user-images.githubusercontent.com/49343621/217912768-6ca1c5b1-be15-46a5-9d8c-fd20a501da4e.png">

## Error Event

```
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  4m24s                  default-scheduler  Successfully assigned default/hipster-shop-accountingservice-549548c4df-vvj5c to sre-demo-site-worker
  Normal   Pulling    2m38s (x4 over 4m21s)  kubelet            Pulling image "ghcr.io/open-telemetry/demo:1.3.0-accountingservice"
  Warning  Failed     2m37s (x4 over 4m14s)  kubelet            Failed to pull image "ghcr.io/open-telemetry/demo:1.3.0-accountingservice": rpc error: code = NotFound desc = failed to pull and unpack image "ghcr.io/open-telemetry/demo:1.3.0-accountingservice": no match for platform in manifest: not found
  Warning  Failed     2m37s (x4 over 4m14s)  kubelet            Error: ErrImagePull
  Warning  Failed     2m9s (x6 over 4m14s)   kubelet            Error: ImagePullBackOff
  Normal   BackOff    118s (x7 over 4m14s)   kubelet            Back-off pulling image "ghcr.io/open-telemetry/demo:1.3.0-accountingservice"
```

**Comment by codeboten** [comment]
I just ran the app w/ `docker compose up` and it worked, not sure if that helps your case or not. I haven't tried w/ kind yet.

**Comment by rkdutta** [comment]
> I just ran the app w/ `docker compose up` and it worked, not sure if that helps your case or not. I haven't tried w/ kind yet.

I didn't try docker compose up. I was always running with kind. And it was working until the latest release.

**Comment by codeboten** [comment]
Ah i see, I misread the question and didn't know previous versions had worked w/ kind. I thought it was a more broad question whether the demo app works on m1 at all :)

**Comment by rkdutta** [comment]
> Ah i see, I misread the question and didn't know previous versions had worked w/ kind. I thought it was a more broad question whether the demo app works on m1 at all :)

I would agree with you.

**Comment by j-sulliman** [comment]
This is from an M2 Mac:



```
kubectl describe pods my-otel-demo-accountingservice-866b6d88c5-x2t9d 

Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  2m59s                default-scheduler  Successfully assigned default/my-otel-demo-accountingservice-866b6d88c5-x2t9d to minikube
  Normal   Pulling    51s (x4 over 2m56s)  kubelet            Pulling image "ghcr.io/open-telemetry/demo:1.3.0-accountingservice"
  Warning  Failed     43s (x4 over 2m42s)  kubelet            Failed to pull image "ghcr.io/open-telemetry/demo:1.3.0-accountingservice": rpc error: code = Unknown desc = **_no matching manifest for linux/arm64/v8 in the manifest list entries_**
  Warning  Failed     43s (x4 over 2m42s)  kubelet            Error: ErrImagePull
  Warning  Failed     18s (x6 over 2m42s)  kubelet            Error: ImagePullBackOff
  Normal   BackOff    6s (x7 over 2m42s)   kubelet            Back-off pulling image "ghcr.io/open-telemetry/demo:1.3.0-accountingservice"
```

And 

```kubectl describe pods my-otel-demo-adservice-5776c69577-79f76

Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  6m42s                  default-scheduler  Successfully assigned default/my-otel-demo-adservice-5776c69577-79f76 to minikube
  Normal   Pulling    4m14s (x4 over 6m37s)  kubelet            Pulling image "ghcr.io/open-telemetry/demo:1.3.0-adservice"
  Warning  Failed     3m58s (x4 over 6m12s)  kubelet            Failed to pull image "ghcr.io/open-telemetry/demo:1.3.0-adservice": rpc error: code = Unknown desc = **_no matching manifest for linux/arm64/v8 in the manifest list entries_**
  Warning  Failed     3m58s (x4 over 6m12s)  kubelet            Error: ErrImagePull
  Warning  Failed     3m47s (x6 over 6m11s)  kubelet            Error: ImagePullBackOff
  Normal   BackOff    93s (x15 over 6m11s)   kubelet            Back-off pulling image "ghcr.io/open-telemetry/demo:1.3.0-adservice"
```

A search on "no matching manifest for linux/arm64/v8 in the manifest list entries" takes me here: https://stackoverflow.com/questions/65456814/docker-apple-silicon-m1-preview-mysql-no-matching-manifest-for-linux-arm64-v8  

Unsure if there's an equivalent "platform" parameter for helm charts the could fix this?

PS: the docker version / compose file of Otel-demo works fine for me on an M2 also.  Issue is with helm charts.

**Comment by mviitane** [comment]
As a workaround for M1 and M2 users using Kubernetes, you can build v1.3.0 demo images locally
`docker compose build —no-cache`
(use `—no-cache` to be sure you get all images built with the 1.3.0 version tag)

The helm chart has
`imagePullPolicy: IfNotPresent`
(the images are pulled only if not present locally)

After the build, you can use helm normally to deploy the app, using the locally built images:
`helm install my-otel-demo open-telemetry/opentelemetry-demo`

Tested on M1 with Docker Desktop Kubernetes.

**Comment by rkdutta** [comment]
There is a way to transport locally build images using ```docker compose build``` to kind kubernetes clusters.
The command in kind looks like this:
```
kind load docker-image  <image>
```
e.g.
```
kind load docker-image  ghcr.io/open-telemetry/demo:1.3.0-shippingservice
```
Tested on M1 with kind clusters.

**Comment by puckpuck** [comment]
I would like to post and document how I got the demo to work on my M2 mac with Kind.

Build the images locally
`docker compose build --no-cache`

Load all the locally built demo images into kind (this may take several minutes with no output that it is working)
`kind load docker-image $(docker images ghcr.io/open-telemetry/demo --format "{{.Repository}}:{{.Tag}}")`

Install the demo using Helm
`helm install otel-demo open-telemetry/opentelemetry-demo`

For the 1.4 release we should have ARM images available, negating the need to do these steps, but until then, this is a workaround we can use.

**Comment by puckpuck** [comment]
The 1.3.1 release of the demo, generated ARM images, and the accompanying Helm chart allows it to be installed in a local K8s cluster running on an M1/M2 mac.
