### ISSUE TITLE
README: add OTel logo back

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry-demo#742]
_Originally posted by @chalin in https://github.com/open-telemetry/opentelemetry-demo/issues/730#issuecomment-1419299765_

>> We should keep the otel image for the main readme but maybe just create another folder. Otherwise lgtm
>
> @cartersocha - would it be ok to address this separately? (We have at least two options, the details of which I'd rather discuss in the context of a followup PR or issue.)

**Comment by cartersocha** [comment]
❤️

**Comment by chalin** [comment]
@cartersocha - given the points made below the main question is: how important is it for repo maintainers to have the OTel logo in the repo's README file?

1. The simplest option is to go without a logo in the README title (level 1 heading). Some of the repos in the OTel org have opted for this.

2. Another option is to get the **official logo** from the website. This is what is done in the READMEs of, for example, the:

    - Website repo
    - Spec repo, and
    - community repo
    E.g., https://github.com/open-telemetry/community/blob/main/README.md?plain=1

          # <img src="https://opentelemetry.io/img/logos/opentelemetry-logo-nav.png" alt="OpenTelemetry Icon" width="45" height=""> OpenTelemetry community content

    If y'all want a logo, this would be my preferred solution so that we don't end up having multiple copies of the logo file across repos.

    The problem here is that `markdownlint`, with it's current settings, won't allow it:

    ```console
    $ make markdownlint
    opentelemetry-demo@ /Users/chalin/git/lf/open-telemetry/opentelemetry-demo
    └─┬ markdownlint-cli@0.31.0
      └── markdownlint@0.25.1
    
    ./CHANGELOG.md
    ./CONTRIBUTING.md
    ./README.md
    ./README.md:1:81 MD013/line-length Line length [Expected: 80; Actual: 140]
    ./README.md:1:3 MD033/no-inline-html Inline HTML [Element: img]
    make: *** [markdownlint] Error 1
    ```

    In the website repo we use Prettifier to enforce formatting (including constraints on line length, which sometimes needs to be more than 80 char), and we don't prevent embedded HTML, for obvious reasons.

WDYT? Any preferences, or other suggestions?

**Comment by chalin** [comment]
I can think of other options, such as having Hugo automatically generate a logo of reduced file size that other repos could then refer to. I know it's possible, but I haven't used that feature yet. Other work is more pressing at the moment, so I might not get time to explore such an option until later. (FYI)

**Comment by cartersocha** [comment]
I'd personally be okay with option 2

**Comment by cartersocha** [comment]
@austinlparker I'm not familiar with our markdownlint checker - can we configure it to ignore html / where?

**Comment by cartersocha** [comment]
A file that could be used across repos would be quite nice. I originally added an image here because I saw another repo with it and liked the vibe. I know it's a small addition but I do feel like small details like this improve the perception of the project / repo.

**Comment by chalin** [comment]
> I'd personally be okay with option 2

Done. It occurred to me that we should be able to disable the lint checker for that one line. See #744.
