### ISSUE TITLE
v1.3.0 demo images breaks M1 support that existed with v1.2.1 images

### ISSUE THREAD

**Issue by eskirk** [open-telemetry/opentelemetry-demo#745]
I have been working with the OTel demo helm chart on 0.15.3 (1.2.1 images) on my M1 mac. Today we upgraded to 0.18.0 (1.3.0 images) and I am no longer able to pull/run any of the images. 

Previously using 1.2.1 images, I had a couple services (featureflag, checkoutservice, ...) that were unable to run, but now almost all of the services fail to pull the images. 

I understand that there is ongoing work to provide full support for arm64 builds, but I find it strange that an upgrade like this would totally break support. 

When looking through tags, it seems like all the [1.3.0 images](https://github.com/open-telemetry/opentelemetry-demo/pkgs/container/demo/66998931?tag=1.3.0-shippingservice) have an OS/Arch tab - but the second architecture is listed as `unknown/unknown`. I am unable to `docker pull ...` either of these images on my M1.  
![image](https://user-images.githubusercontent.com/7052378/217919255-afe96d7f-b580-493e-be81-32e594423204.png)

On the other hand, none of the [1.2.1 images](https://github.com/open-telemetry/opentelemetry-demo/pkgs/container/demo/58058209?tag=v1.2.1-shippingservice) have a second tab for a different architecture, but I am able to pull and run almost all of them. 
![image](https://user-images.githubusercontent.com/7052378/217919536-a93d9ef3-9561-4720-b8b1-3c54c8875191.png)

I am hoping this fix should be as simple as updating a config in the image build process, but wanted to bring this to the teams attention if this was not expected behavior.

**Comment by puckpuck** [comment]
I finally put a request in for an M2 Mac with my org. I expect to have it next week. 

Part of our 1.4 release for the demo is to ensure we have a smooth developer experience with `docker compose up` docker compose build` and `helm install ...` to a local K8s cluster running on ARM.

**Comment by puckpuck** [comment]
The latest demo release 1.3.1 and Helm chart now support multiple architectures (amd64 & arm64). No more workarounds are needed.
