### ISSUE TITLE
Frontend span attribute `app.session.id` gone

### ISSUE THREAD

**Issue by julianocosta89** [open-telemetry/opentelemetry-demo#758]
# Bug Report

Which version of the demo you are using? (please provide either a specific
603af3652b6bcfd383c6b61e73ca5302f7289253

## Symptom

It seems that the span attribute `app.session.id` is not available anymore in the demo.

**What is the expected behavior?**

Either update the [docs](https://opentelemetry.io/docs/demo/manual-span-attributes/#frontend) to remove the `app.session.id` from the list of custom attributes, or ideally, add the span attribute back.

**Comment by disfluxly** [comment]
I'd definitely prefer that it be added back instead of removing it from the docs, since the Session ID is displayed on the bottom of the GUI pages. Made it really easy to walk someone through a demo and see all of the traces they made.
