### ISSUE TITLE
Error "no matching manifest for linux/arm64/v8 in the manifest list entries"

### ISSUE THREAD

**Issue by cchoygithub** [open-telemetry/opentelemetry-demo#768]
Hi I'm getting error "no matching manifest for linux/arm64/v8 in the manifest list entries" when tried to spin up the image from my MacBook Pro M1. Sounds like the repo is not built for the architecture, wondering if there's an images that are built for the ARM64 architecture?

**Comment by rkdutta** [comment]
#739
