### ISSUE TITLE
Long Term Testing: Memory Leaks

### ISSUE THREAD

**Issue by puckpuck** [open-telemetry/opentelemetry-demo#771]
After running a 4-week test on a stable EKS cluster using m6i.large nodes I have found the following services to be experiencing memory leaks:
- [ ] `emailservice` (severe)
- [ ] `loadgenerator` (moderate)
- [x] `redis` (moderate)

This chart shows the 3 services' memory consumption and pod restarts over 3 weeks
![Screenshot 2023-03-06 at 9 47 32 PM](https://user-images.githubusercontent.com/1296118/223307442-0e33bbb9-1b77-49bf-96fd-bd48e7989a36.png)

[This PR](https://github.com/protocolbuffers/protobuf/issues/10106) seems to be related to the `emailservice` though I'm unclear on it.
The `redis` leak is likey attributed to a lack of TTL when the `cartservice` is adding items to the cart
The `loadgenerator` may need further investigation to understand how and why the leak is being caused.

I have also found the `frauddetectionservice` to be experiencing a mild leak, though the service has not restarted after 4 weeks of running. I don't think we need to take any action on this at this point, but wanted to report it just in case.
![Screenshot 2023-03-06 at 9 48 18 PM](https://user-images.githubusercontent.com/1296118/223307461-9300472d-ae2f-4c44-8074-9c9b785e118b.png)

**Comment by cartersocha** [comment]
Would basic [garbage collection](https://docs.python.org/3/library/gc.html) potentially help the loadgenerator?

**Comment by austinlparker** [comment]
Closing this as part of issue cleanup. If there's anything that needs to be done, please create a new issue.
