### ISSUE TITLE
Update .NET SDK to fix metric description

### ISSUE THREAD

**Issue by puckpuck** [open-telemetry/opentelemetry-demo#774]
The .NET SDK had a bug with a schema defined metric description being incorrect. When [this PR](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1063) is released, we need to update the `cartservice` SDK dependencies and revert #738 which added a transform processor to the collector to temporarily prevent an  error condition.

**Comment by julianocosta89** [comment]
duplicated: https://github.com/open-telemetry/opentelemetry-demo/issues/737
