### ISSUE TITLE
[shipping] reqwest spans taking a long duration

### ISSUE THREAD

**Issue by puckpuck** [open-telemetry/opentelemetry-demo#775]
The `reqwest` spans part of the `shippingservice` take magnitudes longer duration than all other spans in a typical transaction that requires the shipping service
![Screenshot 2023-03-06 at 9 48 18 PM](https://user-images.githubusercontent.com/1296118/223314967-bf165caf-b81e-4f84-b3f6-65ee72c1fca3.png)

This seems to be related to #610, when `reqwest` with instrumentation was added, and #622 which also made changes to that instrumentation. 

I expect HTTP requests from Rust to take microseconds, similar (or better) than other similar requests in the other languages in the demo.

**Comment by styblope** [comment]
Look to me the problem is the other side, at quoteservice:
```
root@shippinservice/# ./hey -m POST -c 1 -n 100 -d '{"numberOfItems":"5"}' http://quoteservice:8090/getquote

Summary:
  Total:        44.0418 secs
  Slowest:      0.6043 secs
  Fastest:      0.3200 secs
  Average:      0.4404 secs
  Requests/sec: 2.2706

  Total data:   400 bytes
  Size/request: 4 bytes

Response time histogram:
  0.320 [1]     |■■
  0.348 [4]     |■■■■■■■■
  0.377 [8]     |■■■■■■■■■■■■■■■
  0.405 [16]    |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.434 [21]    |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.462 [15]    |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.491 [14]    |■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.519 [15]    |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.547 [2]     |■■■■
  0.576 [0]     |
  0.604 [4]     |■■■■■■■■

Status code distribution:
  [200] 100 responses
```
Similar stats are when tested from load-generator service.

**Comment by brettmc** [comment]
That's interesting. I see it locally, too. The traces themselves are reportedly quite fast (< 1ms, which I would expect), but the actual http request/response is painfully slow.
I do know that the runtime in use (apache + mod_php) does not complete & return the response until all processing has completed, and in this case that includes sending the telemetry data to the collector. I think that's the most likely cause, I'll do some debugging on it.

**Comment by styblope** [comment]
adding a sample xdebug profile if that helps
[cachegrind.out.zip](https://github.com/open-telemetry/opentelemetry-demo/files/10977227/cachegrind.out.zip)

**Comment by styblope** [comment]
Thanks @brettmc,  is the apache + mod_php combo technically prohibiting sending the telemetry data after the request is finished? Did a tcpdump test to believe ;)
![image](https://user-images.githubusercontent.com/1809272/225298881-555877bd-c632-4fe8-9c43-bfec08f15633.png)

**Comment by brettmc** [comment]
My recollection (from a production outage caused by almost exactly this, with a different APM tool), is that the response to the user is not closed until _all_ PHP processing is complete, which includes shutdown functions (which is where otel-php shuts down processors etc, and tries to export any un-exported data).
So I don't think it prohibits the sending of telemetry data, but rather delays the completion of the main response until telemetry data is done.

Most other PHP runtimes handle this much better, eg [fastcgi](https://www.php.net/manual/en/function.fastcgi-finish-request.php) and the more modern async runtimes.
