### ISSUE TITLE
Incorrect types for Span in the FrontendTracer.ts file

### ISSUE THREAD

**Issue by elliotgonzalez-lk** [open-telemetry/opentelemetry-demo#792]
# Bug Report

Latest version 1.3.1

## Symptom

The following Typescript error pops up when trying to instantiate the spanProcessor.  Line 52 in the demo. 

I've tracked the error down to there being TWO different Types specified for the type `Span`.  The imports for this type specified in `node_modules/@opentelemetry/sdk-trace-web/node_modules/@opentelemetry/sdk-trace-base/build/src/SpanProcessor.d.ts` are different than than the imported `Span` type in `SimpleSpanProcessor` found in `node_modules/@opentelemetry/sdk-trace-base/build/src/export/SimpleSpanProcessor.d.ts`.  Fixing the import  of `Span` inside of `SimpleSpanProcessor` to match the `SpanProcessor` `Span` type fixes the TS error.

```typescript
provider.addSpanProcessor(
    new SimpleSpanProcessor(
      new OTLPTraceExporter({
        url:
          NEXT_PUBLIC_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT ||
          collectorString ||
          "http://localhost:4318/v1/traces",
      })
    )
  );
```
Error:

```
./utils/telemetry/FrontendTracer.ts:41:5

Type error: Argument of type 'SimpleSpanProcessor' is not assignable to parameter of type 'SpanProcessor'.

  Types of property 'onStart' are incompatible.

    Type '(_span: Span, _parentContext: Context) => void' is not assignable to type '(span: Span, parentContext: Context) => void'.

      Types of parameters '_span' and 'span' are incompatible.

        Type 'import("/app/node_modules/@opentelemetry/sdk-trace-web/node_modules/@opentelemetry/sdk-trace-base/build/src/Span").Span' is not assignable to type 'import("/app/node_modules/@opentelemetry/sdk-trace-base/build/src/Span").Span'.

          Types have separate declarations of a private property '_spanContext'.
```

**What is the expected behavior?**

The expected behavior is no TS errors when using the demo code.

## Reproduce

Pull the demo down and install the dependencies that are required for `FrontendTracer.ts`

**Comment by martinkuba** [comment]
@elliotgonzalez-lk I am not able to reproduce this. Are you still seeing this? What version of node and npm are you using?

**Comment by elliotgonzalez-lk** [comment]
Thank you for checking.  It looks like it was a dependency issue on my end.  I'll close this issue now.
