### ISSUE TITLE
otelcol port forward  failed

### ISSUE THREAD

**Issue by taoweibang** [open-telemetry/opentelemetry-demo#794]
# Bug Report

## Which version of the demo you are using? 
helm opentelemetry-demo-0.19.6	1.3.1

## Symptom
failed to expose the OpenTelemetry Collector’s OTLP/HTTP port,
if  connect to collector port,  show error like below

curl http://127.0.0.1:4318/v1/traces
curl: (52) Empty reply from server

[root@otelpoc opentelemetry-demo]# kubectl port-forward svc/my-otel-demo-otelcol 4318:4318
Forwarding from 127.0.0.1:4318 -> 4318
Forwarding from [::1]:4318 -> 4318
Handling connection for 4318
E0315 11:46:28.277273  490637 portforward.go:407] an error occurred forwarding 4318 -> 4318: error forwarding port 4318 to pod 65d7d2b35b21b2369e09d3f2e48003bf92d123a358284c69b0957359182542fa, uid : failed to execute portforward in network namespace "/var/run/netns/cni-72a2ea46-c58b-97bd-2595-2fe58c4ba98c": failed to connect to localhost:4318 inside namespace "65d7d2b35b21b2369e09d3f2e48003bf92d123a358284c69b0957359182542fa", IPv4: dial tcp4 127.0.0.1:4318: connect: connection refused IPv6 dial tcp6 [::1]:4318: connect: connection refused 
E0315 11:46:28.277871  490637 portforward.go:233] lost connection to pod

## Additional Context

Try with K3s(v1.25.7) and kind, got same error

there's no problem on frontendproxy port forward, it works perfect.
kubectl port-forward svc/my-otel-demo-frontendproxy 8080:8080

**Comment by puckpuck** [comment]
This might be related to security issues with the collector and no more binding to 0.0.0.0.

This [PR](https://github.com/open-telemetry/opentelemetry-helm-charts/pull/603) forces the collector to use the POD IP now. There is a discussion in the PR about port-forwarding breaking.

This [PR](https://github.com/open-telemetry/opentelemetry-helm-charts/pull/724) hints at how to get around it by forcing the collector to bind to 127.0.0.1 instead

However, I'm more intrigued by using NetworkPolicy instead (not sure it will work for what we need), which will get merged with this [PR](https://github.com/open-telemetry/opentelemetry-helm-charts/pull/723)
