### ISSUE TITLE
Elastic's fork of the opentelemetry demo needs to be listed

### ISSUE THREAD

**Issue by bshetti** [open-telemetry/opentelemetry-demo#811]
# Feature Request

We would like to have Elastic's fork of the opentelemetry demo https://github.com/elastic/opentelemetry-demo listed on the READ.ME - do we just modify the readme and do a PR?

Before opening a feature request against this repo, consider whether the feature
should/could be implemented in the [other OpenTelemetry client
libraries](https://github.com/open-telemetry/). If so, please [open an issue on
opentelemetry-specification](https://github.com/open-telemetry/opentelemetry-specification/issues/new)
first.

**Is your feature request related to a problem?**

no

If so, provide a concise description of the problem.

**Describe the solution you'd like:**

What do you want to happen instead? What is the expected behavior?

We would like to have Elastic's fork of the opentelemetry demo https://github.com/elastic/opentelemetry-demo listed on the READ.ME - do we just modify the readme and do a PR?

**Describe alternatives you've considered.**

Which alternative solutions or features have you considered?

## Additional Context

Add any other context about the feature request here.

**Comment by julianocosta89** [comment]
Hello @bshetti 👋🏽 

Yes, just send us a PR adding it to the list.
Just one note, the list is following alphabetical order.

**Comment by bshetti** [comment]
@julianocosta89 I put in the PR https://github.com/open-telemetry/opentelemetry-demo/pull/813 
Hope it looks ok. Please accept.

**Comment by julianocosta89** [comment]
@bshetti you need to sign the CLA.
Otherwise we can't accept your PR.
