### ISSUE TITLE
`docker compose up` downloads images instead of building it locally

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-demo#838]
# Bug Report

Which version of the demo you are using? (please provide either a specific
[commit
hash](https://github.com/open-telemetry/opentelemetry-demo/commits/main)
or a specific
[release](https://github.com/open-telemetry/opentelemetry-demo/releases)).

02837fe7b71dd3b85db0efb253a97a693b5d5e3a

## Symptom

**What is the expected behavior?**

Either `docker compose up` should build all local images or https://opentelemetry.io/docs/demo/docker-deployment/#get-and-run-the-demo is fixed.

**What is the actual behavior?**

`docker compose up` downloads images.

## Reproduce

Checkout current main (02837fe7b71dd3b85db0efb253a97a693b5d5e3a).
Execute `docker compose up`

## Additional Context

Tested on Windows 10 with Docker with Linux containers.

**Comment by puckpuck** [comment]
The docs around all of this have changed, and the instructions have changed on how to contribute for the demo. Closing this.
