### ISSUE TITLE
add middleware and database in demo

### ISSUE THREAD

**Issue by wajika** [open-telemetry/opentelemetry-demo#84]
I want to see how the span header issues traceid through kafka redis.

**Comment by cartersocha** [comment]
We have plans to add database components for the PHP admin service, the product catalog, & feature flag service. There's also a redis cache already present. 
https://github.com/open-telemetry/opentelemetry-demo-webstore/blob/main/docs/v1Graph.md

Is this an ask to have a queue between the database & the services?

**Comment by wajika** [comment]
My purpose is that the whole path can be recognized, I am testing whether the backend can record the complete topology and display it.
[learn about this](https://discuss.elastic.co/t/how-to-grab-kafka-traceparent-and-tracestate-headers/302982/2)
probably so: service > kafka > service > database

**Comment by austinlparker** [comment]
Closed by #429
