### ISSUE TITLE
Failed to export traces for recommendation-service with StatusCode.UNAUTHENTICATED

### ISSUE THREAD

**Issue by harrykimpel** [open-telemetry/opentelemetry-demo#842]
# Bug Report

Which version of the demo you are using? (please provide either a specific
[2314b48](https://github.com/open-telemetry/opentelemetry-demo/commits/main)

## Symptom

In the log I see that the recommendation-service is reporting an issue when it comes to sending its telemetry to the otel collector backend. the error message is:

recommendation-service   | 2023-04-13 19:26:46,341 ERROR [opentelemetry.exporter.otlp.proto.grpc.exporter] [exporter.py:368] [trace_id=0 span_id=0 resource.service.name=recommendationservice] - Failed to export traces, error code: StatusCode.UNAUTHENTICATED

All other services are working fine.

**What is the expected behavior?**
recommendation-service sends telemetry to otel collector backend

What do you expect to see?

recommendation-service sends telemetry to otel collector backend

**What is the actual behavior?**

What did you see instead?

the above error message

## Reproduce

Provide the minimum required steps to result in the issue you're observing.

We will close this issue if:

* The steps you provided are complex.
* If we can not reproduce the behavior you're reporting.

**Comment by puckpuck** [comment]
Do you still see this issue with 1.5 (latest release)?

**Comment by harrykimpel** [comment]
> Do you still see this issue with 1.5 (latest release)?

let me check @puckpuck and get back to you

**Comment by harrykimpel** [comment]
> > Do you still see this issue with 1.5 (latest release)?
> 
> let me check @puckpuck and get back to you

still seems to happen @puckpuck

**Comment by puckpuck** [comment]
Does this happen at startup only, or continuously well after the demo has been started?

**Comment by harrykimpel** [comment]
> Does this happen at startup only, or continuously well after the demo has been started?

I am pretty sure this happens continuously

**Comment by puckpuck** [comment]
Can you share the full command you are using the start the demo?

**Comment by harrykimpel** [comment]
> Can you share the full command you are using the start the demo?

this is the command I am using:
`helm install my-otel-demo open-telemetry/opentelemetry-demo --values my-values-file.yaml`

the content of the my-values-file.yaml looks like this:
`components:
  frontendProxy:
    service:
      type: LoadBalancer
  frontend:
    resources:
      limits:
        memory: 400Mi

opentelemetry-collector:
  config:
    exporters:
      otlphttp/newrelic:
        endpoint: https://otlp.nr-data.net:4317
        headers:
          api-key: NEW_RELIC_LICENSE_KEY

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/newrelic]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/newrelic]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/newrelic]`

**Comment by julianocosta89** [comment]
Any chance your `api-key` has a space on it?

In Dynatrace, we got an issue that for Python we needed to change the `Api-Token` from:
- `Api-Token dt01.123.4567`

to:
- `Api-Token%20dt01.123.4567`


And we added the following into our docs:

> URL encoding in environment variables
> 
> Please note that the space in OTEL_EXPORTER_OTLP_HEADERS is encoded as %20 as the variable [follows the correlation context convention﻿](https://opentelemetry.io/docs/specs/otel/protocol/exporter/#specifying-headers-via-environment-variables) and its [value needs to be percent-encoded﻿](https://github.com/w3c/baggage/blob/main/baggage/HTTP_HEADER_FORMAT.md#value).

**Comment by harrykimpel** [comment]
I updated to the latest version of the demo and do not see this error anymore.
