### ISSUE TITLE
Currency Service not emitting metrics in k8s

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry-demo#846]
Trace export seems to be working, but seeing a lot of this in the logs --

```2023-04-16T18:36:36.278175487Z stdout F [Error] File: /opentelemetry-cpp/exporters/otlp/src/otlp_grpc_metric_exporter.cc:74 [OTLP METRIC GRPC Exporter] Export() failed: DNS resolution failed for otelcol:4317: C-ares status is not ARES_SUCCESS qtype=A name=otelcol is_balancer=0: Domain name not found```

**Comment by kaechele** [comment]
Configuration of the OLTP endpoint via environment variables is not yet supported: https://github.com/open-telemetry/opentelemetry-demo/blob/5ef82f3dbd7eca51cd439bc0fd6b14be7abde3bc/src/currencyservice/src/meter_common.h#L28-L29

So as of now it's hardcoded to `otelcol:4317`.

**Comment by puckpuck** [comment]
This has been resolved in the currency service with #904
