### ISSUE TITLE
Changes to Dockerfile(s) not considered during deployment

### ISSUE THREAD

**Issue by kainawroth** [open-telemetry/opentelemetry-demo#876]
Hi everyone,

I forked the OTel Demo repo to experiment with different instrumentations and exporters, but I'm struggling with getting my modified version deployed.

**Example**
 I made changes to the Ad Service Dockerfile to replace the OTel Java agent with the Application Insights version:
 
![image](https://user-images.githubusercontent.com/27689846/236003269-f0531de3-f034-43d1-b0c2-2b6a0c9b85aa.png)

But when I use `docker compose up` it always shows the image _ghcr.io/open-telemetry/demo:1.4.0-adservice_ in Docker, no matter if I run it with or without the `--no-build` flag, and it doesn't consider any of the modifications I made (both files are missing):

![image](https://user-images.githubusercontent.com/27689846/236004254-fc30b812-75e2-49be-bcfd-5651529bafe2.png)

What am I doing wrong? Any help is appreciated!

Best Regards,
Kai

**Comment by julianocosta89** [comment]
Hello Kai,

To build your own image, you can run:

```
docker compose build <SERVICE_NAME>
```

Or, if you want to build all of the services, you can run the same command without the service name.

The image will have the same name though. So you will still see `ghcr.io/open-telemetry/demo` as repository.

**Comment by julianocosta89** [comment]
After built, you can use the:

```
docker compose up
```

To start  the demo.

**Comment by julianocosta89** [comment]
@kainawroth please feel free to re-open this issue if the problem persists.
