### ISSUE TITLE
Cannot build shippingservice : failed to parse platform in step 1/16

### ISSUE THREAD

**Issue by Vyankatesh5** [open-telemetry/opentelemetry-demo#883]
# Bug Report

Release : [v1.4.0](https://github.com/open-telemetry/opentelemetry-demo/releases/tag/1.4.0)

## Symptom
While building the image using "sudo docker-compose up " 
getting error 
"Building shippingservice
Sending build context to Docker daemon  52.66MB
Step 1/16 : FROM --platform=${BUILDPLATFORM} rust:1.69 as builder
failed to parse platform : "" is an invalid component of "": platform specifier component must match "^[A-Za-z0-9_-]+$": invalid argument
ERROR: Service 'shippingservice' failed to build : Build failed
"

## Reproduce
git clone https://github.com/open-telemetry/opentelemetry-demo.git
sudo docker-compose up

**Comment by julianocosta89** [comment]
Hello @Vyankatesh5 👋🏽 ,

Which OS are you using?

Could you try to build it running one of the following commands (depending on your OS architecture):

```
docker compose build emailservice --build-arg BUILDPLATFORM=linux/amd64
```

```
docker compose build emailservice --build-arg BUILDPLATFORM=linux/arm64
```

**Comment by Vyankatesh5** [comment]
It worked thanks @julianocosta89

**Comment by Vyankatesh5** [comment]
Hi @julianocosta89 
Still getting the same error
command
`sudo docker-compose build --build-arg BUILDPLATFORM=linux/amd64
`
![image](https://user-images.githubusercontent.com/14851386/237027432-3a33e14a-a1c9-485b-b352-af1b2959dbc8.png)

**Comment by julianocosta89** [comment]
Not sure if that would solve, but could you try with the newer version of `docker compose`?
I see that you are still using the `v1`.
The `v2+` doesn't use the dash between the words.

The command should be executed like this:
```
docker compose build --build-arg BUILDPLATFORM=linux/amd64
```

**Comment by Vyankatesh5** [comment]
Using `v2+`  solved the issue I was facing with the shippingservice 
But stuck on another one , while building 

![image](https://github.com/open-telemetry/opentelemetry-demo/assets/14851386/40b0da97-9700-490a-a565-673cf63741d0)

**Comment by julianocosta89** [comment]
Great new!

Lets try to fix this other one.
Could you try building just the `currencyservice`?

```
docker compose build currencyservice --no-cache
```

**Comment by Vyankatesh5** [comment]
Getting the error 
![image](https://github.com/open-telemetry/opentelemetry-demo/assets/14851386/d9af8dcb-c6f3-49f5-a303-18924b952590)


On another note :- I am using build because I have edited configuration files `https://github.com/open-telemetry/opentelemetry-demo/blob/main/src/otelcollector/otelcol-config-extras.yml` , it possible to pull other image and just build otelcolllector instead of building everything?

**Comment by julianocosta89** [comment]
you do not need to build everything when updating the `otelcol-config-extras.yml`.
Just running the demo should work

**Comment by Vyankatesh5** [comment]
Just to make sure after updating the `otelcol-config-extras.yml` and running `docker compose up --no-build` changes will be reflected?

**Comment by julianocosta89** [comment]
yes, because the config files are added as a volume in the otel-col container:
https://github.com/open-telemetry/opentelemetry-demo/blob/main/docker-compose.yml#L628-L630

**Comment by Vyankatesh5** [comment]
Thanks for the help @julianocosta89 . We can close this ticket.
