### ISSUE TITLE
Extract trace_id and span_id from logs

### ISSUE THREAD

**Issue by martin-majlis-s1** [open-telemetry/opentelemetry-demo#908]
# Bug Report

Which version of the demo you are using? (please provide either a specific
[commit
hash](https://github.com/open-telemetry/opentelemetry-demo/commits/main)
or a specific
[release](https://github.com/open-telemetry/opentelemetry-demo/releases)).

## Symptom

**What is the expected behavior?**

I am expecting to see `span_id` and `trace_id` as separate attributes so that other tools can easily extract them. It's because the configuration is [minimal](https://github.com/open-telemetry/opentelemetry-demo/blob/main/src/otelcollector/otelcol-config.yml). Based on the description of [attributesprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/attributesprocessor/README.md) it's not clear, whether this could be even achieved.

**What is the actual behavior?**

`span_id` and `trace_id` are part of the log message - `hipstershop.AdService - received ad request (context_words=[binoculars]) trace_id=b9c2b0640cbcbcf8f3c7788dd7ba8651 span_id=d3cc89ce0132578f trace_flags=01`

## Reproduce

Run `docker compose up` and observe logs.

We will close this issue if:

* The steps you provided are complex.
* If we can not reproduce the behavior you're reporting.

**Comment by mviitane** [comment]
Hi @martin-majlis-s1, `attributesprocessor` should not be needed. I'm able to see trace_id and span_id as separate attributes and not part of the log body. See below. It's the same for the Ad service and Recommendation service. 

You can get this detailed output by enabling detailed verbosity for the logging exporter.

```
exporters:
  logging:
    verbosity: detailed
```

```
otel-col  | 2023-06-07T09:49:40.580Z	info	LogsExporter	{"kind": "exporter", "data_type": "logs", "name": "logging", "resource logs": 1, "log records": 1}
otel-col  | 2023-06-07T09:49:40.580Z	info	ResourceLog #0
otel-col  | Resource SchemaURL: 
otel-col  | Resource attributes:
otel-col  |      -> telemetry.sdk.language: Str(python)
otel-col  |      -> telemetry.sdk.name: Str(opentelemetry)
otel-col  |      -> telemetry.sdk.version: Str(1.15.0)
otel-col  |      -> service.namespace: Str(opentelemetry-demo)
otel-col  |      -> service.name: Str(recommendationservice)
otel-col  | ScopeLogs #0
otel-col  | ScopeLogs SchemaURL: 
otel-col  | InstrumentationScope opentelemetry.sdk._logs._internal 
otel-col  | LogRecord #0
otel-col  | ObservedTimestamp: 1970-01-01 00:00:00 +0000 UTC
otel-col  | Timestamp: 2023-06-07 09:49:35.686955264 +0000 UTC
otel-col  | SeverityText: INFO
otel-col  | SeverityNumber: Info(9)
otel-col  | Body: Str(Receive ListRecommendations for product ids:['0PUK6V6EV0', 'HQTGWGPNH4', 'OLJCESPC7Z', 'L9ECAV7KIM', '1YMWWN1N4O'])
otel-col  | Attributes:
otel-col  |      -> otelSpanID: Str(ba6c54c117141502)
otel-col  |      -> otelTraceID: Str(97ffe23dd3d2851cbabcfdfdca030f46)
otel-col  |      -> otelServiceName: Str(recommendationservice)
otel-col  | Trace ID: 97ffe23dd3d2851cbabcfdfdca030f46
otel-col  | Span ID: ba6c54c117141502
otel-col  | Flags: 1
otel-col  | 	{"kind": "exporter", "data_type": "logs", "name": "logging"}
```
