### ISSUE TITLE
Update JS Dependencies

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry-demo#920]
Frontend and Payment Service are at 1.12, need to update to 1.13 per #916

**Comment by chigia001** [comment]
@austinlparker do we want to upgrade directly to 1.14 for the core and 0.40 for the experimental package?
There are new versions that release right after you audit those dependencies,
https://github.com/open-telemetry/opentelemetry-js/releases/tag/v1.14.0
https://github.com/open-telemetry/opentelemetry-js/releases/tag/experimental%2Fv0.40.0

**Comment by julianocosta89** [comment]
@chigia001 we can bump to the latest.
