### ISSUE TITLE
featureflagservice: version-pin dependencies

### ISSUE THREAD

**Issue by styblope** [open-telemetry/opentelemetry-demo#941]
There are a number of dependencies and downloads in the Dockerfile where we use current latest versions which breaks older demo version builds.

Specifically,  [this](https://github.com/open-telemetry/opentelemetry-demo/blob/1cf4e77d33a77dd9bc979f4584afea224593be8f/src/featureflagservice/Dockerfile#L38) latest rebar3 download breaks demo build on 1.4 release tag due to OTP version deprecation]

My workaroud (for 1.4 branch):
```diff
-RUN wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3 && mv rebar3 ~/.mix
+RUN wget https://github.com/erlang/rebar3/releases/download/3.20.0/rebar3 && chmod +x rebar3 && mv rebar3 ~/.mix
```

The other dependencies should be version locked too even though don't break the build.

> Let's consistently use version pinning everywhere throughout the demo to ensure backwards build compatibility and ease vendor forks maintenance!

**Comment by puckpuck** [comment]
We are version pinned in all service dependencies and dockerfile FROM images.
