### ISSUE TITLE
Feature flags span events must be set

### ISSUE THREAD

**Issue by agardnerIT** [open-telemetry/opentelemetry-demo#947]
# Feature Request

Demo should conform to OTEL standard regarding feature flag. Namely: A flag evaluation SHOULD be recorded as an Event on the span during which it occurred.

https://opentelemetry.io/docs/specs/otel/trace/semantic_conventions/feature-flags/#convention

**Is your feature request related to a problem?**

I need to see which feature flags (if any) where set on each span.

**Describe the solution you'd like:**

See above.

**Comment by austinlparker** [comment]
Need to make sure this works with the new flag service

**Comment by austinlparker** [comment]
flagd and the openfeature instrumentation properly records a span event for flag evaluations! closing this as complete
