### ISSUE TITLE
`docker compose up --no-build`  can't run

### ISSUE THREAD

**Issue by ianfor** [open-telemetry/opentelemetry-demo#971]
```
[2023-07-12 11:01:39.768][8][info][main] [source/server/server.cc:961] exiting
2023-07-12 19:01:39 Proto constraint validation failed (BootstrapValidationError.StaticResources: embedded message failed validation | caused by StaticResourcesValidationError.Clusters[0]: embedded message failed validation | caused by ClusterValidationError.LoadAssignment: embedded message failed validation | caused by ClusterLoadAssignmentValidationError.Endpoints[0]: embedded message failed validation | caused by LocalityLbEndpointsValidationError.LbEndpoints[0]: embedded message failed validation | caused by LbEndpointValidationError.Endpoint: embedded message failed validation | caused by EndpointValidationError.Address: embedded message failed validation | caused by AddressValidationError.SocketAddress: embedded message failed validation | caused by field: "port_specifier", reason: is required): static_resources {
2023-07-12 19:01:39   listeners {
2023-07-12 19:01:39     address {
2023-07-12 19:01:39       socket_address {
2023-07-12 19:01:39         address: "0.0.0.0"
2023-07-12 19:01:39         port_value: 8080
2023-07-12 19:01:39       }
2023-07-12 19:01:39     }
```

**Comment by julianocosta89** [comment]
Hello @ianfor,

Would you be able to provide more information?

Which OS are you running?
Which version?
What are the steps to reproduce the error?

**Comment by ianfor** [comment]
OS windows 10
Docker version 20.10.24, build 297e128
use command:
`git clone https://github.com/open-telemetry/opentelemetry-demo.git`
`cd opentelemetry-demo/`
`docker compose up --no-build`

**Comment by julianocosta89** [comment]
Could you try running:
```
docker compose up --no-build --pull 
```

**Comment by kedar-planit** [comment]
I am getting the same error 

OS: Ubuntu 20.04.6 LTS (GNU/Linux 5.15.0-1036-aws x86_64)
Docker version: Docker version 24.0.4, build 3713ee1

**Comment by Jayclifford345** [comment]
Hi there it also looks like I'm getting similar issue:
```
BootstrapValidationError.StaticResources: embedded message failed validation | caused by StaticResourcesValidationError.Clusters[0]: embedded message failed validation | caused by ClusterValidationError.LoadAssignment: embedded message failed validation | caused by ClusterLoadAssignmentValidationError.Endpoints[0]: embedded message failed validation | caused by LocalityLbEndpointsValidationError.LbEndpoints[0]: embedded message failed validation | caused by LbEndpointValidationError.Endpoint: embedded message failed validation | caused by EndpointValidationError.Address: embedded message failed validation | caused by AddressValidationError.SocketAddress: embedded message failed validation | caused by field: "port_specifier", reason: is required
```
Docker Desktop 4.21.1
Docker version 24.0.2, build cb74dfc
MacOS

**Comment by chigia001** [comment]
can you double check for OTEL_COLLECTOR_PORT_GRPC enviroment in your `.env`?
`docker compose up --no-build` might not able to pick that variable up
```
Proto constraint validation failed (BootstrapValidationError.StaticResources: embedded message failed validation 
  | caused by StaticResourcesValidationError.Clusters[0]: embedded message failed validation 
    | caused by ClusterValidationError.LoadAssignment: embedded message failed validation 
       | caused by ClusterLoadAssignmentValidationError.Endpoints[0]: embedded message failed validation 
         | caused by LocalityLbEndpointsValidationError.LbEndpoints[0]: embedded message failed validation 
           | caused by LbEndpointValidationError.Endpoint: embedded message failed validation 
             | caused by EndpointValidationError.Address: embedded message failed validation 
               | caused by AddressValidationError.SocketAddress: embedded message failed validation 
                 | caused by field: "port_specifier", reason: is required)
```

**Comment by Jayclifford345** [comment]
Hi @chigia001,
Many thanks for looking into this. So I can confirm the following:
envoy.tmpl.yml 
<img width="886" alt="Screenshot 2023-07-17 at 13 36 25" src="https://github.com/open-telemetry/opentelemetry-demo/assets/45856600/7b1d5dc1-aa2f-4319-801a-d8c3d87c993b">
docker-compose.yml
<img width="485" alt="Screenshot 2023-07-17 at 13 38 10" src="https://github.com/open-telemetry/opentelemetry-demo/assets/45856600/32e285e1-c2f8-4145-9d60-5e7830be8f70">
.env
<img width="834" alt="Screenshot 2023-07-17 at 13 40 12" src="https://github.com/open-telemetry/opentelemetry-demo/assets/45856600/2bf15017-e0a6-4815-8cea-265e6b527c02">

Should I manually specify these environment variables for the Otel collector manually?

**Comment by chigia001** [comment]
OK, I guess what going on
My PR rename that variable from OTEL_COLLECTOR_PORT to OTEL_COLLECTOR_PORT_GRPC
https://github.com/open-telemetry/opentelemetry-demo/pull/938/files#diff-98e571b5e585b55523fc0049e8e875b9bc21ef329b9d8c666f95a9304e556ac4L67

My guess is the docker image you are using is the old version which depend on OTEL_COLLECTOR_PORT and not OTEL_COLLECTOR_PORT_GRPC.

Can try to add OTEL_COLLECTOR_PORT to .env and docker-compose.yml and see if it working?

**Comment by Jayclifford345** [comment]
That's it up and running! 
So I guess the current issue is: Current containers from `docker compose up --no-build` to not contain the new environment variable reference. So need to pull latest.

Current fix: Either add the old environment variable or build from src.

Many thanks for your support in debugging [chigia001](https://github.com/chigia001)

**Comment by luizgribeiro** [comment]
I've think the issue still persists.
After searching for a new version in ghcr I saw that the one specified in `.env` is the most recent.

So from other PRs and Issues I'd say that it is work in progress, but the fix hasn't been released yet.

Until then, add the following to your `.env` (line 14)
```
OTEL_COLLECTOR_PORT=${OTEL_COLLECTOR_PORT_GRPC}
```

and this under `services > frontendproxy > environment`:
```
- OTEL_COLLECTOR_PORT
```
