### ISSUE TITLE
Please explain a bit more how this project works.

### ISSUE THREAD

**Issue by AndrewWPhillips** [open-telemetry/opentelemetry-demo#974]
# What is the purpose of this project?

I read the readme multiple times and I have a vague idea of the purpose.  I think it has a frontend and many (demo) backend services for a web-based shop. What are the core services?

I can clone, build and run it to work it out, but the readme should explains these things.  Or point to a simpler demo.

Use [Github Discussions](https://github.com/open-telemetry/opentelemetry-demo/discussions/).

**Comment by julianocosta89** [comment]
Hello @AndrewWPhillips, thanks for your feedback!

The documentation for the demo was actually moved to https://opentelemetry.io/docs/demo/.
Let us know if you would expect something else from the docs.

**Comment by AndrewWPhillips** [comment]
Thanks @julianocosta89, I didn't click on that link because it said it was "detailed documentation" and I was just looking for an overview.  I know a lot of projects tend to jump to the nitty gritty in the readme (mea culpa too).  I really think the readme could benefit from an introductory paragraph like this (assuming I got it right):

> The demo is based on the idea of an online shop called Astronomy Shop (not a real shop). It consists of many realistic services demonstrating use of OpenTelemetry in various languages.  For example, the Frontend (see src/frontend) demonstrates instrumentation of Javascript.

**Comment by julianocosta89** [comment]
This is exactly what we have here: https://opentelemetry.io/ecosystem/demo/
