### ISSUE TITLE
Installation of the Demo to Kubernetes Cluster is failing

### ISSUE THREAD

**Issue by constantinosmichael** [open-telemetry/opentelemetry-demo#975]
# Bug Report

Which version of the demo you are using?

[9f8806f](https://github.com/open-telemetry/opentelemetry-demo/commit/9f8806f7b81bcac424cbaab812f04fd2470114e4)

OS: CentOS 8
Kubernetes: minikube version: v1.30.1
Helm version : v3.10.1

## Symptom

When I run:

kubectl apply --namespace otel-demo -f https://raw.githubusercontent.com/open-telemetry/opentelemetry-demo/main/kubernetes/opentelemetry-demo.yaml

The pods fail to start

[root@astronomyshop ~]# kubectl get pods -n otel-demo
NAME                                                        READY   STATUS              RESTARTS   AGE
opentelemetry-demo-accountingservice-9f854ff88-mn7rv        0/1     Init:ErrImagePull   0          20h
opentelemetry-demo-adservice-7888bdfb48-4xkb2               0/1     ErrImagePull        0          20h
opentelemetry-demo-cartservice-56dd9476f7-bd7hs             0/1     Init:ErrImagePull   0          20h
opentelemetry-demo-checkoutservice-6448d84b79-4rx6b         0/1     Init:ErrImagePull   0          20h
opentelemetry-demo-currencyservice-76684c46fc-4q4xv         0/1     ErrImagePull        0          20h
opentelemetry-demo-emailservice-75b6bd5ddf-r6d2g            0/1     ErrImagePull        0          20h
opentelemetry-demo-featureflagservice-6bd59cbd5f-t6x2v      0/1     Init:ErrImagePull   0          20h
opentelemetry-demo-ffspostgres-77f6bbd88d-2s668             0/1     ErrImagePull        0          20h
opentelemetry-demo-frauddetectionservice-5d4c49c97d-fndx4   0/1     Init:ErrImagePull   0          20h
opentelemetry-demo-frontend-d9dd54d77-zjq8s                 0/1     ErrImagePull        0          20h
opentelemetry-demo-frontendproxy-5c47d4b9d6-m2gwc           0/1     ErrImagePull        0          20h
opentelemetry-demo-grafana-59bc87d55-crvsw                  0/1     ErrImagePull        0          20h
opentelemetry-demo-jaeger-7d677cd647-m7vhw                  0/1     ErrImagePull        0          20h
opentelemetry-demo-kafka-69477f986c-lpv2z                   0/1     ErrImagePull        0          20h
opentelemetry-demo-loadgenerator-67d8bb6d49-sd4sw           0/1     ErrImagePull        0          20h
opentelemetry-demo-otelcol-7f8456dffd-m6qk6                 0/1     ErrImagePull        0          20h
opentelemetry-demo-paymentservice-7bf88fc8d6-jfb4r          0/1     ErrImagePull        0          20h
opentelemetry-demo-productcatalogservice-5d5df8cbfc-nzs6j   0/1     ErrImagePull        0          20h
opentelemetry-demo-prometheus-server-7b57745866-dbxgt       0/1     ErrImagePull        0          20h
opentelemetry-demo-quoteservice-5fd7b86cf4-j2hsl            0/1     ErrImagePull        0          20h
opentelemetry-demo-recommendationservice-7c8d8d86b-rphsk    0/1     ErrImagePull        0          20h
opentelemetry-demo-redis-6b5dfd4db9-hmqh9                   0/1     ErrImagePull        0          20h
opentelemetry-demo-shippingservice-fb8656749-vqml8          0/1     ErrImagePull        0          20h

## Reproduce

1 - Set up a CentOS 8 server with minikube, helm version as above.
2 - Follow the instructions found here: https://opentelemetry.io/docs/demo/kubernetes-deployment/
3 - When you have run the commands found here: https://opentelemetry.io/docs/demo/kubernetes-deployment/#install-using-kubectl , wait a few moments for the pods to start then run **get pods -n otel-demo**. You will notice none are running.

**Comment by lalit-k** [comment]
@constantinosmichael Can you try to describe the pod if it provides more information.
`kubectl describe pod opentelemetry-demo-accountingservice-9f854ff88-mn7rv -n otel-demo`

**Comment by constantinosmichael** [comment]
Trying this out now

**Comment by chigia001** [comment]
Do you still have issue?
Can you check if #981 fixed it?

**Comment by constantinosmichael** [comment]
(Most ) pods are running. I think this fixed it.
